var IS_CHROME=!0,tabStorage={},TRUE_BLOCK=!1,bridge={isChrome:!0,browser_name:"chrome",tabs:{sendRequest:function(a,b,c){chrome.tabs.sendRequest(a,b,c)}},initPopover:function(a,b,c){popoverDocument=c;webdb.updateTotalBlocked();chrome.tabs.getSelected(a,function(a){if(a.id in tabStorage)b(a);else if(a=c.getElementById("notscanned"))a.innerHTML=DNTP._("dntp.notscanned")})},localeInit:function(){DNTP.currentLocale=navigator.language.replace(/\-.*/,"").toLowerCase()},settings:{getItem:function(a,b){var c=
localStorage.getItem(a);!c&&b&&(c=b);return c},setItem:function(a,b){b===null?localStorage.removeItem(a):localStorage.setItem(a,b)},clear:function(a){localStorage.removeItem(a)}},_:function(a,b){var c=null,a=a.replace(/\./g,"_");arguments.length>1&&(b=Array.prototype.slice.call(arguments,1));try{DNTP.bundle?(c=DNTP.bundle[a].message)&&b&&(c=c.replace(/\$([0-9]+)/g,function(a,c){return b[parseInt(c)-1]})):c=chrome.i18n.getMessage(a,b)}catch(e){}if(!c||c=="")c="***"+a;return c},initMessageHandler:function(){chrome.extension.onRequest.addListener(handleMessage)},
initTabListener:function(){chrome.tabs.onRemoved.addListener(function(a){clearTabData(a)});chrome.tabs.onUpdated.addListener(function(a){updateToolbarIcon(a)})},showPostInstallPage:function(a){this.openNewTab(a)},initTheme:function(){if(DNTP.theme===null){DNTP.theme=DNTP.Config.get("theme","light");if(DNTP.theme=="default")DNTP.theme="";var a="webkit/popup.html";DNTP.theme!=""?(a="chrome/content/themes/"+DNTP.theme+"/webkit.html",DNTP.getImageUrl=function(a){return"images/"+a},DNTP.getResourceUrl=
function(a){return"../../"+a}):(DNTP.getImageUrl=function(a){return"../chrome/content/images/"+a},DNTP.getResourceUrl=function(a){return"../chrome/content/"+a});chrome.browserAction.setPopup({popup:a})}},initPopoverListener:function(){this.initTheme()},addLinkHandlers:function(){},openNewTab:function(a){chrome.tabs.create({url:a,selected:!0})},getCurrentTabErrors:function(a){return tabStorage[a].pageErrors},cookies:{set:function(a){chrome.cookies.set(a)},remove:function(a){chrome.cookies.remove(a)}},
app:{getDetails:function(){return chrome.app.getDetails()}},updateNotificationsTabData:function(a,b){var c=getTabData(a);if(c)c.abineNotifications=b}};DNTP.closePopup=function(){popoverDocument.defaultView.close()};function resizePopup(){}
function getTabData(a,b){if(!a)return{};if(!(a in tabStorage)){if(b)return!1;tabStorage[a]={tabId:a,abineHosts:{length:0},abineTracking:{length:0},abineBlocked:{length:0},abineOptout:{length:0},disabledHere:!1,startTime:new Date,urlsBlocked:{},host:null,url:null,pageErrors:[]}}return tabStorage[a]}function clearTabData(a){a&&(a in tabStorage&&(DNTP.Events.trigger("PageUnload",tabStorage[a]),delete tabStorage[a]),webdb.updateTotalBlocked())}
var shouldLoad=function(a){var b={cancel:!1};if(a.tabId==-1||DNTP.pauseContentPolicy)return b;var c={},e=getTabData(a.tabId);if(e.disabledHere)return b;var f=e.host;if(!f)return b;var e=a.url,d=e.getDomain();if(!d)return b;c.req_host=d;c.url=e;var h=null,g={sub_frame:"iframe",script:"script",xmlhttprequest:"object",image:"image",object:"object",other:"object"};if(a.type!="script"||!e.match(combinerScripts))h=getMatchingRuleV2(e,e.getHostname(),g[a.type]);if(c.rule=h){var g=h.name,i=!1;if(useGlobalAllow&&
h.allowDomain){if(!h.allowDomain.source)h.allowDomain=RegExp(h.allowDomain,"i");f.match(h.allowDomain)&&(i=!0)}if(f=trackerIsBlocked(DNTP.settings.trackerMap,f,g,i))c.isBlocked=!0,b=a.type=="image"?{redirectUrl:chrome.extension.getURL("webkit/chrome/blank.gif")}:a.type=="sub_frame"?{redirectUrl:chrome.extension.getURL("webkit/chrome/blank.html")}:{cancel:!0},c.message="requestBlocked",bridge.tabs.sendRequest(a.tabId,c,function(){});updateTabData(g,d,f,i,a.tabId,e,a.type)}else updateTabData(null,d,
!1,!1,a.tabId);return b},addDNTHeader=function(a){a.requestHeaders.push({name:"DNT",value:"1"});return{requestHeaders:a.requestHeaders}},handleMessage=function(a,b,c){if(a.message=="loadRules"){var e=b.tab.id;a.topWindow&&clearTabData(e);var f=b.tab.url.getDomain(),d=getTabData(e);if(!d.host)d.host=f,d.disabledHere=f in disabledSites;d.url=b.tab.url;a.topWindow&&updateToolbarIcon(e);TRUE_BLOCK?c({topDomain:f,urlsBlocked:d.urlsBlocked}):(b={},b["*"]=DNTP.settings.trackerMap["*"],b[f]=DNTP.settings.trackerMap[f],
c({trackerMap:b,domainMap:domainMap,disabledHere:d.disabledHere,topDomain:f}))}else if(a.message=="newHost")TRUE_BLOCK==!1&&updateTabData(null,a.requestHost,!1,!1,b.tab.id);else if(a.message=="trackerFound")TRUE_BLOCK==!1&&updateTabData(a.ruleName,a.requestHost,a.blocked,a.allowedByTopDomain,b.tab.id);else if(a.message=="allowTracker")toggleTrackerFromBackground(!1,a.name,a.host,b.tab.id);else if(a.message=="computeBadgeAndNotifications")DNTP.BadgeManager.compute(b.tab.id),d=getTabData(b.tab.id),
DNTP.computeNotifications(null,d),updateToolbarIconWithData(d,b.tab.id);else if(a.message=="testNotifications"){if(DNTP.NotificationManager.noteCounts={},a.newMsgs)DNTP.notificationMessages=a.newMsgs.messages,d=getTabData(b.tab.id),DNTP.computeNotifications(null,d),updateToolbarIconWithData(d,b.tab.id)}else a.message=="changeLocale"?(DNTP.bundle=null,a.locale&&DNTP.sendRequest("../../_locales/"+a.locale+"/messages.json",function(b){b?(DNTP.currentLocale=a.locale,DNTP.bundle=JSON.parse(b)):(DNTP.currentLocale=
navigator.language.replace(/\-.*/,"").toLowerCase(),DNTP.bundle=null)})):a.message=="recordError"?(e=b.tab.id,d=getTabData(e),d.pageErrors.push(a.errorMsg),d.pageErrors.length>5&&d.pageErrors.shift()):a.message=="PageLoadDone"?(e=b.tab.id,d=getTabData(e),d.referrer=a.referrer,d.title=a.title,DNTP.Events.trigger("PageLoad",d)):a.message=="PageUnload"?(e=b.tab.id,d=getTabData(e),DNTP.Events.trigger("PageUnload",d)):a.message=="getDailyTotals"?c(JSON.stringify(DNTP.getDailyTotals(a.year))):a.message==
"getBadTrackerTotals"&&c(JSON.stringify(DNTP.getBadTrackerTotals()))},updateTabData=function(a,b,c,e,f,d,h){var g=getTabData(f);b in g.abineHosts||(g.abineHosts[b]=1,g.abineHosts.length++);if(a){var i=g.abineTracking,b=!1;a in i||(i[a]=e?2:1,i.length++,b=!0);if(c)e=g.abineBlocked,a in e||(e[a]=1,e.length++,b=!0,a in DNTP.socialBlocked&&DNTP.socialBlocked[a]++,totalBlocked++),g.urlsBlocked[d]={rule:a,type:h};b&&(updateToolbarIcon(f),DNTP.Events.trigger(c?"TrackerBlocked":"TrackerFound",null,g.host,
a,null,d,g.url),DNTP.Events.trigger("TrackerCountChanged",g))}};function siteDisabled(a,b){getTabData(a).disabledHere=b}function updateToolbarIcon(a){updateToolbarIconWithData(getTabData(a),a)}
function updateToolbarIconWithData(a,b){var c=[255,0,0,255],e=[225,193,0,255],f=[0,255,0,255],d="Do Not Track Me",h="0";if(a.disabledHere)h=DNTP._("dntp.tooltip.off"),d+=" "+DNTP._("dntp.tooltip.onoff"),f=c;else if(a.abineTracking){var g=a.abineTracking.length+a.abineOptout.length,i=a.abineBlocked.length+a.abineOptout.length,i=i?i:"0",g=g?g:"0";d+="\n"+DNTP._("dntp.tooltip.txt",i,g);h=""+g;if(a.host&&a.host.replace(/^www[0-9]*\./,"")in DNTP.socialMap)f=e;else if(i<g){var f=e,e=a.abineTracking?a.abineTracking:
[],g=a.abineBlocked?a.abineBlocked:[],j;for(j in e)j!="length"&&e[j]!=2&&!g[j]&&(f=c)}}chrome.browserAction.setBadgeBackgroundColor({color:f,tabId:b});chrome.browserAction.setTitle({title:d,tabId:b});c="../../Icon.png";f=DNTP.Config.get("newTrackers","");if(d=DNTP.BadgeManager.getUnviewedBadge())c=DNTP.IMAGE_PATH+d.icon.replace(/.png/,"-sm.png");else if(a.abineNotifications&&a.abineNotifications.hasAlertIcon||f&&f.length>0)c=DNTP.IMAGE_PATH+"privacy_alert_toolbar.png",h="";chrome.browserAction.setBadgeText({text:h,
tabId:b});chrome.browserAction.setIcon({path:c,tabId:b})}try{chrome.webRequest.onBeforeRequest.addListener(shouldLoad,{urls:["<all_urls>"],types:"sub_frame,script,xmlhttprequest,image,object,other".split(",")},["blocking"]),chrome.webRequest.onBeforeSendHeaders.addListener(addDNTHeader,{urls:["<all_urls>"]},["blocking","requestHeaders"]),TRUE_BLOCK=!0}catch(e$$6){};