var D=window.D||{},newCount;D.useConfig=function(a){D.config={cn:{TOOLBAR_SERVER:"http://toolbar3.diigo.cn",UPLOAD_SERVER:"http://www.diigo.cn",DOMAIN:"diigo.cn"},www:{TOOLBAR_SERVER:"http://toolbar3.diigo.com",UPLOAD_SERVER:"http://www.diigo.com",DOMAIN:"diigo.com"},preview:{TOOLBAR_SERVER:"http://preview.diigo.com",UPLOAD_SERVER:"http://preview.diigo.com",DOMAIN:"diigo.com"}}[{dev:"cn",dev1:"preview",dev2:"www"}[a]||a];if(/dev/.test(a))D.config.dontUseGA=true};var GlobalData;
function resetGlobalData(){GlobalData={signedIn:false,user:"",userId:null,realName:"",userLevel:0,myTags:[],myBmLists:[],myGroups:[],myContacts:[],permissions:{capture:true,image:true,premium:true,snapshot:true}}}
var SignInManager=D.SignInManager={checkSignInCookie:function(a){var b=this;chrome.cookies.get({url:"http://"+D.config.DOMAIN,name:"diigoandlogincookie"},function(c){if(c)var d=c.value.split("-.-")[1];b.onUsernameSeen(d);a&&a()})},onUsernameSeen:function(a){if(a)if(this.isSignedIn()){if(a!=GlobalData.user){this._onSignOut();this._onSignIn(a)}}else this._onSignIn(a);else this.isSignedIn()&&this._onSignOut()},isSignedIn:function(){return GlobalData.user&&GlobalData.signedIn},isUserInfoLoaded:function(){return this.isSignedIn()&&
GlobalData.username},_onSignIn:function(a){debug("[SignInManager] _onSignIn",a);GlobalData.user=a;GlobalData.signedIn=true;this.loadMyStuff();EventMachine.needToReload();forEachWebTab(function(b){Messenger.send(b.id,{name:"signIn",details:{user:a},fromTabId:null})});CrossPromotion.userChanged()},_onSignOut:function(){debug("[SignInManager] _onSignOut",GlobalData.user);resetGlobalData();Preloader.cleanUpAllTabData();forEachWebTab(function(a){Messenger.send(a.id,{name:"signOut",fromTabId:null})})},
loadMyStuff:function(){debug("[SignInManager] loadMyStuff",GlobalData.user);(new WebAPICall).invoke("user_loadMyStuff",{what:"myTags myGroups myProfile myBookmarkLists myContacts permissions"},{user:GlobalData.user,transId:null,complete:function(a){a.resp&&forEachWebTab(function(b){Messenger.send(b.id,{name:"myStuffLoaded",details:a.resp.result,fromTabId:null})})}})}},Preloader=D.Preloader={table:{},init:function(){},onTabRemoved:function(a){this.cleanUpTabData(a)},onTabUpdated:function(a,b,c){console.log("update:",
b.status);var d=this;if(b.status=="loading"){d.table[a]&&d.cleanUpTabData(a);if(SignInManager.isSignedIn()){b=c.url;if(isURLApplicable(b)){var e=new WebAPICall;d.table[a]={api:e,loading:true};debug("[Preloader]","loading for",a,b);e.invoke("bm_loadBookmark",{url:b,what:"bookmarkInfo annotations pageComments"},{user:GlobalData.user,complete:function(f){d.table[a].loading=false;console.log("z.table[tabId].loading:",d.table[a].loading);if(!f.cancelled)if((f=f.resp)&&f.code==1){d.table[a].result=f.result;
f.result.saved&&d.updateBrowserActionIcon(c.id,true);Messenger.send(a,{name:"refreshBookmarkInfo"});if(Prefs.get("prefs.autoload")=="true"&&f.result.saved&&f.result.annotations.length>0){console.log("auto show highlight!!!!");sendRunCommand(a)}}}})}}}else if(b.status=="complete"){console.log(d.table[a]);if(d.table[a]){console.log(d.table[a].loading);if(d.table[a].loading!=true){b=d.table[a].result;console.log(Prefs.get("prefs.autoload")=="true",b.saved,b.annotations.length>0);if(Prefs.get("prefs.autoload")==
"true"&&b.saved&&b.annotations.length>0){console.log("auto show highlight!!!!");sendRunCommand(a)}}}else console.log(d.table[a])}},cleanUpAllTabData:function(){for(var a in this.table)this.cleanUpTabData(a)},cleanUpTabData:function(a){if(this.table[a]){debug("[Preloader] cleaning up",a);this.table[a].api.cancel();delete this.table[a]}},preloadedResultForTab:function(a){if(this.table[a])return this.table[a].result;return null},isPreloadingForTab:function(a){return(a=this.table[a])&&a.loading},updateBrowserActionIcon:function(a,
b){chrome.browserAction.setIcon({tabId:a,path:"img/"+(b?"logo-19-bookmarked.png":"logo-19.png")})}};
function isURLApplicable(a){var b=parseUri(a),c=b.path;if(!/^https?$/i.test(b.protocol))return false;if(/\.?diigo\./i.test(b.host))if(/^\/annotated\//i.test(c))return false;else if(/(player|slides?)\.diigo\./i.test(b.host)&&/^\/(list|feed)/i.test(c))return false;else if(/^\/bookmark\//i.test(c))return false;else{if(/^\/cached/i.test(c))return false}else if(/^https?:\/\/chrome\.google\.com\/(extensions|webstore)/i.test(a))return false;return true}
var Messenger={send:function(a,b,c){debug("bg send msg to",a,b.name,b);chrome.tabs.sendRequest(a,b,c)},onMessage:function(a,b,c){debug("bg recv msg from",b.tab&&b.tab.id,a.name,a,b);this.handlers[a.name](a,b,c)},handlers:{showToolbar:function(){showToolbar()},newtip:function(){chrome.browserAction.setBadgeText({text:""});window.open("http://www.diigo.com/extension/chrome/new.html?v="+D.version);newCount=0},annotateAfterSaving:function(a){localStorage["prefs.annotateAfterSaving"]=a.data==true?"true":
"false"},capture:function(a){chrome.tabs.captureVisibleTab({format:"png"},function(b){chrome.tabs.getSelected(null,function(c){console.log("send dataURL",a);chrome.tabs.sendRequest(c.id,{name:"dataURL",dataURL:b,cw:a.cw,ch:a.ch,ct:a.ct,cl:a.cl,target:a.target})})})},WebAPI:function(a,b,c){a=a.details;(new WebAPICall).invoke(a.cmd,a.data,{user:GlobalData.user,transId:a.transId,complete:function(d){console.log(d.status,d.resp);d&&c({status:d.status,resp:d.resp,cmd:d.cmd})}})},ifSignIn:function(){chrome.cookies.get({url:"http://www.diigo.com",
name:"diigoandlogincookie"},function(a){a&&chrome.tabs.getSelected(null,function(b){chrome.tabs.sendRequest(b.id,{name:"SignedIn"})})})},updateGlobalData:function(a,b){console.log("updateGlobalData");var c={},d=a.details;for(var e in d)if(d[e]!=GlobalData[e])c[e]=GlobalData[e]=d[e];forEachWebTab(function(f){Messenger.send(f.id,{name:"globalDataChanged",details:{changes:c},fromTabId:b.tab.id})})},initialData:function(a,b,c){c({extensionID:D.extensionID,globalData:GlobalData,preloadedPrefs:Prefs.get(Prefs.prefsToPreload),
tabId:b.tab.id,version:D.version,loadBookmarkResult:Preloader.preloadedResultForTab(b.tab.id),shouldLoadBookmarkByMyself:!Preloader.isPreloadingForTab(b.tab.id),shoudLoadMyStuff:!GlobalData.realName||EventMachine.needToReload()})},bookmarkChanged:function(a,b){var c=a.details;console.log(c);D.Preloader.updateBrowserActionIcon(b.tab.id,c.saved)},updateBrowserActionIconToDoing:function(a,b){chrome.browserAction.setIcon({tabId:b.tab.id,path:"/img/doing-icon.png"})},saveImageToDiigo:function(a,b){console.log(a);
D.saveImageToDiigo(a.details,b.tab,a.Type)},checkIn:function(){},activateMeAfterSignIn:function(a,b){D.activateTheTabIdAfterSignIn=b.tab.id},createTab:function(a,b){chrome.tabs.create({url:a.details.url,index:b.tab.index+1})},closeTab:function(a,b){setTimeout(function(){chrome.tabs.remove(b.tab.id)},600)},openWindow:function(a){a=a.details;window.open(a.url,a.name,a.features)},getPrefs:function(a,b,c){console.log("getprefs",a);a=Prefs.get(a.details.keys);console.log(a);c(a)},setPrefs:function(a,b,
c){a=Prefs.set(a.details.data,null,b.tab.id);c&&c(a)},getUserData:function(a,b,c){a=Prefs.getUserData(a.details.keys);console.log(a);c(a)},setUserData:function(a,b,c){a=Prefs.setUserData(a.details.data,b.tab.id);c&&c(a)},twitterGrabPin:function(a,b){TwitterOAuth.getAccessToken(a.details.pin,b.tab.id)},twitterCheckAuthentication:function(a,b,c){c(TwitterOAuth.checkAuthentication())},twitterSend:function(a,b,c){TwitterOAuth.updateStatus(a.details,c)},twitterChangeUser:function(a,b){D.switchToTabIdAfterTwitterOauth=
b.tab.id;TwitterOAuth.changeUser()},twitterConnect:function(a,b){D.switchToTabIdAfterTwitterOauth=b.tab.id;TwitterOAuth.changeUser()},shortenUrl:function(a,b,c){var d=a.details.url;debug("[bit.ly short url] making",d);$.ajax({url:"http://api.bit.ly/shorten?version=2.0.1&login=diigo&apiKey=R_051efe0ca04a325db066155db77c2d08&longUrl="+encodeURIComponent(d),timeout:1E4,type:"GET",complete:function(e,f){if(f=="success"){try{var g=JSON.parse(e.responseText)}catch(h){error("error parsing json from bit.ly",
e.responseText);c(d);return}if(g.statusCode=="OK"){d=g.results[d].shortUrl;debug("[bit.ly url] success",d)}else error("[bit.ly url] failure",g)}else error("[bit.ly url] failure",e);c(d)}})},uploadCache:function(a,b){var c=a.details;(new CachePage({urlMD5:c.urlMD5,text:c.text,html:c.html,groups:c.groups,tabId:b.tab.id,username:GlobalData.user,ispdf:c.ispdf,pdfurl:c.pdfurl})).start()},pickPromotionMessage:function(a,b,c){c(CrossPromotion.pickMessage())},promotionMessageClicked:function(a){CrossPromotion.messageClicked(a.details.id)},
searchDiigoGoogle:function(a,b){D.searchDiigoGoogle(a.details.text,b.tab)},copy:function(a){function b(d){var e=document.createElement("textarea");document.body.appendChild(e);e.value=d;e.select();document.execCommand("copy");document.body.removeChild(e)}function c(d){var e=document.createElement(e);e.innerHTML=d;document.body.appendChild(e);d=window.getSelection();d.removeAllRanges();d.selectAllChildren(e);document.execCommand("copy");d.removeAllRanges();document.body.removeChild(e)}a=a.details;
if(a.text)b(a.text);else a.html&&c(a.html)},changeColor:function(a){console.log(a.color);localStorage["prefs.lastUsedColor"]=a.color},sample:function(){}}};function getAllTabs(a){chrome.windows.getAll({populate:true},function(b){var c=[];b.forEach(function(d){d.tabs.forEach(function(e){c.push(e)})});a(c)})}function forEachWebTab(a){forEachTab(a,function(b){return/^https?:\/\//.test(b.url)})}function forEachTab(a,b){getAllTabs(function(c){c.forEach(function(d){if(!b||b(d))a(d)})})}
function broadcastMessage(a){chrome.windows.getAll({populate:true},function(b){b.forEach(function(c){c.tabs.forEach(function(d){Messenger.send(d.id,a)})})})}function executeContentScripts(a,b,c){function d(){if(e<b.length){debug("executing "+b[e]);chrome.tabs.executeScript(a,{file:b[e++]},d)}else c&&c()}var e=0;d()}
function getExtensionVersion(){try{var a=chrome.extension.getURL("manifest.json"),b=new XMLHttpRequest;b.open("GET",a,false);b.send(null);return JSON.parse(b.responseText).version}catch(c){error("Failed to get version number",c);return""}}function sendRunCommand(a,b){Messenger.send(a,{name:"run",details:extend({extensionID:D.extensionID,version:D.version,logLevel:D.logLevel},b||{})})}
function showToolbar(){chrome.tabs.getSelected(null,function(a){if(/^https?:\/\/chrome\.google\.com\/(extensions|webstore)/i.test(a.url))alert(chrome.i18n.getMessage("alertGallery"));else if(isURLApplicable(a.url)){chrome.tabs.executeScript(a.id,{file:"js/checkTab.js"},function(){debug("executeScript callback")});EventMachine.onActivate();sendRunCommand(a.id,{userClick:true})}else alert(chrome.i18n.getMessage("alertUnsupportedPage"))})}
function init(){D.logLevel=localStorage.logLevel||"never";D.version=getExtensionVersion();D.extensionID=chrome.extension.getURL("").match(/:\/\/(\w+)\//)[1];Upgrader.check();Prefs.setDefaultPrefs();resetGlobalData();console.log("GlobalData",GlobalData);SignInManager.checkSignInCookie();TwitterOAuth.init();EventMachine.init();D.Preloader.init();ContextMenu.init();ComboSearch.init();CrossPromotion.init();chrome.extension.onRequest.addListener(function(a,b,c){console.log(a.name);Messenger.onMessage(a,
b,c)});chrome.tabs.onUpdated.addListener(function(a,b,c){if(b.url==chrome.extension.getURL("")){console.log("remove");chrome.tabs.remove(c.id)}console.log(c.url);if(b.status=="complete"&&/diigo\.(com|cn)\/images\/diigo-logo.png#SIGNED_IN/i.test(c.url)){debug("[Sign in tab opened by extension detected!]",a,b,c);chrome.tabs.remove(a);chrome.tabs.update(D.activateTheTabIdAfterSignIn,{selected:true})}EventMachine.onTabUpdated(a,b,c);SignInManager.checkSignInCookie(function(){Prefs.get("prefs.autoloadBookmarkStatus")===
"true"&&Preloader.onTabUpdated(a,b,c);if(Prefs.get("prefs.SearchO")==="true"){var d=Prefs.get("prefs.comboSearch")==="true"?true:false;SearchO.init(a,b,c,d)}if(Prefs.get("prefs.comboSearch")==="true"){d=Prefs.get("prefs.SearchO")==="true"?true:false;ComboSearch.onTabUpdated(a,b,c,d)}})});chrome.tabs.onRemoved.addListener(function(a){Preloader.onTabRemoved(a)})}
var Prefs={prefsToPreload:"prefs.bookmark.privateByDefault".split(" "),_observers:[],observeChanges:function(a){this._observers.push(a)},_notifyChanges:function(a){for(var b=0,c=this._observers.length;b<c;b++)this._observers[b].call(null,a)},setDefaultPrefs:function(){function a(c,d){if(b.get(c)===null){var e={};e[c]=d;Prefs.set(e)}}var b=this;a("prefs.contextMenu",true);a("prefs.autoload",false);a("prefs.autoloadBookmarkStatus",false);a("prefs.comboSearch",true);a("prefs.SearchO",true);a("prefs.annotateAfterSaving",
false);a("prefs.autoShowHighlightIcon",true);a("prefs.lastUsedColor","yellow");a("prefs.autoImageClipper",false);a("prefs.shortcutQuicksave",true);a("prefs.shortcutBookmark",true);a("prefs.shortcutAnnotate",true);a("prefs.shortcutQuicksaveCtrl",true);a("prefs.shortcutQuicksaveAlt",true);a("prefs.shortcutBookmarkCtrl",true);a("prefs.shortcutBookmarkAlt",true);a("prefs.shortcutAnnotateCtrl",true);a("prefs.shortcutAnnotateAlt",true);a("prefs.autoCloseReadLater",false);a("prefs.shortcutQuicksaveKey",
"Q");a("prefs.shortcutBookmarkKey","D");a("prefs.shortcutAnnotateKey","A")},prefixForUser:function(){var a=GlobalData.user;if(!a||a.length==0)throw"Invalid user";return"user."+a+"."},get:function(a,b){b=b||"";if($.isArray(a)){var c={};a.forEach(function(d){c[d]=localStorage.getItem(b+d)});return c}else return this.get([a],b)[a]},setObject:function(a,b){b=b||"";var c={};forEach(a,function(d,e){var f=b+e;debug("[prefs] set",f,d);d=String(d);if(localStorage.getItem(f)!=d){localStorage.setItem(f,d);c[f]=
d}});return c},set:function(a,b,c){var d=this.setObject(a,b);if(!$.isEmptyObject(d)){forEachWebTab(function(e){Messenger.send(e.id,{name:"prefsChanged",details:{data:d},fromTabId:c})});this._notifyChanges(d)}return d},remove:function(a,b){b=b||"";if($.isArray(a)){var c={};a.forEach(function(d){c[d]=localStorage.removeItem(b+d)});return c}else return this.remove([a],b)[a]},getUserData:function(a){return this.get(a,this.prefixForUser())},setUserData:function(a,b){return this.set(a,this.prefixForUser(),
b)},removeUserData:function(a){return this.remove(a,this.prefixForUser())}},EventMachine=D.EventMachine={_locationCounter:0,_activationCounter:0,_lastReloadTime:new Date,_shouldReload:false,init:function(){},onTabUpdated:function(a,b,c){b.status=="complete"&&this.changeLocation(c.url)},onActivate:function(){this._activationCounter++;if(this._activationCounter>=5){debug("[EventMachine] onActivate 5 times");this._shouldReload=true;this._activationCounter=0}},needToReload:function(){if(((new Date).getTime()-
this._lastReloadTime.getTime())/1E3/60>15){debug("[EventMachine] 15 mins");this._shouldReload=true}if(this._shouldReload){this._shouldReload=false;this._locationCounter=this._activationCounter=0;this._lastReloadTime=new Date;return true}else return false},changeLocation:function(){var a=++this._locationCounter;if(a%20==0){debug("[EventMachine] changeLocation 20 times");this._shouldReload=true}if(a>16777215)this._locationCounter=0}},ContextMenu={init:function(){var a=this;Prefs.get("prefs.contextMenu")!=
"false"&&this.createContextMenu();Prefs.observeChanges(function(b){b=b["prefs.contextMenu"];if(b!==undefined)b=="true"?a.createContextMenu():a.removeContextMenu()})},createContextMenu:function(){var a=chrome.contextMenus.create({title:"Save image to Diigo",contexts:["image"]});chrome.contextMenus.create({title:"Tag as a stand-alone item",contexts:["image"],parentId:a,onclick:function(b,c){D.saveImageToDiigo(b,c,"tag")}});chrome.contextMenus.create({title:"Attach it to the page URL",contexts:["image"],
parentId:a,onclick:function(b,c){D.saveImageToDiigo(b,c,"attach")}});a=chrome.contextMenus.create({title:"Diigo"});chrome.contextMenus.create({title:"Bookmark and Annotate",parentId:a,onclick:function(){showToolbar()}});chrome.contextMenus.create({title:"Read Later",parentId:a,onclick:function(b,c){chrome.tabs.sendRequest(c.id,{name:"readlater"})}});chrome.contextMenus.create({title:"Search Diigo+Google for selection",contexts:["selection"],onclick:function(b,c){D.searchDiigoGoogle(b.selectionText,
c)}})},removeContextMenu:function(){chrome.contextMenus.removeAll()}};D.searchDiigoGoogle=function(a,b){if(a&&a.length>0){var c={url:"http://www.diigo.com/search/g?cx=!partner-pub-7625644023173335%3A7j8qgl-cf10&cof=FORID:11&ie=UTF-8&q="+encodeURIComponent(a)+"&sa=Search"};if(b)c.index=b.index+1;chrome.tabs.create(c)}};
D.saveImageToDiigo=function(a,b,c){console.log(a);var d=new XMLHttpRequest;d.open("GET",a.srcUrl,true);d.responseType="blob";d.onload=function(){if(this.status==200){var e=new Blob([this.response],{type:"image/png"});console.log(e);var f=new FileReader;f.onload=function(){console.log(f.result);chrome.tabs.sendRequest(b.id,{name:"saveImageToDiigo",data:f.result,type:c})};f.readAsDataURL(e)}};d.send()};var WebAPICall=function(a){this.context=a};
WebAPICall.prototype={invoke:function(a,b,c){this.callOptions=c;var d=c.transId||WebAPICall.transIdStepper++,e=c.user;d={cmd:a,v:13,_nocache:Math.random(),json:JSON.stringify(b),user:e,transId:d};debug("[WebAPICall]",a,b);b=D.config.TOOLBAR_SERVER;this.performInvocation(a=="user_signIn"?evalTpl(b+"/chappai/pv=#{pv}/ct=tb/cv=#{cv}/cmd=#{cmd}",{pv:13,cv:D.version,cmd:a}):evalTpl(b+"/chappai/pv=#{pv}/ct=tb/cv=#{cv}/user=#{user}/cmd=#{cmd}/",{pv:13,cv:D.version,user:e,cmd:a}),d,c,a)},cancel:function(){this.cancelled=
true;if(this.xhr){this.xhr.abort();this.xhr=null}},performInvocation:function(a,b,c,d){var e=this;e.xhr=$.ajax({type:"POST",url:a,data:b,complete:function(f){try{var g=JSON.parse(f.responseText)}catch(h){debug("[WebAPICall error parsing JSON]",h,f)}debug("[WebAPI ajax response]",f.status,g);if(d=="upload_file"||d=="bm_saveBookmark"){e.status=f.status;e.cmd=d}if(e.resp=g){if(g.code==1)e.ok=true;g.user&&SignInManager.onUsernameSeen(g.user)}c.complete(e,g);e.xhr=null},error:function(f,g,h){debug("[WebAPI ajax error]",
f,g,h)}})}};var WebAPICall_Static={transIdStepper:1,_baseUrl:null,setup:function(a){this._baseUrl=a.baseUrl}};extend(WebAPICall,WebAPICall_Static);
var Upgrader={check:function(){var a=D.version,b=Prefs.get("version")||"0";this.compareVersion(a,b)>0&&this.upgrade(b)},upgrade:function(a){debug("Performing upgrade from",a,"to",D.version);this.isVersionBefore(a,"1.6.2.4")&&Prefs.set({"prefs.autoloadBookmarkStatus":true});Prefs.set({version:D.version})},compareVersion:function(a,b){function c(e){if(/[^\d.]/.test(e))throw"version must be in formatted like 1.2.4";return e.split(".").map(function(f){return parseInt(f,10)})}if(a===b)return 0;a=c(a);
b=c(b);for(var d=0;d<a.length&&d<b.length;d++)if(a[d]!=b[d])return a[d]>b[d]?1:-1;if(a.length==b.length)return 0;return a.length>b.length?1:-1},isVersionBefore:function(a,b,c){if(c===undefined)c=false;a=this.compareVersion(a,b);if(c&&a==0)return true;return a<0}};$(document).ready(init);
