var Bg=chrome.extension.getBackgroundPage(),Prefs=Bg.Prefs;
$(document).ready(function(){$("#btnSave").click(function(){save();$("#noticeSaved").fadeIn("slow").delay(1E3).fadeOut("slow");return false});$("#btnCancel").click(function(){window.close();return false});buildSelect();prefs2UI();(function(){var a=$("#check-autoloadBookmarkStatus"),c=$("#check-autoload");a.change(function(){a.is(":checked")||c.attr("checked",false)});c.change(function(){c.is(":checked")&&a.attr("checked",true)});$("#check-shortcut-quicksave").change(function(){shortcutSwitchState("quicksave")});$("#check-shortcut-bookmark").change(function(){shortcutSwitchState("bookmark")});
$("#check-shortcut-annotate").change(function(){shortcutSwitchState("annotate")});$("#shortcut-quicksave select").change(function(){var b=$(this).val();$("#shortcut-bookmark select option").each(function(){$(this).removeAttr("disabled")});$('#shortcut-bookmark select option[value="'+b+'"]').attr("disabled",true);$("#shortcut-anotate select option").each(function(){$(this).removeAttr("disabled")});$('#shortcut-anotate select option[value="'+b+'"]').attr("disabled",true)});$("#shortcut-bookmark select").change(function(){console.log("change");
var b=$(this).val();$("#shortcut-quicksave select option").each(function(){$(this).removeAttr("disabled")});$('#shortcut-quicksave select option[value="'+b+'"]').attr("disabled",true);$("#shortcut-anotate select option").each(function(){$(this).removeAttr("disabled")});$('#shortcut-anotate select option[value="'+b+'"]').attr("disabled",true)});$("#shortcut-annotate select").change(function(){console.log("change");var b=$(this).val();$("#shortcut-quicksave select option").each(function(){$(this).removeAttr("disabled")});
$('#shortcut-quicksave select option[value="'+b+'"]').attr("disabled",true);$("#shortcut-bookmark select option").each(function(){$(this).removeAttr("disabled")});$('#shortcut-bookmark select option[value="'+b+'"]').attr("disabled",true)})})()});function buildSelect(){for(var a=["Q","D"],c=$("<select></select>"),b=48;b<91;b++)if(!(b>57&&b<65)){var d=String.fromCharCode(b);$("<option></option>").attr({value:d}).text(d).appendTo(c)}c.appendTo($(".shortcut")).each(function(e){this.value=a[e]})}
function save(){$("#check-searcho").is(":checked")||_gaq.push(["_trackEvent","Disable SearchO","Diigo"]);UI2prefs()}function shortcutSwitchState(a){$("#check-shortcut-"+a).is(":checked")?$("#check-shortcut-"+a+"-ctrl,#check-shortcut-"+a+"-alt,#shortcut-"+a+" select").removeAttr("disabled"):$("#check-shortcut-"+a+"-ctrl,#check-shortcut-"+a+"-alt,#shortcut-"+a+" select").attr("disabled","true")}
function prefs2UI(){$("#check-bmPrivateAsDefault").attr({checked:Prefs.get("prefs.bookmark.privateByDefault")=="true"});$("#check-autoloadBookmarkStatus").attr({checked:Prefs.get("prefs.autoloadBookmarkStatus")=="true"});$("#check-autoload").attr({checked:Prefs.get("prefs.autoload")=="true"});$("#check-contextMenu").attr({checked:Prefs.get("prefs.contextMenu")=="true"});$("#check-comboSearch").attr({checked:Prefs.get("prefs.comboSearch")=="true"});$("#check-searcho").attr({checked:Prefs.get("prefs.SearchO")==
"true"});$("#check-autoshowicon").attr({checked:Prefs.get("prefs.autoShowHighlightIcon")=="true"});$("#check-autoImageClipper").attr({checked:Prefs.get("prefs.autoImageClipper")=="true"});$("#check-autoCloseReadLater").attr({checked:Prefs.get("prefs.autoCloseReadLater")=="true"});$("#check-shortcut-quicksave").attr({checked:Prefs.get("prefs.shortcutQuicksave")=="true"});$("#check-shortcut-bookmark").attr({checked:Prefs.get("prefs.shortcutBookmark")=="true"});$("#check-shortcut-annotate").attr({checked:Prefs.get("prefs.shortcutAnnotate")==
"true"});$("#check-shortcut-quicksave-ctrl").attr({checked:Prefs.get("prefs.shortcutQuicksaveCtrl")=="true"});$("#check-shortcut-quicksave-alt").attr({checked:Prefs.get("prefs.shortcutQuicksaveAlt")=="true"});$("#shortcut-quicksave select").val(Prefs.get("prefs.shortcutQuicksaveKey"));$("#check-shortcut-bookmark-ctrl").attr({checked:Prefs.get("prefs.shortcutBookmarkCtrl")=="true"});$("#check-shortcut-bookmark-alt").attr({checked:Prefs.get("prefs.shortcutBookmarkAlt")=="true"});$("#shortcut-bookmark select").val(Prefs.get("prefs.shortcutBookmarkKey"));
$("#check-shortcut-annotate-ctrl").attr({checked:Prefs.get("prefs.shortcutAnnotateCtrl")=="true"});$("#check-shortcut-annotate-alt").attr({checked:Prefs.get("prefs.shortcutAnnotateAlt")=="true"});$("#shortcut-annotate select").val(Prefs.get("prefs.shortcutAnnotateKey"));shortcutSwitchState("bookmark");shortcutSwitchState("quicksave");shortcutSwitchState("annotate")}
function UI2prefs(){Prefs.set({"prefs.bookmark.privateByDefault":$("#check-bmPrivateAsDefault").is(":checked")});Prefs.set({"prefs.autoloadBookmarkStatus":$("#check-autoloadBookmarkStatus").is(":checked")});Prefs.set({"prefs.autoload":$("#check-autoload").is(":checked")});Prefs.set({"prefs.contextMenu":$("#check-contextMenu").is(":checked")});Prefs.set({"prefs.comboSearch":$("#check-comboSearch").is(":checked")});Prefs.set({"prefs.SearchO":$("#check-searcho").is(":checked")});Prefs.set({"prefs.autoShowHighlightIcon":$("#check-autoshowicon").is(":checked")});
Prefs.set({"prefs.autoImageClipper":$("#check-autoImageClipper").is(":checked")});Prefs.set({"prefs.shortcutQuicksave":$("#check-shortcut-quicksave").is(":checked")});Prefs.set({"prefs.shortcutBookmark":$("#check-shortcut-bookmark").is(":checked")});Prefs.set({"prefs.shortcutAnnotate":$("#check-shortcut-annotate").is(":checked")});Prefs.set({"prefs.shortcutQuicksaveCtrl":$("#check-shortcut-quicksave-ctrl").is(":checked")});Prefs.set({"prefs.shortcutQuicksaveAlt":$("#check-shortcut-quicksave-alt").is(":checked")});
Prefs.set({"prefs.shortcutBookmarkCtrl":$("#check-shortcut-bookmark-ctrl").is(":checked")});Prefs.set({"prefs.shortcutBookmarkAlt":$("#check-shortcut-bookmark-alt").is(":checked")});Prefs.set({"prefs.shortcutAnnotateCtrl":$("#check-shortcut-annotate-ctrl").is(":checked")});Prefs.set({"prefs.shortcutAnnotateAlt":$("#check-shortcut-annotate-alt").is(":checked")});Prefs.set({"prefs.shortcutQuicksaveKey":$("#shortcut-quicksave select").val()});Prefs.set({"prefs.shortcutBookmarkKey":$("#shortcut-bookmark select").val()});
Prefs.set({"prefs.shortcutAnnotateKey":$("#shortcut-annotate select").val()});Prefs.set({"prefs.autoCloseReadLater":$("#check-autoCloseReadLater").is(":checked")})}var _gaq=_gaq||[];_gaq.push(["_setAccount","UA-295754-35"]);_gaq.push(["_trackPageview"]);(function(){var a=document.createElement("script");a.type="text/javascript";a.async=true;a.src="https://ssl.google-analytics.com/ga.js";var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c)})();
