chrome.tabs.getSelected(null,function(h){chrome.tabs.sendRequest(h.id,{name:"checkVersion"})});
$(document).ready(function(){function h(){var b={};b.title=$("#show-title").text();b.url=$("#show-url").text();b.description=$("#show-des").text()=="Add a description"?"":$("#show-des").text();var a=$("#myTags").tagit("getAllTag");console.log(a);b.tags=a;b.mode=$("#permission").hasClass("selected")?2:0;b.unread=$("#readlater").hasClass("selected")?true:false;var c=$("#diigo-list-items").children(".diigo-x-item").children(".select-checkbox"),d=[],e=[];for(a=0;a<c.length;a++)if($(c[a]).attr("checked")==
"checked"){var f=$(c[a]).attr("id"),g=$(c[a]).attr("title");d.push({id:f,title:g})}for(a=0;a<c.length;a++)if($(c[a]).attr("checked")=="checked"){d=$(c[a]).attr("id");e.push(d)}b.shareLists=e;c=$("#diigo-group-items").children(".diigo-x-item").children(".select-checkbox");d=[];e=[];for(a=0;a<c.length;a++)if($(c[a]).attr("checked")=="checked"){f=$(c[a]).attr("id");g=$(c[a]).attr("title");var i=$(c[a]).attr("name");d.push({displayName:g,name:i,id:f})}for(a=0;a<c.length;a++)if($(c[a]).attr("checked")==
"checked"){d=$(c[a]).attr("id");e.push(d)}b.shareGroups=e;b.shareAnnotations=$("#share-annotations").attr("checked")=="checked"?true:false;chrome.tabs.getSelected(null,function(j){console.log(j.id);chrome.tabs.sendRequest(j.id,{name:"savebookmark",tabId:j.id,data:b});if($("#annotate-after-saving").attr("checked")=="checked"){chrome.extension.sendRequest({name:"annotateAfterSaving",data:true});chrome.extension.sendRequest({name:"showToolbar"})}else chrome.extension.sendRequest({name:"annotateAfterSaving",
data:false});window.close()})}function o(b){var a=b.mytag,c=b.bm;c.saved==true&&$("#bm-main #top span").text("Edit this link");$("#myTags").tagit({singleField:true,availableTags:a,removeConfirmation:true,allowSpaces:true,placeholderText:"Press enter to add tags"});$(".ui-widget-content.ui-autocomplete-input").focus(function(){$(".ui-widget-content.ui-autocomplete-input").attr("placeholder","");$(".ui-widget-content.ui-autocomplete-input").css("width","50px")});$(".ui-widget-content.ui-autocomplete-input").blur(function(){$(".ui-widget-content.ui-autocomplete-input").attr("placeholder",
"Press enter to add tags");$(".ui-widget-content.ui-autocomplete-input").css("width","")});$("#show-title").text(c.title);$("#show-url").text(c.url);c.mode==2&&$("#permission").removeClass("unselected").addClass("selected");c.unread==true&&$("#readlater").removeClass("unselected").addClass("selected");if(c.description.length>0)$("#show-des").text(c.description).addClass("normal");else b.selection&&$("#show-des").text('"'+b.selection+'"').addClass("normal");for(a=0;a<c.tags.length;a++)$("#myTags").tagit("createTag",
c.tags[a]);for(a=0;a<b.lists.length;a++){var d=document.createElement("div");d.className="diigo-x-item";d.innerHTML='<input class="select-checkbox" title="'+b.lists[a].title+'" name="'+b.lists[a].id+'" id="'+b.lists[a].id+'" type="checkbox" ><label for="'+b.lists[a].id+'">'+b.lists[a].title+"</label>";$("#diigo-list-items").append(d)}for(a=0;a<b.groups.length;a++){d=document.createElement("div");d.className="diigo-x-item";d.innerHTML='<input class="select-checkbox" title="'+b.groups[a].displayName+
'" name="'+b.groups[a].name+'" id="'+b.groups[a].name+'" type="checkbox" ><label for="'+b.groups[a].name+'">'+b.groups[a].displayName+"</label>";$("#diigo-group-items").append(d)}$("#diigo-group-items .diigo-x-item .select-checkbox").click(function(f){if(f.target.checked==true)if(l==false){console.log("group-tag");$("#group-tag").show();l=true;var g=f.target.id;chrome.tabs.getSelected(null,function(i){chrome.tabs.sendRequest(i.id,{name:"getGroupTags",groupName:g})})}});var e=c.lists;for(a=0;a<e.length;a++){d=
e[a].id;$("#"+d).prop("checked",true)}c=c.groups;for(a=0;a<c.length;a++){d=c[a].name;$("#"+d).prop("checked",true)}c=b.lastUsedTags;console.log(c.length);if(c.length==0)$("#last-used-tag").hide();else{for(a=0;a<c.length;a++){d=document.createElement("div");d.className="diigo-tag";d.title=c[a];d.innerHTML='<span class="label" >'+c[a]+'</span><img src="img/popup-image/tag7.png">';$("#last-used-tag .tag-box").append(d)}$(".diigo-tag .label").click(function(f){f=$(f.target).text();$("#myTags").tagit("createTag",
f)});b.annotateAfterSaving=="true"&&$("#annotate-after-saving").prop("checked",true)}}function m(b,a){if(a.length==0)$("#"+b+"-tag").hide();else{$("#"+b+"-tag .tag-box .loading").hide();for(var c=0;c<a.length;c++){var d=document.createElement("div");d.className="diigo-tag";d.title=a[c];d.innerHTML='<span class="label" >'+a[c]+'</span><img src="img/popup-image/tag7.png">';$("#"+b+"-tag .tag-box").append(d)}$(".diigo-tag .label").click(function(e){e=$(e.target).text();$("#myTags").tagit("createTag",
e)})}}function n(b){console.log($("#"+b+"-container").hasClass("hide"));$("#"+b+"-container").hasClass("hide")?$("#"+b+"-arrow").removeClass("expand").addClass("unexpand"):$("#"+b+"-arrow").removeClass("unexpand").addClass("expand")}function k(b){var a=$("#"+b);a.click(function(){a.hasClass("unselected")?a.removeClass("unselected").addClass("selected"):a.removeClass("selected").addClass("unselected")})}var l=false;chrome.cookies.get({url:"http://www.diigo.com",name:"diigoandlogincookie"},function(b){if(b){console.log(b);
var a=b.value.split("-.-")[1];a&&$("#sign-out-btn").text("Sign Out ("+a+")");$("#action a").click(function(c){var d;c=c.target.id;if(c!="more"){if(c)switch(c){case "home":d="http://www.diigo.com/user/"+a;break;case "unread":d="http://www.diigo.com/user/"+a+"?type=bookmark&read=no";break;case "my-network":d="http://www.diigo.com/network/"+a;break;case "my-groups":d="http://groups.diigo.com/user/"+a;break;case "option":d=chrome.extension.getURL("");d+="options.html";break;case "changelog":d="http://www.diigo.com/extension/chrome/new.html";
break;case "sign-out-btn":d="http://www.diigo.com/sign-out";break}chrome.tabs.create({url:d})}});$("#main").show();chrome.tabs.getSelected(null,function(c){chrome.tabs.sendRequest(c.id,{name:"ifbookmark"});console.log("ifbookmark")})}else $("#sign-in").show()});chrome.extension.onRequest.addListener(function(b){if(b.name=="saved"){console.log("change to saved");$("#quick-bookmark").removeClass("unsaved").addClass("saved").attr("title","remove this bookmark")}else if(b.name=="sendCtx"){console.log(b.data);
o(b.data)}else if(b.name=="sendRetags"){console.log(b.data);m("recommanded",b.data)}else if(b.name=="sendGtags"){console.log(b.data);m("group",b.data)}else if(b.name=="listCreateSuccess"){var a=b.data;console.log(b);b=document.createElement("div");b.className="diigo-x-item";b.innerHTML='<input class="select-checkbox" title="'+a.title+'" name="'+a.id+'" id="'+a.id+'" type="checkbox" ><label for="'+a.id+'">'+a.title+"</label>";$("#diigo-list-items").append(b);$("#create-list").val("")}else if(b.name==
"popupclose")window.close();else b.name=="shownew"&&window.close()});$("#lu-tag").click(function(){for(var b=$("#last-used-tag .tag-box").children(".diigo-tag"),a=0;a<b.length;a++)$("#myTags").tagit("createTag",b[a].title)});$("#r-tag").click(function(){for(var b=$("#recommanded-tag .tag-box").children(".diigo-tag"),a=0;a<b.length;a++)$("#myTags").tagit("createTag",b[a].title)});$("#bm-saveBtn").click(function(){h()});$("#bm-cancelBtn").click(function(){window.close()});$("#quick-bookmark").click(function(){if($("#quick-bookmark").hasClass("unsaved")){chrome.tabs.getSelected(null,
function(b){chrome.tabs.sendRequest(b.id,{name:"qsavebookmark"});console.log("qsave")});$("#quick-bookmark").removeClass("unsaved").addClass("saved").attr("title","remove this bookmark")}else{chrome.tabs.getSelected(null,function(b){chrome.tabs.sendRequest(b.id,{name:"qdeletebookmark"});console.log("qdelete")});$("#quick-bookmark").removeClass("saved").addClass("unsaved").attr("title","quick save")}});$("#show-title").click(function(){var b=$("#show-title").text();$("#title-input").val(b);$("#show-title").hide();
$("#title-input").show();$("#title-input").focus()});$("#show-url").click(function(){var b=$("#show-url").text();$("#url-input").val(b);$("#show-url").hide();$("#url-input").show();$("#url-input").focus()});$("#show-des").click(function(){var b=$("#show-des").text();$("#des-input").val(b);$("#show-des").fadeOut("fast",function(){$("#des-input").fadeIn();$("#des-input").focus();$("#des-input").val()=="Add a description"&&$("#des-input").val("")})});$("#title-input").blur(function(){var b=$("#title-input").val();
if(b!=""){$("#title-input").hide();$("#show-title").text(b);$("#show-title").show()}else $("#title-input").addClass("none").val("Please input a title")});$("#title-input").click(function(){$("#title-input").hasClass("none")&&$("#title-input").removeClass("none").val("")});$("#url-input").blur(function(){var b=$("#url-input").val();if(b!=""){$("#url-input").hide();$("#show-url").text(b);$("#show-url").show()}else $("#url-input").addClass("none").val("Please input a url")});$("#url-input").click(function(){$("#url-input").hasClass("none")&&
$("#url-input").removeClass("none").val("")});$("#des-input").blur(function(){var b=$("#des-input").val();if(b!=""){$("#des-input").hide();$("#show-des").text(b);$("#show-des").show().addClass("normal")}else{$("#des-input").hide();$("#show-des").text("Add a description");$("#show-des").show();$("#show-des").hasClass("normal")&&$("#show-des").removeClass("normal")}});$("#diigo-list").click(function(){if($("#group-container").hasClass("hide"))$("#list-container").toggleClass("hide");else{$("#list-container").toggleClass("hide");
$("#group-container").toggleClass("hide")}n("list")});$("#diigo-group").click(function(){if($("#list-container").hasClass("hide"))$("#group-container").toggleClass("hide");else{$("#group-container").toggleClass("hide");$("#list-container").toggleClass("hide")}n("group")});$("#create-list-addbtn").click(function(){if($("#create-list").val()){var b=$("#create-list").val();chrome.tabs.getSelected(null,function(a){chrome.tabs.sendRequest(a.id,{name:"createList",data:b})})}});$("#create-group").click(function(){window.open("http://groups.diigo.com/create")});
k("permission");k("readlater");k("cache");$("#bookmark").click(function(){$("#main").hide();$("#bm-main").show();chrome.tabs.getSelected(null,function(b){chrome.tabs.sendRequest(b.id,{name:"getCtx"});chrome.tabs.sendRequest(b.id,{name:"getRecommendedTags"})})});$("#sign-in-btn").click(function(){window.open("http://www.diigo.com/sign-in?referInfo="+encodeURIComponent("/images/diigo-logo.png#SIGNED_IN"))});$("#sign-up-btn").click(function(){var b="http://www.diigo.com/account/thirdparty/openid?openid_url=https://www.google.com/accounts/o8/id&redirect_url="+
encodeURIComponent(chrome.extension.getURL(""))+"&request_from=chrome_diigo_extension";window.open(b)});$("#annotate").hover(function(){$(this).parent().addClass("annotate-hover")},function(){$(this).parent().removeClass("annotate-hover")}).click(function(){chrome.extension.sendRequest({name:"showToolbar"});window.close()});$("#tag").hover(function(){$(this).parent().addClass("tag-hover")},function(){$(this).parent().removeClass("tag-hover")}).click(function(){chrome.tabs.getSelected(null,function(b){chrome.tabs.sendRequest(b.id,
{name:"showWindow"});window.close()})});$("li").click(function(b){switch(b.target.id){case "read-later":chrome.tabs.getSelected(null,function(a){chrome.tabs.executeScript(a.id,{file:"js/checkTab.js"},function(){debug("executeScript callback")});chrome.tabs.sendRequest(a.id,{name:"readlater"});console.log("readlater");window.close()});break;case "screenshot":chrome.tabs.getSelected(null,function(a){chrome.tabs.executeScript(a.id,{file:"js/checkTab.js"},function(){debug("executeScript callback")});
chrome.tabs.sendRequest(a.id,{name:"screenshot"});window.close();console.log("send")});break;case "share":chrome.tabs.getSelected(null,function(a){chrome.tabs.sendRequest(a.id,{name:"share"});window.close()});break}});$("#annotate #text").click(function(){chrome.extension.sendRequest({name:"showToolbar"});window.close()});$("#action #more").click(function(){$(this).toggleClass("unfold");$("#more-link").slideToggle("fast")})});
