(function(b){b.widget("ui.tagit",{options:{itemName:"item",fieldName:"tags",availableTags:[],tagSource:null,removeConfirmation:false,caseSensitive:true,placeholderText:null,allowSpaces:false,animate:true,singleField:false,singleFieldDelimiter:",",singleFieldNode:null,tabIndex:null,onTagAdded:null,onTagRemoved:null,onTagClicked:null},_create:function(){var a=this;if(this.element.is("input")){this.tagList=b("<ul></ul>").insertAfter(this.element);this.options.singleField=true;this.options.singleFieldNode=
this.element;this.element.css("display","none")}else this.tagList=this.element.find("ul, ol").andSelf().last();this._tagInput=b('<input type="text" />').addClass("ui-widget-content");this.options.tabIndex&&this._tagInput.attr("tabindex",this.options.tabIndex);this.options.placeholderText&&this._tagInput.attr("placeholder",this.options.placeholderText);this.options.tagSource=this.options.tagSource||function(c,e){var g=c.term.toLowerCase(),h=b.grep(this.options.availableTags,function(i){return i.toLowerCase().indexOf(g)===
0});e(this._subtractArray(h,this.assignedTags()))};if(b.isFunction(this.options.tagSource))this.options.tagSource=b.proxy(this.options.tagSource,this);this.tagList.addClass("tagit").addClass("ui-widget ui-widget-content ui-corner-all").append(b('<li class="tagit-new"></li>').append(this._tagInput)).click(function(c){var e=b(c.target);e.hasClass("tagit-label")?a._trigger("onTagClicked",c,e.closest(".tagit-choice")):a._tagInput.focus()});this.tagList.children("li").each(function(){if(!b(this).hasClass("tagit-new")){a.createTag(b(this).html(),
b(this).attr("class"));b(this).remove()}});if(this.options.singleField)if(this.options.singleFieldNode){var d=b(this.options.singleFieldNode),f=d.val().split(this.options.singleFieldDelimiter);d.val("");b.each(f,function(c,e){a.createTag(e)})}else this.options.singleFieldNode=this.tagList.after('<input type="hidden" style="display:none;" value="" name="'+this.options.fieldName+'" />');this._tagInput.keydown(function(c){if(c.which==b.ui.keyCode.BACKSPACE&&a._tagInput.val()===""){var e=a._lastTag();
if(!a.options.removeConfirmation||e.hasClass("remove"))a.removeTag(e);else a.options.removeConfirmation&&e.addClass("remove ui-state-highlight")}else a.options.removeConfirmation&&a._lastTag().removeClass("remove ui-state-highlight");if(c.which==b.ui.keyCode.COMMA||c.which==b.ui.keyCode.ENTER||c.which==b.ui.keyCode.TAB&&a._tagInput.val()!==""||c.which==b.ui.keyCode.SPACE&&a.options.allowSpaces!==true&&(b.trim(a._tagInput.val()).replace(/^s*/,"").charAt(0)!='"'||b.trim(a._tagInput.val()).charAt(0)==
'"'&&b.trim(a._tagInput.val()).charAt(b.trim(a._tagInput.val()).length-1)=='"'&&b.trim(a._tagInput.val()).length-1!==0)){c.preventDefault();a.createTag(a._cleanedInput());a._tagInput.autocomplete("close")}}).blur(function(){a.createTag(a._cleanedInput())});if(this.options.availableTags||this.options.tagSource)this._tagInput.autocomplete({source:this.options.tagSource,select:function(c,e){a._tagInput.val()===""&&a.removeTag(a._lastTag(),false);a.createTag(e.item.value);return false}})},_cleanedInput:function(){return b.trim(this._tagInput.val().replace(/^"(.*)"$/,
"$1"))},_lastTag:function(){return this.tagList.children(".tagit-choice:last")},assignedTags:function(){var a=this,d=[];console.log(this.options.singleField);if(this.options.singleField){d=b(this.options.singleFieldNode).val().split(this.options.singleFieldDelimiter);if(d[0]==="")d=[]}else this.tagList.children(".tagit-choice").each(function(){console.log(a.tagLabel(this),a);d.push(a.tagLabel(this))});return d},getAllTag:function(){var a=this,d=[];this.tagList.children(".tagit-choice").each(function(){console.log(a.tagLabel(this),
a);d.push(a.tagLabel(this))});return d},_updateSingleTagsField:function(a){b(this.options.singleFieldNode).val(a.join(this.options.singleFieldDelimiter))},_subtractArray:function(a,d){for(var f=[],c=0;c<a.length;c++)b.inArray(a[c],d)==-1&&f.push(a[c]);return f},tagLabel:function(a){return this.options.singleField?b(a).children(".tagit-label").text():b(a).children("input").val()},_isNew:function(a){var d=this,f=true;this.tagList.children(".tagit-choice").each(function(){if(d._formatStr(a)==d._formatStr(d.tagLabel(this))){b(this).addClass("remove").delay(500).queue(function(c){b(this).removeClass("remove");
c()});return f=false}});return f},_formatStr:function(a){if(this.options.caseSensitive)return a;return b.trim(a.toLowerCase())},createTag:function(a,d){var f=this;a=b.trim(a);if(!this._isNew(a)||a==="")return false;var c=b(this.options.onTagClicked?'<a class="tagit-label"></a>':'<span class="tagit-label" contenteditable="true"></span>').text(a).focus(function(){b(this).addClass("diigo-tag-editing")}).blur(function(){b(this).removeClass("diigo-tag-editing")}).bind("keydown",function(h){h.keyCode==
13&&b(this).blur()}),e='<img class="" src="'+chrome.extension.getURL("")+'img/popup-image/tag7.png">',g=b("<li></li>").addClass("tagit-choice ui-widget-content ui-state-default ui-corner-all").addClass(d).append(c).append(e);e=b("<span></span>").addClass("ui-icon ui-icon-close");e=b('<a><span class="text-icon">\u00d7</span></a>').addClass("tagit-close").append(e).click(function(){f.removeTag(g)});g.append(e);if(this.options.singleField){c=this.assignedTags();c.push(a);this._updateSingleTagsField(c)}else{c=
c.html();g.append('<input type="hidden" style="display:none;" value="'+c+'" name="'+this.options.itemName+"["+this.options.fieldName+'][]" />')}this._trigger("onTagAdded",null,g);this._tagInput.val("");this._tagInput.parent().before(g)},removeTag:function(a,d){d=d||this.options.animate;a=b(a);this._trigger("onTagRemoved",null,a);if(this.options.singleField){var f=this.assignedTags(),c=this.tagLabel(a);f=b.grep(f,function(e){return e!=c});this._updateSingleTagsField(f)}d?a.fadeOut("fast").hide("blind",
{direction:"horizontal"},"fast",function(){a.remove()}).dequeue():a.remove()},removeAll:function(){var a=this;this.tagList.children(".tagit-choice").each(function(d,f){a.removeTag(f,false)})}})})(jQuery);
