(function(d){d.widget("ui.tagit",{options:{tagSource:[],triggerKeys:["enter","space","comma","tab"],initialTags:[],minLength:1,select:false,allowNewTags:true,caseSensitive:false,sortable:false,highlightOnExistColor:"#0F0",emptySearch:true,tagsChanged:function(){},maxTags:undefined,blurOnPaste:true},_splitAt:/\ |,/g,_existingAtIndex:0,_keys:{backspace:[8],enter:[13],space:[32],comma:[44,188],tab:[9]},_sortable:{sorting:-1},_create:function(){var a=this;this.tagsArray=[];this.timer=null;this.element.addClass("tagit");
this.element.children("li").each(function(){var b=d(this),e=b.attr("tagValue")||b.data("value");a.options.initialTags.push({label:b.text(),value:e?e:b.text()})});a._splitAt=null;if(d.inArray("space",a.options.triggerKeys)>0&&d.inArray("comma",a.options.triggerKeys)>0)a._splitAt=/\ |,/g;else if(d.inArray("space",a.options.triggerKeys)>0)a._splitAt=/\ /g;else if(d.inArray("comma",a.options.triggerKeys)>0)a._splitAt=/,/g;this.element.html('<li class="tagit-new"><input class="tagit-input" type="text" /></li>');
this.input=this.element.find(".tagit-input");d(this.element).click(function(b){if(d(b.target).hasClass("tagit-close")){b=d(b.target).parent();b=a.tagsArray[b.index()];b.element.remove();a._popTag(b)}else{a.input.focus();a.options.emptySearch&&d(b.target).hasClass("tagit-input")&&a.input.val()==""&&a.input.autocomplete!=undefined&&a.input.autocomplete("search")}});var c=this.options.select;this.options.appendTo=this.element;this.options.source=this.options.tagSource;this.options.select=function(b,
e){a.input.data("autoCompleteTag",true);clearTimeout(a.timer);if(a.options.maxTags!==undefined&&a.tagsArray.length==a.options.maxTags)a.input.val("");else e.item.label===undefined?a._addTag(e.item.value):a._addTag(e.item.label,e.item.value);return false};this.options.focus=function(b,e){if(e.item.label!==undefined&&/^key/.test(b.originalEvent.originalEvent.type)){a.input.val(e.item.label);a.input.data("value",e.item.value);return false}};this.options.autoFocus=!this.options.allowNewTags;this.input.autocomplete(this.options);
this.options.select=c;this.input.keydown(function(b){var e=a.element.children(".tagit-choice:last");if(b.which==a._keys.backspace)return a._backspace(e);if(a._isInitKey(b.which)&&!(a._isTabKey(b.which)&&this.value==""&&!a.input.data("autoCompleteTag"))){b.preventDefault();a.input.data("autoCompleteTag",false);if(!a.options.allowNewTags||a.options.maxTags!==undefined&&a.tagsArray.length==a.options.maxTags)a.input.val("");else a.options.allowNewTags&&d(this).val().length>=a.options.minLength&&a._addTag(d(this).val())}a.options.maxLength!==
undefined&&a.input.val().length==a.options.maxLength&&b.preventDefault();e.hasClass("selected")&&e.removeClass("selected");a.lastKey=b.which});this.input.bind("paste",function(){if(a.options.blurOnPaste){var b=d(this);a.timer=setTimeout(function(){b.blur()},0)}});this.input.blur(function(){a.currentLabel=d(this).val();a.currentValue=d(this).data("value");if(a.options.allowNewTags)a.timer=setTimeout(function(){a._addTag(a.currentLabel,a.currentValue);a.currentValue="";a.currentLabel=""},400);d(this).val("").removeData("value");
return false});if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};if(this.options.select){this.select=d('<select class="tagit-hiddenSelect" name="'+(this.element.attr("name")||this.element.data("name"))+'" multiple="multiple"></select>');this.element.after(this.select)}this._initialTags();if(a.options.sortable!==false){c={items:".tagit-choice",containment:"parent",opacity:0.6,tolerance:"pointer",start:function(b,e){a._sortable.tag=d(e.item);a._sortable.origIndex=
a._sortable.tag.index()},update:function(){a._sortable.newIndex=a._sortable.tag.index();a._moveTag(a._sortable.origIndex,a._sortable.newIndex);if(a.options.tagsChanged){var b=a.tagsArray[a._sortable.newIndex];a.options.tagsChanged(b.value,"moved",b.element)}}};if(a.options.sortable=="handle"){c.handle="a.ui-icon";c.cursor="move"}a.element.sortable(c)}},_popSelect:function(a){d("option:eq("+a.index+")",this.select).remove();this.select.change()},_addSelect:function(a){this.select.append('<option selected="selected" value="'+
a.value+'">'+a.label+"</option>");this.select.change()},_popTag:function(a){if(a===undefined)a=this.tagsArray.pop();else this.tagsArray.splice(a.index,1);for(var c in this.tagsArray)this.tagsArray[c].index=c;this.options.select&&this._popSelect(a);if(this.options.tagsChanged)this.options.tagsChanged(a.value||a.label,"popped",a)},_addTag:function(a,c){this.input.autocomplete("close").val("");if(this._splitAt&&a.search(this._splitAt)>0)for(var b=a.split(this._splitAt),e=0;e<b.length;e++)this._addTag(b[e],
c);else{a=a.replace(/,+$/,"").trim();if(a=="")return false;b=this._exists(a,c);if(b!==false){this._highlightExisting(b);return false}b=this.tag(a,c);b.element=d('<li class="tagit-choice"'+(c!==undefined?' tagValue="'+c+'"':"")+">"+(this.options.sortable=="handle"?'<a class="ui-icon ui-icon-grip-dotted-vertical" style="float:left"></a>':"")+a+'<a class="tagit-close">x</a></li>');b.element.insertBefore(this.input.parent());this.tagsArray.push(b);this.input.val("");this.options.select&&this._addSelect(b);
this.options.tagsChanged&&this.options.tagsChanged(b.label,"added",b.element);return true}},_exists:function(a,c){if(this.tagsArray.length==0)return false;a=this._lowerIfCaseInsensitive(a);c=this._lowerIfCaseInsensitive(c);for(var b in this.tagsArray)if(this._lowerIfCaseInsensitive(this.tagsArray[b].label)==a)if(c!==undefined){if(this._lowerIfCaseInsensitive(this.tagsArray[b].value)==c)return b}else return b;return false},_highlightExisting:function(a){if(this.options.highlightOnExistColor!==undefined){a=
this.tagsArray[a];a.element.stop();var c=a.element.css("color");a.element.animate({color:this.options.highlightOnExistColor},100).animate({color:c},800)}},_isInitKey:function(a){var c="";for(var b in this._keys)if(d.inArray(a,this._keys[b])!=-1)c=b;if(d.inArray(c,this.options.triggerKeys)!=-1)return true;return false},_isTabKey:function(a){return d.inArray(a,this._keys.tab)>-1},_removeTag:function(){this._popTag();this.element.children(".tagit-choice:last").remove()},_backspace:function(a){if(this.input.val()==
"")if(this.lastKey==this._keys.backspace){this._popTag();a.remove();this.lastKey=null}else{a.addClass("selected");this.lastKey=this._keys.backspace}return true},_initialTags:function(){var a=this,c;if(this.options.tagsChanged)c=this.options.tagsChanged;this.options.tagsChanged=null;this.options.initialTags.length!=0&&d(this.options.initialTags).each(function(b,e){typeof e=="object"?a._addTag(e.label,e.value):a._addTag(e)});this.options.tagsChanged=c},_lowerIfCaseInsensitive:function(a){if(a===undefined||
typeof a!="string")return a;if(this.options.caseSensitive)return a;return a.toLowerCase()},_moveTag:function(a,c){this.tagsArray.splice(c,0,this.tagsArray.splice(a,1)[0]);for(var b in this.tagsArray)this.tagsArray[b].index=b;this.options.select&&d("option:eq("+a+")",this.select).insertBefore(d("option:eq("+c+")",this.select))},tags:function(){return this.tagsArray},destroy:function(){d.Widget.prototype.destroy.apply(this,arguments);this.tagsArray=[]},reset:function(){this.element.find(".tagit-choice").remove();
this.tagsArray=[];if(this.options.select){this.select.children().remove();this.select.change()}this._initialTags();this.options.tagsChanged&&this.options.tagsChanged(null,"reset",null)},fill:function(a){if(a!==undefined)this.options.initialTags=a;this.reset()},add:function(a,c){return typeof a=="object"?this._addTag(a.label,a.value):this._addTag(a,c)},autocomplete:function(){return this.input.data("autocomplete")},tag:function(a,c,b){return{label:a,value:c===undefined?a:c,element:b,index:this.tagsArray.length}},
remove:function(a,c){if(this.tagsArray.length==0)return false;a=this._lowerIfCaseInsensitive(a);c=this._lowerIfCaseInsensitive(c);for(var b=0;b<this.tagsArray.length;b++)if(this._lowerIfCaseInsensitive(this.tagsArray[b].value)==c||this._lowerIfCaseInsensitive(this.tagsArray[b].label)==a)break;if(b>=0&&b<this.tagsArray.length){b=this.tagsArray[b];b.element.remove();this._popTag(b);return true}return false}})})(jQuery);
