var disabledSites={},disabledSitesReason={},bg=window;DNTP.bundle=null;DNTP._=bridge._;DNTP.settings.trackerMap={};DNTP.trackerNames={};DNTP.browser_name=bridge.browser_name;DNTP.origin=ORIGIN;DNTP.version=bridge.app.getDetails().version;DNTP.pauseContentPolicy=!1;
var domainMap={script:{"*":[]},image:{"*":[]},iframe:{"*":[]},object:{"*":[]},subobject:{"*":[]}},optoutMap={},totalBlocked=0,totalOptout=0,savedTotalBlocked=0,savedTotalOptout=0,useGlobalAllow=!0,writeCookies=!0,installDate=new Date,original_version=VERSION,showPostInstallBubble=!1,showPostInstallBubbleX=!1,trackerLastUpdated=null;DNTP.noteCounts={};var webdb={};webdb.open=function(){webdb.db=openDatabase("abine2","1.1","abine2",5242880)};webdb.onError=function(){};webdb.onSuccess=function(){};
var freshInstall=!1;
webdb.createTable=function(a){webdb.db.transaction(function(c){c.executeSql("CREATE TABLE IF NOT EXISTS trackers(ID INTEGER PRIMARY KEY ASC, name VARCHAR, blocked INTEGER, domain VARCHAR, UNIQUE (name,domain) ON CONFLICT REPLACE)",[],function(){c.executeSql("CREATE TABLE IF NOT EXISTS blockcount(name VARCHAR, value INTEGER, UNIQUE (name) ON CONFLICT REPLACE)",[],function(){c.executeSql("CREATE TABLE IF NOT EXISTS notifications(msg VARCHAR, seen INTEGER, UNIQUE (msg) ON CONFLICT REPLACE)",[],function(){c.executeSql("CREATE TABLE IF NOT EXISTS settings(name VARCHAR, value VARCHAR, UNIQUE (name) ON CONFLICT REPLACE)",
[],function(b,c){if(c.rowsAffected>0||c.insertId>0)freshInstall=!0;try{a()}catch(e){}freshInstall&&(bridge.settings.clearAll&&bridge.settings.clearAll(),DNTP.setupTag(function(){if(bridge.settings.getItem("postInstallShown","no")=="no"){bridge.settings.setItem("postInstallShown","yes");showPostInstallBubble=!0;var b;b="http://donottrackplus.com/postinstall.php?b="+(bridge.isChrome?"chrome":"safari")+"&o=DNTP_"+DNTP.origin+"&v="+bridge.app.getDetails().version+"&t="+DNTP.origin;SILENT?webdb.setSetting("showPostInstall",
b):bridge.showPostInstallPage(b)}}))})})})})})};webdb.initNoteCounts=function(){webdb.db.transaction(function(a){a.executeSql("SELECT * from notifications",[],function(a,b){DNTP.NotificationManager.init(webdb.saveNoteCounts);for(var d=0;d<b.rows.length;d++)DNTP.NotificationManager.noteCounts[b.rows.item(d).msg]=b.rows.item(d).seen})})};
webdb.saveNoteCounts=function(a){webdb.db.transaction(function(c){for(var b=0;b<4;b++){var d=a[b];if(d)c.executeSql("INSERT INTO notifications (msg, seen) VALUES (?,?)",[d.msg,d.impressions],webdb.onSuccess,webdb.onError),DNTP.NotificationManager.noteCounts[d.msg]=d.impressions}})};
webdb.setValue=function(a,c,b){if(!b||b=="")b="*";DNTP.settings.trackerMap[b]||(DNTP.settings.trackerMap[b]={});DNTP.settings.trackerMap[b][a]=c;webdb.db.transaction(function(d){d.executeSql("INSERT INTO trackers (blocked,name,domain) VALUES (?,?,?)",[c,a,b],webdb.onSuccess,webdb.onError)})};webdb.toggleGlobal=function(a){webdb.db.transaction(function(c){c.executeSql("DELETE FROM trackers WHERE name = '"+a+"' AND domain != '*'",[],webdb.onSuccess,webdb.onError)})};
webdb.updateTrackerMap=function(){webdb.db.transaction(function(a){a.executeSql("SELECT * FROM trackers",[],function(a,b){for(var d=0;d<b.rows.length;d++)DNTP.settings.trackerMap[b.rows.item(d).domain]||(DNTP.settings.trackerMap[b.rows.item(d).domain]={}),DNTP.settings.trackerMap[b.rows.item(d).domain][b.rows.item(d).name]=b.rows.item(d).blocked;webdb.convertTrackerDomains();addNewTrackers()})})};
webdb.initTotalBlocked=function(){webdb.db.transaction(function(a){a.executeSql('SELECT * from blockcount where name = "totalb"',[],function(a,b){for(var d=0;d<b.rows.length;d++)savedTotalBlocked=totalBlocked=b.rows.item(d).value});a.executeSql('SELECT * from blockcount where name = "totalOptout"',[],function(a,b){for(var d=0;d<b.rows.length;d++)savedTotalOptout=totalOptout=b.rows.item(d).value,DNTP.OPTOUT_DISABLED&&(savedTotalOptout=totalOptout=0)});a.executeSql('SELECT * from blockcount where name = "facebook"',
[],function(a,b){for(var d=0;d<b.rows.length;d++)DNTP.socialBlocked["Facebook Connect"]=b.rows.item(d).value});a.executeSql('SELECT * from blockcount where name = "twitter"',[],function(a,b){for(var d=0;d<b.rows.length;d++)DNTP.socialBlocked["Twitter Badge"]=b.rows.item(d).value});a.executeSql('SELECT * from blockcount where name = "google"',[],function(a,b){for(var d=0;d<b.rows.length;d++)DNTP.socialBlocked["Google +1"]=b.rows.item(d).value})})};
webdb.checkForRulesUpdate=function(){webdb.db.transaction(function(a){a.executeSql('SELECT * FROM settings WHERE name = "rules.update.last"',[],function(a,b){var d=!1;if(b.rows.length==1){var e=(new Date).getTime(),f=b.rows.item(0).value;trackerLastUpdated=f;e-f>864E5?d=!0:window.setTimeout(function(){webdb.checkForRulesUpdate()},18E5)}else d=!0;d&&(DNTP.sendRequest(DNTP.RulesUpdateUrl,function(b){if(b&&b.indexOf('"Companies":')!=-1)try{var a=JSON.parse(b);if(a.Version&&a.Version>Tracker.Version||
a.Notifications&&Tracker.Notifications&&a.Notifications.version>Tracker.Notifications.version)webdb.setSetting("converted.disabledsites",""),webdb.setSetting("converted.trackerdomains",""),webdb.updateRules(b);webdb.markDidUpdate()}catch(c){console.log(c)}}),window.setTimeout(function(){webdb.checkForRulesUpdate()},18E5))})})};
webdb.updateRules=function(a){webdb.db.transaction(function(c){c.executeSql("INSERT INTO settings (name,value) VALUES ('rules',?)",[a],function(){webdb.initRulesFromDatabase()},webdb.onError);c.executeSql("INSERT INTO settings (name,value) VALUES ('rules.update.last',?)",[(new Date).getTime()],webdb.onSuccess,webdb.onError)})};
webdb.markDidUpdate=function(){webdb.db.transaction(function(a){a.executeSql("INSERT INTO settings (name,value) VALUES ('rules.update.last',?)",[(new Date).getTime()],webdb.onSuccess,webdb.onError)})};
webdb.initRulesFromDatabase=function(){webdb.db.transaction(function(a){a.executeSql('SELECT * FROM settings WHERE name = "rules"',[],function(a,b){if(b.rows.length==1){var d=b.rows.item(0).value;if(d.length!=0)try{var e=JSON.parse(d);if(e.Version&&e.Version>Tracker.Version){Tracker=e;for(var d={script:1,iframe:1,image:1},f=Tracker.Companies,g=0;g<f.length;g++)for(var h=f[g],j=0;j<h.rules.length;j++)for(type in d){var i=h.rules[j];if(type in i&&(i[type].pattern=RegExp(i[type].pattern,"i"),i[type].allowDomain))i[type].allowDomain=
RegExp(i[type].allowDomain,"i")}if(e.HostingSites)Tracker.HostingSites=RegExp(e.HostingSites,"i");if(e.CompoundRealms)Tracker.CompoundRealms=RegExp(e.CompoundRealms,"i");if(e.CombinerScripts)Tracker.CombinerScripts=RegExp(e.CombinerScripts,"i")}if(e.Notifications&&Tracker.Notifications&&e.Notifications.version>Tracker.Notifications.version)Tracker.Notifications=e.Notifications}catch(k){alert(k)}}setupRules(Tracker.Companies);if(Tracker.CombinerScripts)combinerScripts=Tracker.CombinerScripts;setupTopLevelDomains(Tracker.CompoundRealms,
Tracker.HostingSites);DNTP.setupNotifications(Tracker.Notifications);webdb.convertDisabledSites();webdb.convertTrackerDomains();DNTP.settings.trackerMap["*"]&&addNewTrackers()})})};
webdb.initDisabledSites=function(){webdb.db.transaction(function(a){a.executeSql('SELECT * FROM settings WHERE name = "disabled.sites"',[],function(a,b){if(b.rows.length==1){var d=b.rows.item(0).value;if(d.length!=0)try{disabledSites=JSON.parse(d)}catch(e){alert(e)}webdb.convertDisabledSites()}});a.executeSql('SELECT * FROM settings WHERE name = "disabled.sites.reason"',[],function(a,b){if(b.rows.length==1){var d=b.rows.item(0).value;if(d.length!=0)try{disabledSitesReason=JSON.parse(d)}catch(e){}}})})};
webdb.updateDisabledSites=function(){webdb.db.transaction(function(a){a.executeSql("INSERT INTO settings (name,value) VALUES ('disabled.sites',?)",[JSON.stringify(disabledSites)],webdb.onSuccess,webdb.onError);a.executeSql("INSERT INTO settings (name,value) VALUES ('disabled.sites.reason',?)",[JSON.stringify(disabledSitesReason)],webdb.onSuccess,webdb.onError)})};
webdb.updateInstallDate=function(){webdb.db.transaction(function(a){a.executeSql('SELECT value FROM settings WHERE name = "install.date"',[],function(a,b){b.rows.length==1?installDate=new Date(parseInt(b.rows.item(0).value)):(installDate=new Date,a.executeSql("INSERT INTO settings (name,value) VALUES ('install.date',?)",[installDate.getTime()],webdb.onSuccess,webdb.onError))})})};
webdb.updateTag=function(){var a=DNTP.Config.get("origin",null);a?DNTP.origin=ORIGIN=a:webdb.db.transaction(function(a){a.executeSql('SELECT value FROM settings WHERE name = "TAG"',[],function(a,c){c.rows.length==1?(DNTP.origin=ORIGIN=c.rows.item(0).value,DNTP.Config.set("origin",ORIGIN)):a.executeSql("INSERT INTO settings (name,value) VALUES ('TAG',?)",[ORIGIN],webdb.onSuccess,webdb.onError)})})};
webdb.updateOriginalVersion=function(){webdb.db.transaction(function(a){a.executeSql('SELECT value FROM settings WHERE name = "original.version"',[],function(a,b){b.rows.length==1?original_version=b.rows.item(0).value:(original_version=bridge.app.getDetails().version,a.executeSql("INSERT INTO settings (name,value) VALUES ('original.version',?)",[original_version],webdb.onSuccess,webdb.onError))})})};
webdb.setSetting=function(a,c){webdb.db.transaction(function(b){c||(c="");b.executeSql("INSERT INTO settings (name,value) VALUES (?,?)",[a,c],webdb.onSuccess,webdb.onError)})};webdb.getSetting=function(a,c,b){webdb.db.transaction(function(d){d.executeSql("SELECT value FROM settings WHERE name = ?",[a],function(a,d){d.rows.length==1?b(d.rows.item(0).value):b(c)})})};
webdb.updateTotalBlocked=function(){webdb.db.transaction(function(a){var c=totalBlocked-savedTotalBlocked;writeCookies&&(c+=totalOptout-savedTotalOptout);c>0&&(DNTP.updateDailyTotals(totalBlocked+totalOptout-c,c),savedTotalBlocked=totalBlocked,savedTotalOptout=totalOptout,a.executeSql("INSERT INTO blockcount (name,value) VALUES ('totalb',?)",[totalBlocked],webdb.onSuccess,webdb.onError),a.executeSql("INSERT INTO blockcount (name,value) VALUES ('totalOptout',?)",[totalOptout],webdb.onSuccess,webdb.onError),
a.executeSql("INSERT INTO blockcount (name,value) VALUES ('facebook',?)",[DNTP.socialBlocked["Facebook Connect"]],webdb.onSuccess,webdb.onError),a.executeSql("INSERT INTO blockcount (name,value) VALUES ('twitter',?)",[DNTP.socialBlocked["Twitter Badge"]],webdb.onSuccess,webdb.onError),a.executeSql("INSERT INTO blockcount (name,value) VALUES ('google',?)",[DNTP.socialBlocked["Google +1"]],webdb.onSuccess,webdb.onError))})};
webdb.convertDisabledSites=function(){webdb.getSetting("converted.disabledsites","",function(a){if(a!="1"){webdb.setSetting("converted.disabledsites","1");var a=!1,c;for(c in disabledSites){var b=getUserTopLevelDomain(c);b!=c&&(disabledSites[b]=disabledSites[c],delete disabledSites[c],a=!0)}a&&webdb.updateDisabledSites()}})};
webdb.convertTrackerDomains=function(){webdb.getSetting("converted.trackerdomains","",function(a){if(a!="1"){webdb.setSetting("converted.trackerdomains","1");a=DNTP.settings.trackerMap;DNTP.settings.trackerMap={"*":a["*"]};for(var c in a)if(c!="*"){var b=getUserTopLevelDomain(c);if(b==c)DNTP.settings.trackerMap[c]=a[c];else{(function(a){webdb.db.transaction(function(b){b.executeSql("delete from trackers where domain = ?",[a],webdb.onSuccess,webdb.onError)})})(c);for(var d in a[c])webdb.setValue(d,
a[c][d],b)}}}})};
var toggleTrackerFromBackground=function(a,c,b,d){if(d&&bridge.isChrome){var e=getTabData(d);a?c in e.abineBlocked||(e.abineBlocked[c]=1,e.abineBlocked.length++):c in e.abineBlocked&&(delete e.abineBlocked[c],e.abineBlocked.length--);updateToolbarIcon(d)}DNTP.settings.trackerMap[b]||(DNTP.settings.trackerMap[b]={});if(b=="*"){for(site in DNTP.settings.trackerMap)DNTP.settings.trackerMap[site]&&delete DNTP.settings.trackerMap[site][c];webdb.toggleGlobal(c)}a?(DNTP.settings.trackerMap[b][c]=1,webdb.setValue(c,
1,b)):(DNTP.settings.trackerMap[b][c]=0,webdb.setValue(c,0,b));bridge.tabs.sendRequest(d,{message:"toggleTracker",name:c,host:b,blocked:a},function(){})},setupTopLevelDomains=function(a,c){a&&(compoundRealms=a.source?a:RegExp(a,"i"));c&&(hostingSites=c.source?c:RegExp(c,"i"))};function startContentPolicy(){DNTP.pauseContentPolicy=!1;DNTP.update_toolbar_icon()}function stopContentPolicy(){DNTP.pauseContentPolicy=!0;DNTP.update_toolbar_icon()}
var setupRules=function(a){DNTP.trackerNames={};domainMap={script:{"*":[]},image:{"*":[]},iframe:{"*":[]},object:{"*":[]},subobject:{"*":[]}};for(var c=0;c<a.length;c++)for(var b=a[c].rules,d=0;d<b.length;d++)for(var e in domainMap)if(typeof b[d][e]!="undefined"){var f=typeof b[d][e]=="string"?b[d][b[d][e]]:b[d][e];DNTP.trackerNames[b[d].name]=b[d].name;f.name=b[d].name;f.category=b[d].category;if(IS_CHROME&&f.pattern.source&&(f.pattern=f.pattern.source,f.allowDomain&&f.allowDomain.source))f.allowDomain=
f.allowDomain.source;for(var g=f.domains.split("|"),h=0;h<g.length;h++)g[h]in domainMap[e]||(domainMap[e][g[h]]=[]),domainMap[e][g[h]].push(f)}};
function addNewTrackers(){var a=[];DNTP.settings.trackerMap["*"]||(DNTP.settings.trackerMap["*"]={});var c=DNTP.DEFAULT_TRACKER_STATE?1:0,b;for(b in DNTP.trackerNames)b in DNTP.settings.trackerMap["*"]||(DNTP.settings.trackerMap["*"][b]=c,webdb.setValue(b,c,"*"),a.push(b));freshInstall||DNTP.saveNewTrackers(a);DNTP.DISABLE_BAD_TRACKERS||DNTP.setupBadTrackers(Tracker.BadTrackers);freshInstall=!1}
var getURLForCookie=function(a){var c="http://";c+=a[1].indexOf(".")==0?a[1].substr(1):a[1];c+=a[2];return c},removeOptoutCookies=function(){for(var a in optoutMap)for(var c=optoutMap[a],b=0;b<c.length;b++)bridge.cookies.remove({url:getURLForCookie(c[b]),name:c[b][3]})},writeOptoutCookies=function(){for(var a in optoutMap)for(var c=optoutMap[a],b=0;b<c.length;b++)bridge.cookies.set({url:getURLForCookie(c[b]),name:c[b][3],value:c[b][4],domain:c[b][1],path:c[b][2]})},setupOptout=function(a){DNTP.OPTOUT_DISABLED&&
a==1&&(DNTP.Config.setWriteCookies(0),a=0);writeCookies=a==1;for(a=0;a<optout_cookies.length;a++)optoutMap[optout_cookies[a][1]]||(optoutMap[optout_cookies[a][1]]=[]),optoutMap[optout_cookies[a][1]].push(optout_cookies[a]);optout_cookies=null;writeCookies&&writeOptoutCookies()};webdb.open();
webdb.createTable(function(){window.setTimeout(function(){webdb.checkForRulesUpdate()},15E3);typeof customBackgroundScriptsInit=="function"&&customBackgroundScriptsInit();bridge.localeInit();bridge.initMessageHandler();bridge.initTabListener();bridge.initPopoverListener();webdb.initRulesFromDatabase();webdb.initDisabledSites();webdb.updateTag();webdb.updateInstallDate();webdb.updateOriginalVersion();webdb.getSetting("dntp.writecookies",0,setupOptout);webdb.updateTrackerMap();webdb.initTotalBlocked();
webdb.initNoteCounts();DNTP.Events.trigger("initialized");webdb.getSetting("dntp.useglobalallow",1,function(a){useGlobalAllow=a==1?!0:!1})});