var Components={utils:{"import":function(){}}},popoverDocument=null;
DNTP.extend({IMAGE_PATH:"../../chrome/content/images/",license:{isValid:!0},bundle:null,Counts:{totalBlocked:function(){return totalBlocked},socialBlocked:function(){var a=0,b;for(b in DNTP.socialBlocked)a+=DNTP.socialBlocked[b];return a}},settings:{notify:null,notifyDone:{}},Config:{get:function(a,b){return bridge.settings.getItem(a,b)},set:function(a,b){return bridge.settings.setItem(a,b)},getFile:function(a,b){var c=bridge.settings.getItem(a,b);typeof c==="string"&&(c=JSON.parse(c));return c},
setFile:function(a,b){typeof b!=="string"&&(b=JSON.stringify(b));bridge.settings.setItem(a,b)},getDisabledSites:function(){var a=[],b;for(b in disabledSites)a.push(b);return a},getDisabledSitesReason:function(){return disabledSitesReason},setDisabledSitesReason:function(a,b){disabledSitesReason[a]=b;webdb.updateDisabledSites()},getWriteCookies:function(){return writeCookies},setWriteCookies:function(a){writeCookies=a;webdb.setSetting("dntp.writecookies",a==1?"1":"0");a?writeOptoutCookies():removeOptoutCookies()},
getUseGlobalAllow:function(){return useGlobalAllow},setUseGlobalAllow:function(a){useGlobalAllow=a;webdb.setSetting("dntp.useglobalallow",a?1:0)},getLastTrackerUpdated:function(){return trackerLastUpdated}},dump:function(a){console.log(a)},showPopupBlue:function(){(new DNTP.View.Alert(docElement,bg.popoverDocument)).show()},showAllowedSites:function(){(new DNTP.View.AllowedSites(docElement,bg.popoverDocument)).show()},openPreferences:function(){},setupQwerly:function(){return null},blockTrackerPerSite:function(a,
b){allowTracker(a,b,topDomain)},refreshPrivacyAlert:function(){},setTimeout:function(){return window.setTimeout.apply(window,arguments)},clearTimeout:function(){return window.clearTimeout.apply(window,arguments)},toggle_tracker:function(a,b,c,e,d){toggleTracker(c,e,d)},toggle_social:function(a,b,c,e,d){toggleTracker(c,e,d)},toggle_all_trackers_on_site:function(a,b,c,e){toggleAllTrackersOnSite(c,e)},toggle_all_trackers_no_ui:function(a){toggleAllTrackers(a)},toggle_all_trackers:function(a,b,c){toggleAllTrackers(c)},
update_toolbar_icon:function(a){if(!a||typeof a!="number")a=tabID;try{updateToolbarIcon(a)}catch(b){}},gat:function(){},reportIssue:function(a,b){var c=bridge.app.getDetails().version,e=[],d;for(d in b.abineTracking)d!="length"&&e.push(d);d="";d+="version="+escape(""+c);d+="&origin=dntp_"+bridge.browser_name+"_"+escape(DNTP.origin);d+="&revision="+escape(""+REVISION);d+="&url="+escape(b.url);d+="&oversion=";d+="&description="+escape(a);d+="&async=1";d+="&rulesversion="+escape(Tracker.Version);e.length&&
(d+="&trackers="+escape(e.join(",")));c=bridge.getCurrentTabErrors(tabID);c.length&&(c=c.join(","),d+="&log="+escape(c));DNTP.sendRequest("http://abine.com/feedback/reportbug.php",function(){},d)},computeNotifications:function(a,b){var c={},e;for(e in b.abineBlocked)e!="length"&&(c[e]=1);c=DNTP.NotificationManager.getPersonDataForTab({host:b.host,url:b.url,blocked:c,language:navigator.language});b.abineNotifications=DNTP.NotificationManager.computeMessages(c)},openWindowInNewTab:function(a){bridge.openNewTab(a)},
setRequestHeaders:function(a){a.setRequestHeader("X-DNT-OVersion",original_version,!1);a.setRequestHeader("X-DNT-VERSION",DNTP.version+" "+bridge.browser_name+" "+ORIGIN+" "+REVISION);var b=installDate?installDate.getFullYear()+"-"+(installDate.getMonth()+1)+"-"+installDate.getDate():"-1";a.setRequestHeader("X-DNT-COHORT",b)},getDomain:function(a){return getUserTopLevelDomain(a)},alert:function(a){window.alert(a)},initTheme:function(){bridge.initTheme()},getVersion:function(){return DNTP.version},
getOriginalVersion:function(){return original_version},getFullVersion:function(){return DNTP.version+" "+bridge.browser_name+" "+ORIGIN+" "+REVISION},setHtml:function(a,b){if(a)a.innerHTML=b}});String.prototype.getHostname=function(){var a=this.match(/^http(?:s)?:\/\/([^/]+)/im);return a&&a.length>1?a[1].toString():null};
var compoundRealms=/^(((co|ac|go|ed|ga|mn|nj|nc|or|ne|in|gr|ca|on|pa|qc|bc|sh|at|va|us|il|tv|me|lg|at|ny|gv|nz|com|edu|org|net|gov|mil|biz)\...)|(163\.com)|(kiev\.ua)|(gob\.pe)|(gen\.tr)|(waw.pl)|(jus.br))$/,hostingSites=/^(((go|typepad|tumblr|blogspot|squarespace|wordpress|myshopify|blogfa|blog|blogs|blinkweb|ning|posterous|over-blog|mihanblog|appspot|webs|weebly|onsugar|ucoz|uk|pch|ecwid)(\.com|\.in))|(comcast\.net)|(nic\.in)|((ucoz|spb|narod)\.ru)|(blog\.163\.com)|((gouv|free)\.fr)|(uol\.com\.br)|(web\.id)|(gob\.mx)|(blogg\.se)|(home.pl))$/,
combinerScripts=/(\.js[^\/](.+\.js)+)/i,getUserTopLevelDomain=function(a){if(!a)return null;var b=a.split(".");if(b.length<2)return a;var a=b.pop(),c=b.pop(),a=c+"."+a;compoundRealms.test(a)&&b.length>0&&(c=b.pop(),a=c+"."+a);hostingSites.test(a)&&b.length>0&&(a=b.pop()+"."+a);return a};String.prototype.getDomain=function(){return getUserTopLevelDomain(this.getHostname())};
function getMatchingRuleV2(a,b,c){for(c=domainMap[c];;){if(b in c){for(var e=c[b],d=0;d<e.length;d++){var f=e[d];if(!f.pattern.source)f.pattern=RegExp(f.pattern,"i");if(a.match(f.pattern))return f}if(b=="*")return null}e=b.indexOf(".");b=e==-1?"*":b.substr(e+1)}}
function getMatchingRuleByNodeName(a,b,c){var e=null;if(a=="IMG")e=getMatchingRuleV2(b,c,"image");else if(a=="SCRIPT")b.match(combinerScripts)||(e=getMatchingRuleV2(b,c,"script"));else if(a=="IFRAME"||a=="FRAME")e=getMatchingRuleV2(b,c,"iframe");else if(a=="OBJECT"||a=="EMBED")(e=getMatchingRuleV2(b,c,"object"))||(e=getMatchingRuleV2(b,c,"subobject"));return e}
function trackerIsBlocked(a,b,c,e){var d=!1;a["*"]&&a["*"][c]==1&&!e&&(d=!0);a[b]&&a[b][c]==1&&(d=!0);a[b]&&a[b][c]==0&&(d=!1);a[b]&&a[b]["*"]==0&&(d=!1);return d};