var EXPORTED_SYMBOLS=[];Components.utils["import"]("resource://dntp/ff/overlay.js");DNTP.templates={};DNTP.templates.View_allowed_sites=function(b){this.window=b};
DNTP.templates.View_allowed_sites.prototype.render=function(b,c){var d="";if(c.toggledOff){d+='\n<div id="DNTPreport" class="block" style="padding:8px;">\n    <b>'+DNTP._("dntp.now.disabled",b.host)+'</b><br/><br/>\n    <span style="color:red;">'+DNTP._("dntp.webkit.pleasewait")+"</span><br/><br/>\n    "+DNTP._("dntp.helpothers")+'<br/><br/><div id=reasons><ul style="padding-left:10px;">\n    ';for(var a=1;a<5;a++){var e=DNTP._("off.reason."+a);a==4?b.observe("reason"+a,"click",function(){b.$("reasons").style.display=
"none";b.$("other").style.display="";b.$("DNTPdesc").focus()}):b.observe("reason"+a,"click",function(a){a=a||event;a=a.target||a.srcElement;b.$("DNTPdesc").value=a.textContent||a.innerText;b.reportIssue()});d+="\n        <li id=reason"+a+">"+e+"</li>\n    "}d+='\n    </ul></div>\n    <div id=other style="display:none">\n        <textarea id="DNTPdesc" style="width:90%;height:50px;resize:none;" name="description"></textarea>\n        <div class="am"><input type="submit" id="DNTPreportissueform" class="DNTPbutton2" style="padding: 5px; display: block; float: left"\n                           value="'+
DNTP._("dntp.submit")+'" />\n        </div>\n    </div>\n</div>\n';if(b.fadeTimer<15E3)b.fadeTimer=15E3;if(c.toggledOff)b.docElement.toggledOff=!1}d+='\n\n<div id="DNTPonOffAtSite">\n    ';c.disabledSites.length>0&&(d+='\n    <div class=fl style="margin-top:8px;">'+DNTP._("allowed.sites")+"</div><br class=cb />\n    ");d+="\n</div>\n";if(c.removedSite)d+='\n  <div class=block style="padding:5px;"><span style="color:green;">',DNTP._("now.blocking"),d+=" "+c.removedSite+"</span></div>\n  ",c.removedSite=
null;if(c.reloadRequired)c.reloadRequired=!1,d+='\n  <div class="block" style="background-color: #ffffcc; padding: 5px"><span>\n    '+DNTP._("dntp.webkit.pleasewait")+".</span>\n  </div>\n";d+='\n\n<div class="block">\n';if(c.disabledSites.length==0)d+="\n    <br/>"+DNTP._("none.disabled.sites")+"<br/><br/>\n";else{d+="\n    <ul class=allowedSites>\n    ";a=c.disabledSites.length-1;for(e=!0;a>=0;a--){var f=c.disabledSites[a];(function(a){b.observe(a,"click",function(){DNTP.toggle_tracker(b.parentDoc,
b.doc,!1,"*",a);c.removedSite=a;if(b.host==a)c.abineDisabled=!1,c.reloadRequired=!0,DNTP.update_toolbar_icon(b.parentDoc);b.show()})})(f);d+="\n        <li "+(!e?'style="border-top: solid 1px #e5e5e5;"':"")+'>\n            <img class=fr src="'+DNTP.getImageUrl("cross.gif")+'" id="'+f+'"/>\n            <div style="'+(f in c.reasons?"":"padding-top: 4px;")+'">'+f+"\n            ";f in c.reasons&&(d+="\n                <br/><small>"+c.reasons[f]+"</small>\n            ");d+="\n            </div>\n        </li>\n        ";
e=!1}d+="\n    </ul>\n"}d+="\n</div>\n";b.observe("DNTPreportissueform","click",b.bind(b.reportIssue));return d};DNTP.templates.View_layout=function(b){this.window=b};
DNTP.templates.View_layout.prototype.render=function(b,c){var d=DNTP._,a="";a+='<div id="dntpContainer">\n\t<div id="DNTPheader" style="background: #000 url('+DNTP.getImageUrl("header.png")+') top left repeat-x;">\n        <img src="'+DNTP.getImageUrl("logo.png")+'" height="16px" width="181px" />\n\t\t<span id="DNTPinvites">\n            <a target="_blank" class=externalLink id="DNTPinviteLink" href="http://www.donottrackplus.com/link.php?type=invite">\n\t            '+d("dntp.view.invitations")+
'\n            </a>\n\t\t</span>\n\t\t<div id="DNTPclosePopup" style="width:25px;font-size:175%;cursor:pointer;">\n            <a href="#"><img src="'+DNTP.getImageUrl("close-blue.png")+'" /></a>\n\t\t</div>\n\t</div>\n\t<div class="body">\n\t\t'+c.body+'\n\t</div>\n</div>\n<div style="clear:both;height:7px;"></div>\n<div class=footer style="font-weight:normal !important;font-size:80%;">\n\t<a class=externalLink target=_blank href="http://www.donottrackplus.com/link.php?type=abine">Abine.com</a>\n\t| '+
d("dntp.slogan")+'\n</div>\n<div class="cb clearfix" style="font-weight:normal !important;" id=footerLinks>\n\t<a class=externalLink target="_blank" href="http://www.donottrackplus.com/link.php?type=video">\n\t\t<img style="margin-bottom:-3px;" src="'+DNTP.getImageUrl("tv_icon.png")+'"/>\n    </a> |\n\t<a class=externalLink target="_blank" href="http://www.donottrackplus.com/link.php?type=how">\n\t\t'+d("dntp.footer.how")+'\n\t</a>\n\t<span id=DNTPshowGlobal> | <a href="#">'+d("dntp.footer.settings")+
'</a></span> |\n    <a class=externalLink id="chatWithUs" href="http://www.donottrackplus.com/link.php?type=chat" target=_blank>\n\t    '+d("dntp.footer.sayhello")+"\n    </a>\n</div>\n";if(c.notifications){a+='\n<div id="deletemeBar" class=am style="margin-top:5px;">\n\t';if(c.notifications.length==1){var e=c.notifications[0];if(e.badTracker)e.label=DNTP._(e.label,e.badTracker);a+='\n\t\t<div id="notificationMsgs">';a+=(new DNTP.templates.View_notification_link(this.window)).render(b,{item:e});a+=
"</div>\n    ";e.badTracker&&b.observe(e.id,"click",function(){var a=DNTP.Config.get("badTrackerClicked","");a||(a="");(","+a+",").indexOf(","+e.badTracker+",")==-1&&(a.length>0&&(a+=","),a+=e.badTracker,DNTP.Config.set("badTrackerClicked",a));b.openUrlInNewTab(DNTP.getLinkUrl("badTracker."+e.badTracker));return!1})}else{a+='\n\t<ul id="notificationMsgs">\n\t\t';for(d=0;d<3;d++)a+="\n\t\t\t<li>",a+=(new DNTP.templates.View_notification_link(this.window)).render(b,{item:c.notifications[d]}),a+="</li>\n\t\t\t",
b.addOnLoad(b.bind(b.verticallyCenter,c.notifications[d].id)),a+="\n\t\t";a+="\n\t"}a+="\n</div>\n"}a+="\n";b.observe("DNTPclosePopup","click",b.bind(b.close));b.observe("DNTPshowGlobal","click",b.bind(b.showGlobal));return a};DNTP.templates.View_notification_link=function(b){this.window=b};
DNTP.templates.View_notification_link.prototype.render=function(b,c){var d="",a=c.item.id,e=c.item.link,f=c.item.iframe,g=c.item.label,h="";c.item.plainLink&&(h=" plainLink");d+="\n";e&&!f?d+='\n\t<a class="externalLink '+h+'" id="'+a+'" target="_blank" href="'+e+'">'+g+"</a>\n":f?(d+='\n\t<a class="externalLink" id="'+a+'" href="javascript:void(0)">'+g+"</a>\n\t",b.observe(a,"click",b.bind(b.addNotificationIframe,e)),d+="\n"):d+='\n\t<a class="noLink" id="'+a+'" href="javascript:void(0)">'+g+"</a>\n";
return d};DNTP.templates.View_privacy=function(b){this.window=b};
DNTP.templates.View_privacy.prototype.render=function(b,c){var d=DNTP._,a="";a+='<\!-- allow/block --\>\n<div id="DNTPonOffAtSite">\n\t'+b.getNewVersionLink()+"\n";if(c.host&&c.host!=""){a+='\n\t<div class="vm fl" style="margin-top: 5px;">\n\t\t'+d(c.off?"onoff.off":"onoff.on")+'\n\t\t<img src="'+DNTP.getImageUrl("at_symbol.png")+'" class=vm style="width:17px;"/> '+c.host+"\n\t</div>\n\t";if(c.totalTrackers>0||c.off)a+='\n      <div id="toggleSite" class=fr>'+d(c.off?"dntp.turnon":"dntp.turnoff")+
"</div>\n\t  ",b.observe("toggleSite","click",b.bind(b.toggleOnOff)),a+="\n\t";a+="\n"}a+="\n\t<br class=cb />\n</div>\n\n<\!-- OFF or toggled ON state --\>\n";c.off?(a+='\n\t<div class=block style="padding: 5px;margin:5px 0;"><br/>'+d("dntp.turnedoff")+'\n\t\t<div class="am blueLinks" style="line-height:12pt;">\n\t\t\t'+d("dntp.turnedoff.block","<a href=# id=blockAgain>","</a>")+"\n\t\t\t<br/><br/>\n\t        "+d("dntp.turnedoff.viewall","<br/><a href=# id=allowedSites>","</a>")+"\n\t\t\t<br/>\n\t\t</div>\n\t\t",
b.observe("blockAgain","click",b.bind(b.toggleOnOff)),a+="\n\t\t",b.observe("allowedSites","click",DNTP.showAllowedSites),a+="\n\t\t<br/>\n\t</div>\n"):c.toggledOff&&(a+='\n\t<div class=block style="padding: 5px;">\n\t\t<br/>'+d("dntp.turnedon")+'\n\t\t<br/><br/><div style="color:red;">'+d("dntp.pleasewait")+"</div><br/>\n\t</div>\n");a+="\n\n<\!-- new badge --\>\n";if(c.newBadge){var e=c.newBadge;a+='\n\t<div style="background-image: url('+DNTP.getImageUrl("badge/badge_box_bg.png")+');" id="DNTPNewBadge">\n\t    <div class="badgeText badgeIconBig badge\''+
e.cssClass+"\n\t        badge"+e.cssClass+'Img" >\n\t\t    <div class="badgeCountBig">'+DNTP.addCommas(e.limit)+'</div>\n\t\t    <div class="badgeTextBig">'+d(e.badgeText)+'</div></div>\n\t    <div class="badgeCongrats">\n            '+d("dntp.badge.congrats","<br/> "+(e.level?e.level+b.getNumberSuffix(e.level)+" ":"")+d(e.name))+"<br/><br/>\n\t\t    <span>"+DNTP.addCommas(e.limit)+"</span>\n\t\t    "+d(e.text)+"\n\t    </div>\n\t</div>\n"}a+="\n\n<\!-- trackers/optouts --\>\n";!c.newBadge&&!c.off&&
(a+="\n\t\t",c.totalTrackers==0&&!c.firstPartySocial?(a+="\n\t\t\t",c.toggledOff||(a+='\n\t\t\t\t<div id="DNTPnoTrackingHere">\n                    <img src="'+DNTP.getImageUrl("sunrise.png")+'" id=dntpClearSkies height="50px;"/>\n                    <p style="text-align:center;"><br/><br/>'+d("clear.skies")+"<br/><br/><br/></p>\n                </div>\n\t\t\t"),a+="\n\t\t"):(a+='\n\t\t\t<div id="DNTPtrackingHere">\n\t\t\t\t',a+=(new DNTP.templates.View_social_block(this.window)).render(b,c),a+="\n\t\t\t\t",
a+=(new DNTP.templates.View_tracker_block(this.window)).render(b,c),a+="\n\t\t\t</div>\n\t\t"),a+="\n");a+="\n\n<\!-- totals --\>\n";!c.skipTotals&&c.globalTotal>0&&(e=c.badges[0],a+='\n<div class=block id="footerBlock">\n\t<div id="DNTPfooter" class=clearfix>\n\t',c.newBadge?(a+="\n\t\t",a+=(new DNTP.templates.View_tracking_report(this.window)).render(b,c)):(a+="\n\t\t",e.name!="None"&&(a+='\n\t    <div id="latestBadge" class="badgeText badge'+e.cssClass+" badge"+e.cssClass+'Img ">\n\t\t    <div class="badgeCountSmall">'+
DNTP.addCommas(e.limit)+"</div>\n\t    </div>\n\t\t",b.observe("trackingDetailed","click",b.bind(b.renderPartialInElement,"DNTPfooter","tracking_report",c,{newBadge:!0})),a+="\n\t\t"),a+='\n\t\t<div style="margin-top:5px;height:170px;" id="DNTPtrackingAttempts">\n\t        <span id="DNTPtotalBlockedIntro">\n\t            '+d("funword"+c.funWordIndex)+"!\n\t        </span>"+d("dntp.alltime")+'<br/>\n\t        <a href="javascript:void(0);" id="trackingDetailed">\n\t            <span id="DNTPtotalBlocked">'+
DNTP.addCommas(c.globalTotal)+"</span>\n\t            "+d("dntp.alltimesuffix",d(DNTP.plural("dntp.attempt",c.globalTotal)))+'\n\t        </a><br style="clear:both;"/>\n            <div id=chartdiv></div>\n            <a href="'+DNTP.getLinkUrl("dntReport")+'" target="_blank" class="externalLink" id=stats style="display:none;font-size: 9px;font-weight: normal;">\n                <img src="'+DNTP.getImageUrl("stats.png")+'"/><br/>\n                '+d("my.stats")+"\n            </a>\n\t\t</div>\n\t",
b.observe("trackingDetailed","click",b.bind(b.renderPartialInElement,"DNTPfooter","tracking_report",c,{newBadge:!1}))),a+="\n\t",a+="\n\t</div>\n</div>\n");b.addOnLoad(b.bind(b.renderChart));a+="\n";return a};DNTP.templates.View_settings=function(b){this.window=b};
DNTP.templates.View_settings.prototype.render=function(b,c){var d="",a=c.ruleArray,e=c.lastUpdateDateString,f=c.globalSettings,g="";c.useGlobalAllow==1&&(g="checked='checked'");d+="\n<div id='DNTPglobalTrackers'>\n    <p style='font-size:115%;font-weight:bold;color:white;'>"+DNTP._("dntp.global.controltracking")+"</p><br/>\n    <div id='DNTPlastUpdated'><br/>\n        <a href='#' id='DNTPbackToPopup' style='font-size:105%;padding-left:7px;text-decoration:underline;'>\n            "+DNTP._("dntp.global.back")+
"\n        </a>&nbsp;&nbsp;&nbsp;\n        ";b.canShowOldUI()&&(d+="\n          ",d+=DNTP.Config.get("theme","light")=="light"?"\n            <a href='#' style=\"text-decoration:underline;\" id='darkUi'>"+DNTP._("dntp.dark.ui")+"</a>\n          ":"\n            <a href='#' style=\"text-decoration:underline;\" id='lightUi'>"+DNTP._("dntp.light.ui")+"</a>\n          ",d+="&nbsp;&nbsp;&nbsp;\n        ");d+="\n        <a href='#' id='DNTPallowedSites' style=\"text-decoration: underline;\">"+DNTP._("dntp.global.allowedSites")+
"</a>\n        <p style='padding-bottom:3px;padding-top:20px;font-size:95%;'>\n            <a href='#' id='DNTPtoggle_all_blocked'>"+DNTP._("dntp.global.blockall")+"</a>\n            <a href='#' id='DNTPtoggle_all_unblocked'>"+DNTP._("dntp.global.unblockall")+"</a>\n        </p>\n    </div>\n    <div class=block>\n        <a class=externalLink href='http://www.donottrackplus.com/link.php?type=who-they-are'\n           style='color:blue !important;' target='_blank'>"+DNTP._("dntp.global.learnmore")+
"</a>\n\n        <ul id='DNTPtracker_list' style='height:200px;overflow-y:scroll;overflow-x:hidden;'>\n";for(var h={},i=0;i<a.length;i++){var j=a[i];if(!h[j]){h[j]=1;var k=j.replace(" ","");d+="<li id='g"+k+"'>"+j+"<span>";d+=f[j]==1?'\n            <img src="'+DNTP.getImageUrl("accept.gif")+'" /> '+DNTP._("dntp.global.blockedeverywhere")+"\n        ":'\n            <img src="'+DNTP.getImageUrl("cancel.gif")+'" /> '+DNTP._("dntp.global.notblocked")+"\n        ";d+="\n        </span></li>\n        ";
b.observe("g"+k,"click",b.bind(b.blockUnblock))}}d+="\n        </ul>\n    </div>\n\n    <span style='display:block;width:100%;border-style:none;margin:0px !important;padding:0px !important;border:none !important;text-align:center;background-color:#01273c;color:white;font-size:85%;'>\n        "+DNTP._("dntp.global.tpl")+" "+e+'\n        <br/>\n        <input type="checkbox" '+g+" id='DNTPuseRecs'/> "+DNTP._("dntp.global.useglobalallow")+"\n    </span>\n</div>\n";b.observe("DNTPuseRecs","click",b.bind(b.toggleUseRecs));
b.observe("DNTPbackToPopup","click",DNTP.showPopupBlue);b.observe("DNTPallowedSites","click",DNTP.showAllowedSites);b.observe("DNTPdntSignalDisplay","click",DNTP.openPreferences);b.observe("DNTPtoggle_all_blocked","click",b.bind(b.blockAll));b.observe("DNTPtoggle_all_unblocked","click",b.bind(b.allowAll));b.observe("darkUi","click",function(){b.changeTheme("default")});b.observe("lightUi","click",function(){b.changeTheme("light")});d+="\n";return d};
DNTP.templates.View_social_block=function(b){this.window=b};
DNTP.templates.View_social_block.prototype.render=function(b,c){var d=DNTP._,a="";if(c.toggledOff)return a;a+="\n";var e=c.social,f=c.blocked,g=c.firstPartySocial,h=c.abineMessage,i=c.domain,j=c.currentSocialCount,k=b.getTextColor(f,e),l=g?DNTP.socialMap[c.domain].blockImg:"social.png";a+='\n<div class="block" id="socialBlock">\n\t<div class="header clearfix '+(e.length==0&&!g?"empty":"")+'" id="socialTop">\n\t\t<div class=title id="DNTPsocialText">\n\t\t\t';e.length>0?(a+="\n\t\t\t\t"+d("dntp.socialtracking",
e.length,d(DNTP.plural("dntp.count.socialbutton",e.length)))+'\n\t\t\t\t<span id=DNTPsocialTextColor class=count style="color:'+k+'">\n                   '+c.socialBlocked+" "+d(DNTP.plural("dntp.Mblocked",c.socialBlocked))+"\n\t\t\t\t</span>\n                ",b.observe("socialTop","click",b.bind(b.toggleBlock,"DNTPsocial"))):(a+="\n\t\t\t\t",g?(a+="\n\t\t\t\t\t"+DNTP.socialMap[c.domain].name+" "+d("dntp.tracksacross")+"\n\t\t\t\t\t",b.observe("socialTop","click",b.bind(b.toggleBlock,"DNTPsocial")),
a+="\n\t\t\t\t"):a+="\n\t\t\t\t\t"+d("dntp.nosocial")+"\n\t\t\t\t");a+="\n\t\t\t";a+='\n\t\t</div>\n\t\t<img src="'+DNTP.getImageUrl(l)+'" /></div>\n        <div id="DNTPsocial" style="'+(g||h?"":"display:none;")+'max-height:150px;overflow:auto;" class="cb">\n\n\t        ';g&&(h=null,a+="\n\t\t        <span style='font-weight:normal;'>"+(DNTP.socialMap[i].name+" "+d("dntp.oneofseveral"))+"</span>\n                ",j>0&&(a+="\n                <br/><br/>\n                <div style='float:left;'>\n\t\t\t        <img src='"+
DNTP.getImageUrl(DNTP.socialMap[i].favicon)+"'\n\t\t                                      style='height:24px;width:24px;float:left;margin-right:4px;' />\n\t\t        </div>\n\t            <div style='float:left;font-size:1.6em;margin-right:5px;color:green;font-weight:normal !important;'>\n\t\t            "+j+"\n\t            </div>\n\t            <div style='float:left;display:inline;width:250px;font-weight:normal;'>\n\t\t            "+d("firstparty.youblocked",DNTP.socialMap[i].name,j,d(DNTP.plural("dntp.othersite",
j)))+"\n\t            </div>\n                <div style='clear:both;'></div>\n                "),a+="\n\t        ");a+="\n\n\t        ";h&&(a+="<div id='msgBorder' style='padding:4px;border:2px solid orange;position:relative'>");a+="\n\n\t        <ul id='DNTPsocialList'>\n\t\t        ";for(var m in e)m!="length"&&(g=m.replace(" ",""),i=e[m]==2?".recommended":"",b.observe(g,"click",b.bind(b.socialTrackerClicked,m)),a+='\n\t\t            <li id="'+g+"\">\n\t\t\t            <img class='socialBtn' src=\""+
DNTP.getImageUrl(DNTP.socialImages[m]+".PNG")+'" />\n\t\t\t            '+m+"\n\t\t\t\t\t\t<span id=DNTPsocialButtonText"+g+">\n\t\t                ",a+=m in f?'\n\t\t                    <img src="'+DNTP.getImageUrl("accept.gif")+'" /> '+d("dntp.capblockedhere"+i)+"\n\t\t\t\t\t\t":'\n\t\t                    <img src="'+DNTP.getImageUrl("cancel.gif")+'" /> '+d("dntp.notblockedhere"+i)+"\n\t\t                ",a+="\n\t\t                </span>\n\t\t            </li>\n\t\t        ");a+="\n\t\t        ";
e.length>0&&(a+="\n\t\t        <li class=nohover>\n\t\t\t        <a class=externalLink href='http://www.donottrackplus.com/link.php?type=how-social'\n\t\t\t           style='float:left;padding-top:5px;color:blue !important;' target='_blank'>\n\t\t\t            "+d("dntp.stillwork")+"\n\t\t\t        </a>\n\t\t        </li>\n\t\t        ");a+="\n\t\t    </ul>\n\n\t        ";h&&(a+="<br style='clear:both;'/><span id=abineMsg>"+h+"</span></div>");a+="\n\n\t    </div>\n\t</div>\n</div>\n";return a};
DNTP.templates.View_tracker_block=function(b){this.window=b};
DNTP.templates.View_tracker_block.prototype.render=function(b,c){var d=DNTP._,a="";if(c.toggledOff||c.abineMessage||c.firstPartySocial&&c.trackers.length==0)return a;a+="\n";var e=c.trackers,f=c.blocked,g=c.trackersBlocked,h=b.getTextColor(f,e);a+='\n<div class="block clearfix" id="trackerBlock">\n\t<div class="header clearfix '+(e.length==0?"empty":"")+'" id="trackerTop">\n\t\t<div class=title style="letter-spacing:.051em;" id="DNTPtrackerText">\n\t\t\t';e.length>0?(a+="\n\t\t        "+d("dntp.trackingcompany",
e.length,DNTP._(DNTP.plural("dntp.company",e.length)))+"\n                <span class=count style='letter-spacing:normal;color:"+h+"'>\n\t                "+g+" "+d(DNTP.plural("dntp.Fblocked",g))+"\n                </span>\n\t\t\t\t",b.observe("trackerTop","click",b.bind(b.toggleBlock,"DNTPtrackers")),a+="\n\t\t\t"):a+="\n                "+d("dntp.notrackingcompanies")+"\n            ";a+='\n        </div>\n\t\t<img src="'+DNTP.getImageUrl("trackers.png")+'"/>\n\t</div>\n\t';if(e.length>0){g="&c=";
h=!1;a+='\n        <div id="DNTPtrackers" style="display:none;max-height:150px;overflow:auto;" class="cb">\n            <ul id="DNTPtrackerList">\n            ';for(var i in e)if(i!="length"){g+=i+"~";var j=e[i]==2?".recommended":"";j!=""&&(h=!0);var k=i.replace(" ","");a+="\n                <li id='"+k+"' >"+i+"<span style='margin-right:1px;'>\n\t\t\t\t";a+=f[i]==1?"\n\t                 <img src='"+DNTP.getImageUrl("accept.gif")+"' /> "+d("dntp.capblockedhere"+j)+"\n                ":"\n                     <img src='"+
DNTP.getImageUrl("cancel.gif")+"' /> "+d("dntp.notblockedhere"+j)+"\n                ";a+="\n                </span></li>\n                ";b.observe(k,"click",b.bind(b.trackerClicked,i));a+="\n            "}a+="\n            <li class=nohover>\n              ";a+=h?"\n                  <a class=externalLink href='http://www.donottrackplus.com/link.php?type=recommended' target='_blank'>\n                    "+d("dntp.recommended")+"</a></li>\n              ":"\n                  <a class=externalLink href='http://www.donottrackplus.com/link.php?type=who-they-are' target='_blank'>\n                    "+
d("dntp.whoarethey")+"</a>\n              ";a+="\n            </li>\n\t        </ul>\n        </div>\n    "}a+="\n</div>";return a};DNTP.templates.View_tracking_report=function(b){this.window=b};
DNTP.templates.View_tracking_report.prototype.render=function(b,c){var d=DNTP._,a="",e=c.badges;a+='\n\n<ul id="reportTabs" class="tabs">\n\t<li id="trackingTab" class="selected"><a id="DNTPshowTracking" href="#">'+d("dntp.whoarethey")+'</a></li>\n\t<li id="badgeTab" class=""><a id="DNTPshowBadges" href="#">'+d("dntp.badges.mybadges")+'</a></li>\n</ul>\n\n<div id="badgeTabContent" style="display:none;" class="tabContent">\n\n';for(var f=0;f<e.length;f++){var g=e[f];a+="\n\t";f>0&&(a+='<div class="badgeSep">&nbsp;</div>');
a+='\n\t<div class="badgeBlock">\n\t\t'+d(g.title)+"\n\n    ";a+=g.name=="None"?'\n\t    <div class="" style="margin:10px auto;text-align:center;height:50px;">'+d("dntp.no.badge")+"</div>\n    ":'\n        <div class="badgeText badgeIconSmall badge'+g.cssClass+" badge"+g.cssClass+'Img">\n\t        <div class=badgeCountSmall>'+DNTP.addCommas(e[f].limit)+"</div>\n\t        <div class=badgeTextSmall>"+d(g.badgeText)+"</div>\n        </div>\n    ";a+="\n\t\t<div>\n\t";a+=g.nextBadge.name=="None"?"\n        "+
d("dntp.badges.maxlevel")+"\n    ":"\n        "+d("dntp.badges.levelup",DNTP.addCommas(g.nextBadge.limit),(g.nextBadge.level?g.nextBadge.level+b.getNumberSuffix(g.nextBadge.level)+" ":"")+d(g.nextBadge.name))+"\n    ";a+="\n\t\t</div>\n\n    </div>\n"}a+='\n\n\t<br style="clear:both;"/>\n\t<div style="float:right;padding:5px;font-size:10px;">\n\t\t<a style="color:blue;" class=externalLink href="http://www.donottrackplus.com/link.php?type=read-about-medals" target="_blank">\n\t\t\t'+d("dntp.readbadges")+
'\n\t\t</a>\n\t</div>\n\t<br style="clear:both;"/>\n</div>\n\n<div id="trackingTabContent" style="display:block;" class="tabContent">\n\t<table class="cb detailTable" style="margin-top: 10px;" cellspacing=0 cellpadding=3 width=100%>\n\t\t<tr><th align=left>'+d("dntp.whostried")+"</th><th align=right>"+d("dntp.numblocked")+"</th></tr>\n\t\t<tr>\n\t\t\t<td align=left>"+d("dntp.socialbuttons")+'</td>\n\t\t\t<td style="font-weight:normal;" align=right>'+DNTP.addCommas(c.globalSocialTotal)+"</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td align=left>"+
d("dntp.adnetworks")+'</td>\n\t\t\t<td style="font-weight:normal;" align=right>'+DNTP.addCommas(c.globalOptoutTotal)+"</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td align=left>"+d("dntp.trackingcompanies")+'</td>\n\t\t\t<td style="font-weight:normal;" align=right>'+DNTP.addCommas(c.globalTrackerTotal)+'</td>\n\t\t</tr>\n\t</table><br/>\n\n\t<div class=am style="font-size:100%;font-weight:normal;">\n\t\t'+d("dntp.intotalstart")+'\n\t\t<span style="font-weight:700;">'+DNTP.addCommas(c.globalTotal)+"</span>\n\t\t"+
d("dntp.intotalend",d(DNTP.plural("dntp.attempt",c.globalTotal)))+"\n\t</div><br/>\n</div>\n";b.addOnLoad(b.bind(b.tabs,"reportTabs",c.newBadge?"badgeTab":null));return a};DNTP.templates.View_light_allowed_sites=function(b){this.window=b};
DNTP.templates.View_light_allowed_sites.prototype.render=function(b,c){var d="";if(c.toggledOff){d+='\n<div id="DNTPreport" class="clearfix block highlight">\n    <b>'+DNTP._("dntp.now.disabled",b.host)+'</b><br/><br/>\n    <span style="color:red;">'+DNTP._("dntp.webkit.pleasewait")+"</span><br/><br/>\n    "+DNTP._("dntp.helpothers")+'<br/><br/>\n    <div id=reasons><ul style="padding-left:20px;">\n    ';for(var a=1;a<5;a++){var e=DNTP._("off.reason."+a);a==4?b.observe("reason"+a,"click",function(){b.$("reasons").style.display=
"none";b.$("other").style.display="";b.$("DNTPdesc").focus()}):b.observe("reason"+a,"click",function(a){a=a||event;a=a.target||a.srcElement;b.$("DNTPdesc").value=a.textContent||a.innerText;b.reportIssue()});d+="\n        <li id=reason"+a+">"+e+"</li>\n    "}d+='\n    </ul></div>\n    <div id=other style="display:none">\n        <textarea id="DNTPdesc" style="width:90%;height:50px;resize:none;" name="description"></textarea>\n        <div class="am"><input type="submit" id="DNTPreportissueform" class="DNTPbutton2"\n                               style="padding: 5px; display: block; float: left"\n                           value="'+
DNTP._("dntp.submit")+'" />\n        </div>\n    </div>\n</div>\n';if(b.fadeTimer<15E3)b.fadeTimer=15E3;if(c.toggledOff)b.docElement.toggledOff=!1}d+='\n\n<div id="DNTPonOffAtSite">\n    ';c.disabledSites.length>0&&(d+='\n    <div class=fl style="margin-top:8px;">'+DNTP._("allowed.sites")+"</div><br class=cb />\n    ");d+="\n</div>\n";if(c.removedSite)d+='\n  <div class=block style="padding:5px;"><span style="color:green;">',DNTP._("now.blocking"),d+=" "+c.removedSite+"</span></div>\n  ",c.removedSite=
null;if(c.reloadRequired)c.reloadRequired=!1,d+='\n  <div class="block" style="background-color: #ffffcc; padding: 5px"><span>\n    '+DNTP._("dntp.webkit.pleasewait")+"</span>\n  </div>\n";d+='\n\n<div class="block">\n    <ul class=allowedSites>\n';if(c.disabledSites.length==0)d+="\n    <li>"+DNTP._("none.disabled.sites")+"<br/><br/></li>\n";else{d+="\n    ";a=c.disabledSites.length-1;for(e=!0;a>=0;a--){var f=c.disabledSites[a];(function(a){b.observe(a,"click",function(){DNTP.toggle_tracker(b.parentDoc,
b.doc,!1,"*",a);c.removedSite=a;if(b.host==a)c.abineDisabled=!1,c.reloadRequired=!0,DNTP.update_toolbar_icon(b.parentDoc);b.show()})})(f);d+="\n        <li "+(!e?'style="border-top: solid 1px #e5e5e5;"':"")+'>\n            <img class=fr src="'+DNTP.getImageUrl("cross.gif")+'" id="'+f+'"/>\n            <div style="'+(f in c.reasons?"":"padding-top: 4px;")+'">'+f+"\n            ";f in c.reasons&&(d+="\n                <br/><small>"+c.reasons[f]+"</small>\n            ");d+="\n            </div>\n        </li>\n        ";
e=!1}d+="\n"}d+="\n    </ul>\n</div>\n";b.observe("DNTPreportissueform","click",b.bind(b.reportIssue));return d};DNTP.templates.View_light_layout=function(b){this.window=b};
DNTP.templates.View_light_layout.prototype.render=function(b,c){function d(a){return a.image?' class=imageButton style="background-image:url('+a.image+');background-repeat: no-repeat;" title="'+a.label+'" ':""}function a(a){return a.alert?'<img src="'+DNTP.getImageUrl("alert.png")+'" class=alert />':""}var e=DNTP._,f="";b.observe("abineArea","click",function(){var a=b.fixExternalLink(DNTP.getLinkUrl("abine"));DNTP.openWindowInNewTab(a);return!1});b.observe("dntmeArea","click",function(){var a=b.fixExternalLink(DNTP.getLinkUrl("how"));
DNTP.openWindowInNewTab(a);return!1});f+='\n<div id="dntpContainer">\n\t<div id="header">\n        <img src="'+DNTP.getImageUrl("logo.png")+'" height="16px" width="181px" style="margin-top:2px;" usemap="#logoMap"/>\n\t\t<div id="closePopup">\n            <a href="#"><img src="'+DNTP.getImageUrl("close.png")+'" height="20px" width="20px" title="Close"/></a>\n\t\t</div>\n\t\t<div id="help">\n            <a class=externalLink target="_blank" href="'+DNTP.getLinkUrl("dnt_faq")+'" title="Help">\n                <img src="'+
DNTP.getImageUrl("question.png")+'" height="20px" width="20px"/>\n            </a>\n\t\t</div>\n        <div id="showGlobal">\n            <img src="'+DNTP.getImageUrl("settings.png")+'" height="20px" width="20px"  title="'+e("dntp.footer.settings")+'"/>\n        </div>\n\t</div>\n\t<div class="body">\n\t\t'+c.body+'\n\t</div>\n</div>\n<map name=logoMap>\n    <area id="abineArea" shape="rect" coords="0,0,48,16" href="#" alt="Abine Inc.">\n    <area id="dntmeArea" shape="rect" coords="52,0,181,16" href="#" alt="Do Not Track Me">\n</map>\n';
if(c.notifications){f+='\n<div id="notifyBar" class=am>\n\t';if(c.notifications.length==1){var g=c.notifications[0];if(g.badTracker)g.label=DNTP._(g.label,g.badTracker);f+='\n\t\t<div id="notificationMsgs" '+d(g)+">\n            "+a(g)+"\n            ";f+=(new DNTP.templates.View_light_notification_link(this.window)).render(b,{item:g});f+="\n        </div>\n        ";b.addOnLoad(b.bind(b.verticallyCenter,g.id));f+="\n\t";g.badTracker&&b.observe(g.id,"click",function(){var a=DNTP.Config.get("badTrackerClicked",
"");a||(a="");(","+a+",").indexOf(","+g.badTracker+",")==-1&&(a.length>0&&(a+=","),a+=g.badTracker,DNTP.Config.set("badTrackerClicked",a));b.openUrlInNewTab(DNTP.getLinkUrl("badTracker."+g.badTracker));return!1})}else{f+='\n\t<ul id="notificationMsgs">\n\t\t';for(e=0;e<3;e++)f+="\n\t\t\t<li "+d(c.notifications[e])+">\n                "+a(c.notifications[e])+"\n                ",f+=(new DNTP.templates.View_light_notification_link(this.window)).render(b,{item:c.notifications[e]}),f+="\n            </li>\n\t\t\t",
b.addOnLoad(b.bind(b.verticallyCenter,c.notifications[e].id)),f+="\n\t\t";f+="\n\t"}f+="\n</div>\n"}f+='\n<div id="productBar" class="clearfix am cb" style="margin-top:5px;">\n    <a class=externalLink href="'+DNTP.getLinkUrl("deleteme")+'" target=_blank><img src="'+DNTP.getImageUrl("footer-del-me.png")+'" height="32px" /></a>\n    <a class=externalLink href="'+DNTP.getLinkUrl("maskme")+'" target=_blank><img src="'+DNTP.getImageUrl("footer-mask-me.png")+'" height="32px" /></a>\n</div>\n';b.observe("closePopup",
"click",b.bind(b.close));b.observe("showGlobal","click",b.bind(b.showGlobal));b.addOnLoad(function(){DNTP.setTimeout(b.bind(b.autoSizeIframe),200)});return f};DNTP.templates.View_light_new_trackers=function(b){this.window=b};
DNTP.templates.View_light_new_trackers.prototype.render=function(b,c){var d="",a=c.newTrackers;a.sort();for(var e={},f="",g=0;g<a.length;g++)e[a[g]]=1;b.observe("back","click",DNTP.showPopupBlue);b.doNotAutoRefresh=!0;d+="\n<div style=\"padding: 10px 10px 0;font-weight: normal;\">\n    <div style='font-size:120%;font-weight:bold;margin-bottom:8px;'>\n        "+DNTP._("dntp.new.trackers")+"\n    </div>\n    "+DNTP._("dntp.new.trackers.details")+'\n</div>\n<div class="block" style="margin: 10px;font-size: 14px;border: 1px solid #eee;">\n    <div id="DNTPtrackers" style="max-height:150px;overflow:auto;border-bottom-width: 0;" class="cb">\n        <ul class=DNTPtrackerList>\n            ';
for(var h in e)f!=""&&(f+=","),f+=h,d+='\n            <li style="color:#888;">'+h+"</li>\n            ";d+='\n        </ul>\n    </div>\n</div>\n<div style="padding: 10px;font-weight: normal" class=clearfix>\n    <a class="externalLink" target="_blank" href="'+DNTP.getLinkUrl("newTrackers",{"new":f})+'" >\n        '+DNTP._("dntp.new.trackers.link")+'\n    </a>\n    <a class="fr" href="#" id=back>'+DNTP._("dntp.global.back")+"</a>\n</div>\n\n\n";return d};
DNTP.templates.View_light_notification_link=function(b){this.window=b};
DNTP.templates.View_light_notification_link.prototype.render=function(b,c){var d="",a=c.item.id,e=c.item.link,f=c.item.iframe,g=c.item.label,h="";c.item.plainLink&&(h=" plainLink");c.item.image&&(g="");d+="\n";e&&!f?d+='\n\t<a class="externalLink'+h+'" id="'+a+'" target="_blank" href="'+e+'">'+g+"</a>\n":f?(d+='\n\t<a class="externalLink" id="'+a+'" href="#">'+g+"</a>\n\t",b.observe(a,"click",b.bind(b.addNotificationIframe,e)),d+="\n"):d+='\n\t<a class="noLink" id="'+a+'" href="#">'+g+"</a>\n";return d};
DNTP.templates.View_light_privacy=function(b){this.window=b};
DNTP.templates.View_light_privacy.prototype.render=function(b,c){var d=DNTP._,a="";if(!c.newBadge){var e=DNTP.Config.get("newTrackers","");if(e&&e!=""&&(e=e.split(","),e.length>0))return DNTP.Config.set("newTrackers",""),DNTP.update_toolbar_icon(),a+=(new DNTP.templates.View_light_new_trackers(this.window)).render(b,{newTrackers:e}),a}var f=c.badges,e=null;if(0<f.length&&f[0].nextBadge&&f[0].nextBadge.name!="None")e=f[0].nextBadge;var g=b.fixExternalLink(DNTP.getLinkUrl("recommended"));b.toggleTracker=
function(a,c,d){var d=d||event,e=d.target||d.srcElement;if(e.className.indexOf("suggested")!=-1)return b.openUrlInNewTab(g),!1;for(;!e.className||e.className.indexOf("tracker")==-1;)e=e.parentNode;if(e.getAttribute("animateProgress"))return!1;var f=e.className.indexOf("off")!=-1;b.animateButton(e,f?1:-1,function(){e.className=e.className.replace(/on|off/,f?"on":"off");c?b.socialTrackerClicked(a,{target:e}):b.trackerClicked(a,{target:e})})};a+="\n<\!-- allow/block --\>\n";if(c.off||!c.toggledOff&&
(c.totalTrackers>0||c.firstPartySocial)){a+='\n<div id="DNTPonOffAtSite">\n';if(c.host&&c.host!=""){a+="\n    ";c.firstPartySocial||(a+='\n\t<div class="topBar">\n\t\t<div class=domain>\n            '+c.host+'<br/>\n            <span style="font-size:11pt;font-style: italic;text-shadow: none;">\n               '+d(c.off?"is.tracking":"was.tracking")+"\n            </span>\n        </div>\n        ",!c.off&&c.totalTrackers>0&&(a+="\n        <div id=topCount class=count>\n            "+c.totalTrackers+
"\n        </div>\n        ",b.observe("topCount","click",b.bind(b.showAllBlocks))),a+="\n\t</div>\n    ");a+="\n\t";if(c.totalTrackers>0||c.off)a+='\n    <div class="clearfix am">\n        <div id="toggleSite" class="clearfix tracker '+(c.off?"off":"on")+'" style="margin-top: 8px;text-align: left;margin-left: 13px;">\n            <span class="button" style="background-image: url('+DNTP.getImageUrl("on-off.png")+');">\n                <img src="'+DNTP.getImageUrl("on-off-knob.png")+'" class=vm />\n            </span>\n            <span class="offMsg" style="width:auto;">'+
d("onoff.off.here")+'</span>\n            <span class="onMsg" id="toggleSiteOnMsg"\n                  style="width:auto;">'+d("onoff.on.here",c.blocked.length+"",d("dntp."+(c.blocked.length!=1?"companies":"company")))+"</span>\n        </div>\n    </div>\n    ",b.observe("toggleSite","click",function(){var a=b.$("toggleSite");if(a.getAttribute("animateProgress"))return!1;b.animateButton(a,c.off?1:-1,function(){var d=b.getButton(a);d.className=d.className.replace(/on|off/,c.off?"off":"on");b.toggleOnOff()})}),
a+="\n\t";a+="\n"}a+="\n\t<br class=cb />\n    "+b.getNewVersionLink()+"\n</div>\n"}a+="\n\n<\!-- OFF or toggled ON state --\>\n";c.off?(a+='\n\t<div class="am block highlight" style="margin:10px 5px;"><br/>'+d("dntp.turnedoff")+'\n\t\t<div class="blueLinks" style="line-height:12pt;">\n\t\t\t'+d("dntp.turnedoff.block","<a href=# id=blockAgain>","</a>")+"\n\t\t\t<br/><br/>\n\t        "+d("dntp.turnedoff.viewall","<br/><a href=# id=allowedSites>","</a>")+"\n\t\t\t<br/>\n\t\t</div>\n\t\t",b.observe("blockAgain",
"click",b.bind(b.toggleOnOff)),a+="\n\t\t",b.observe("allowedSites","click",DNTP.showAllowedSites),a+="\n\t\t<br/>\n\t</div>\n"):c.toggledOff&&(a+='\n\t<div class="block highlight" style="margin:10px 5px;">\n\t\t<br/>'+d("dntp.turnedon")+'\n\t\t<br/><br/><div style="color:red;">'+d("dntp.pleasewait")+"</div><br/>\n\t</div>\n");a+="\n\n<\!-- new badge --\>\n";if(c.newBadge){var f=c.newBadge,h=(f.level?f.level+b.getNumberSuffix(f.level)+" ":"")+d(f.name);a+='\n\t<div id="DNTPNewBadge" class=highlight>\n\t    <div class="badgeText badgeIconBig badge\''+
f.cssClass+"\n\t        badge"+f.cssClass+'Img" >\n\t\t    <div class="badgeCountBig">'+DNTP.addCommas(f.limit)+'</div>\n\t\t    <div class="badgeTextBig">'+d(f.badgeText)+'</div></div>\n\t    <div class="badgeCongrats">\n\t\t    '+d("dntp.badge.congrats","<br/> "+h)+"<br/><br/>\n\t\t    <span>"+DNTP.addCommas(f.limit)+"</span>\n\t\t    "+d(f.text)+'\n\t    </div>\n\t</div>\n    <div class="am">'+d("dntp.badge.new.share")+':\n        <a class="externalLink" target="_blank" href="'+DNTP.getLinkUrl("badgeShare",
{where:"fb",name:h,limit:f.limit,"new":1})+'">\n            <img class=vm src="'+DNTP.getImageUrl("fb_sm.png")+'" height="16px"/>\n        </a>\n        <a class="externalLink" target="_blank" href="'+DNTP.getLinkUrl("badgeShare",{where:"tw",name:h,limit:f.limit,"new":1})+'">\n            <img class=vm src="'+DNTP.getImageUrl("tw_sm.png")+'" height="16px"/>\n        </a>\n    </div>\n'}a+="\n\n<\!-- trackers/optouts --\>\n";!c.newBadge&&!c.off&&(a+="\n\t\t",c.totalTrackers==0&&!c.firstPartySocial?
(a+="\n\t\t\t",c.toggledOff||(a+='\n\t\t\t\t<div id="DNTPnoTrackingHere" class="clearfix">\n                    <img class=sun src="'+DNTP.getImageUrl("sun.png")+'" id=dntpClearSkies height="100px;"/>\n                    <div class=text>\n                        <b>'+d("clear.skies")+"</b>\n                        ",c.hostname&&(a+='\n                        <br/><br/>\n                        <span style="font-weight: normal;">'+d("dntp.clearskies.thanks",c.host)+'\n                            <a class="externalLink" target="_blank" href="'+
DNTP.getLinkUrl("noTrackingThanks",{where:"fb",host:c.host})+'">\n                                <img class=vm src="'+DNTP.getImageUrl("fb_sm.png")+'" height="16px"/>\n                            </a>\n                            <a class="externalLink" target="_blank" href="'+DNTP.getLinkUrl("noTrackingThanks",{where:"tw",host:c.host})+'">\n                                <img class=vm src="'+DNTP.getImageUrl("tw_sm.png")+'" height="16px"/>\n                            </a>\n                        </span>\n        \t\t\t    '),
a+="\n                    </div>\n                </div>\n\t\t\t"),a+="\n\t\t"):(a+='\n\t\t\t<div id="DNTPtrackingHere">\n\t\t\t\t',a+=(new DNTP.templates.View_light_social_block(this.window)).render(b,c),a+="\n\t\t\t\t",a+=(new DNTP.templates.View_light_tracker_block(this.window)).render(b,c),a+="\n\t\t\t</div>\n\t\t"),a+="\n");a+="\n\n<\!-- totals --\>\n";if(!c.skipTotals&&c.globalTotal>0){f=c.badges[0];a+='\n<div class=block id="footerBlock">\n\t<div id="DNTPfooter" class=clearfix>\n\t';if(c.newBadge)a+=
"\n\t\t",a+=(new DNTP.templates.View_light_tracking_report(this.window)).render(b,c);else{a+="\n\t\t";f.name!="None"&&(a+='\n\t    <div id="latestBadge" class="badge'+f.cssClass+" badge"+f.cssClass+'Img ">\n\t\t    <div class=badgeText >'+DNTP.addCommas(f.limit)+"</div>\n\t    </div>\n\t\t",b.observe(["latestBadge"],"click",b.bind(b.renderPartialInElement,"DNTPfooter","tracking_report",c,{newBadge:!0})),a+="\n\t\t");a+='\n\t\t<div style="margin-top:5px;height:170px;" id="DNTPtrackingAttempts">\n\t        <span id="DNTPtotalBlockedIntro">\n\t            '+
d("funword"+c.funWordIndex)+"!\n\t        </span>"+d("dntp.alltime")+'\n\t        <a href="javascript:void(0);" id="trackingDetailed">\n\t            <span id="DNTPtotalBlocked">'+DNTP.addCommas(c.globalTotal)+"</span>\n\t            "+d("dntp.alltimesuffix",d(DNTP.plural("dntp.attempt",c.globalTotal)))+"\n\t        </a>\n            ";if(c.totalTrackers>0||c.firstPartySocial)a+='\n            <a class="externalLink" target="_blank" href="'+DNTP.getLinkUrl("totalShare",{where:"fb",total:c.globalTotal})+
'">\n                <img class=vm src="'+DNTP.getImageUrl("fb_sm.png")+'" height="16px"/>\n            </a>\n            <a class="externalLink" target="_blank" href="'+DNTP.getLinkUrl("totalShare",{where:"tw",total:c.globalTotal})+'">\n                <img class=vm src="'+DNTP.getImageUrl("tw_sm.png")+'" height="16px"/>\n            </a>\n            ';a+='\n            <br style="clear:both;"/>\n            <div id=chartdiv class="clearfix"></div>\n            ';e&&e.limit-c.globalTotal>0&&(a+=
'\n            <div id="nextBadgeMsg" style="display: none;">\n               '+d("dntp.badges.levelup.diff",DNTP.addCommas(e.limit-c.globalTotal),(e.level?"<br/>"+e.level+b.getNumberSuffix(e.level)+" ":"")+d(e.name))+"\n            </div>\n            ");a+='\n            <a href="'+DNTP.getLinkUrl("dntReport")+'" target="_blank" class="externalLink" id=stats style="display:none;">\n                <img src="'+DNTP.getImageUrl("stats.png")+'"/><br/>\n                '+d("my.stats")+"\n            </a>\n\t\t</div>\n\t    ";
b.observe("trackingDetailed","click",b.bind(b.renderPartialInElement,"DNTPfooter","tracking_report",c,{newBadge:!1}))}a+="\n\t";a+="\n\t</div>\n</div>\n"}b.addOnLoad(b.bind(b.renderChart));a+="\n";return a};DNTP.templates.View_light_settings=function(b){this.window=b};
DNTP.templates.View_light_settings.prototype.render=function(b,c){var d=DNTP._,a="",e=c.useGlobalAllow,f=c.ruleArray,g=c.lastUpdateDateString,h=c.globalSettings,i=DNTP.Config.get("global.blocked",DNTP.DEFAULT_TRACKER_STATE?"1":"0"),j="";e==1&&(j="checked='checked'");a+="\n<div id='DNTPglobalTrackers' style=\"padding: 0px 2px;\">\n    <div style='font-size:120%;font-weight:bold;margin-bottom:8px;'>\n        <img src=\""+DNTP.getImageUrl("gear.png")+'" class=vm height=18px style="margin-top:-3px;padding: 0 3px 0 5px;"/>\n        '+
DNTP._("dntp.footer.settings")+'\n    </div>\n    <div class="clearfix">\n        <div id="toggleSite" class="clearfix fl tracker '+(i==1?"on":"off")+'" style="margin: 8px 0 10px 13px;text-align: left;">\n            <div class="fr onMsg">'+d("dntp.global.all.blockedeverywhere")+'</div>\n            <div class="fr offMsg">'+d("dntp.global.all.allowedeverywhere")+'</div>\n            <div class="fr button" style="background-image: url('+DNTP.getImageUrl("on-off.png")+');">\n                <img src="'+
DNTP.getImageUrl("on-off-knob.png")+'"/>\n            </div>\n        </div>\n        ';b.observe("toggleSite","click",function(){var a=b.$("toggleSite");if(a.getAttribute("animateProgress"))return!1;b.animateButton(a,i==1?-1:1,function(){var a=b.$("toggleSite");a.className=a.className.replace(/on|off/,i==1?"off":"on");i==1?(b.allowAll(),i=0):(b.blockAll(),i=1)})});a+="\n    </div>\n    <br class=cb />\n    <div class=block>\n        <ul id='DNTPtrackerList' class=\"trackers\" style='height:200px;overflow-y:scroll;overflow-x:hidden;border:1px solid #eee;border-width: 1px 0px;margin-top: 5px;'>\n";
for(var e={},k=0;k<f.length;k++){var l=f[k];if(!e[l]){e[l]=1;var m="g"+l.replace(" ","");a+='\n            <li id="'+m+'"\n                 class="tracker clearfix ';a+=h[l]==1?"on":"off";a+='">\n                <div class="fl name">'+l+'</div>\n                <div class="fr onMsg">'+d("dntp.global.blockedeverywhere")+'</div>\n                <div class="fr offMsg">'+d("dntp.global.notblocked")+'</div>\n                <div class="fr button" style="background-image: url('+DNTP.getImageUrl("on-off.png")+
');">\n                    <img class=skip src="'+DNTP.getImageUrl("on-off-knob.png")+'"/>\n                </div>\n            </li>\n        '}}a+="\n        </ul>\n    </div>\n\n    <span class=\"am\" style='display:block;width:100%;padding:0px !important;font-size:85%;'>\n        "+DNTP._("dntp.global.tpl")+" "+g+'\n        <br/>\n        <input type="checkbox" '+j+" id='DNTPuseRecs'/> "+DNTP._("dntp.global.useglobalallow")+'\n    </span>\n</div>\n<div class="cb am" style="margin-top: 5px;">\n    <a href=\'#\' class="button" id=\'DNTPallowedSites\'>'+
DNTP._("dntp.global.allowedSites")+"</a>\n    ";b.canShowOldUI()&&(a+="\n      ",a+=DNTP.Config.get("theme","light")=="light"?"\n        <a href='#' class=\"button\" id='darkUi'>"+DNTP._("dntp.dark.ui")+"</a>\n      ":"\n        <a href='#' class=\"button\" id='lightUi'>"+DNTP._("dntp.light.ui")+"</a>\n      ",a+="\n    ");a+="\n    <a href='#' class=\"button\" id='DNTPbackToPopup'>"+DNTP._("dntp.global.back")+"</a>\n</div>\n";b.observe("DNTPtrackerList","click",b.bind(function(a){for(var a=a||event,
c=a.target||a.srcElement;!c.className||c.className.indexOf("tracker")==-1;)c=c.parentNode;if(c.getAttribute("animateProgress"))return!1;for(var d=null,a=c.firstChild;a&&(!a.className||a.className.indexOf("name")==-1);)a=a.nextSibling;if(!a)return!1;var d=a.textContent||a.innerText,e=c.className.indexOf("off")!=-1;b.animateButton(c,e?1:-1,function(){c.className=c.className.replace(/on|off/,e?"on":"off");DNTP.toggle_tracker(b.parentDoc,b.doc,e,d,"*",!1)})}));b.observe("DNTPuseRecs","click",b.bind(b.toggleUseRecs));
b.observe("DNTPbackToPopup","click",DNTP.showPopupBlue);b.observe("DNTPallowedSites","click",DNTP.showAllowedSites);b.observe("DNTPdntSignalDisplay","click",DNTP.openPreferences);b.observe("darkUi","click",function(){b.changeTheme("default")});b.observe("lightUi","click",function(){b.changeTheme("light")});a+="\n";return a};DNTP.templates.View_light_social_block=function(b){this.window=b};
DNTP.templates.View_light_social_block.prototype.render=function(b,c){var d=DNTP._,a="";if(c.toggledOff)return a;a+="\n";var e=c.social,f=c.blocked,g=c.firstPartySocial,h=c.abineMessage,i=c.domain,j=c.currentSocialCount,k=b.getTextColor(f,e),l=b.getSocialImage(f,e),m=!1;a+='\n<div class="block" id="socialBlock">\n\t<div class="header clearfix '+(e.length==0&&!g?"empty":"")+'" id="socialTop">\n\t\t<div class=title id="DNTPsocialText">\n\t\t\t';e.length>0?(a+="\n\t\t\t\t"+d("dntp.socialtracking",e.length,
d(DNTP.plural("dntp.count.socialbutton",e.length)))+'\n\t\t\t\t<span id=DNTPsocialTextColor class=count style="color:'+k+'">\n                   '+c.socialBlocked+" "+d(DNTP.plural("dntp.Mblocked",c.socialBlocked))+"\n\t\t\t\t</span>\n                ",b.observe("socialTop","click",b.bind(b.toggleBlock,"DNTPsocial"))):(a+="\n\t\t\t\t",g?(a+="\n\t\t\t\t\t"+DNTP.socialMap[c.domain].name+" "+d("dntp.tracksacross")+"\n\t\t\t\t\t",b.observe("socialTop","click",b.bind(b.toggleBlock,"DNTPsocial")),a+="\n\t\t\t\t"):
(m=!0,a+="\n\t\t\t\t\t"+d("dntp.nosocial")+"\n\t\t\t\t"));a+="\n\t\t\t";a+='\n\t\t</div>\n\t\t<img src="'+DNTP.getImageUrl(l)+'" id="DNTPsocialIcon"  height="36px" width="36px" /></div>\n        ';if(!m){a+='\n        <div id="DNTPsocial" style="'+(g||h?"":"display:none;")+'\n                        max-height:150px;overflow:hidden;" class="cb clearfix">\n\n\t        ';g&&(h=null,a+="\n                <div style=\"padding:5px;\" class=clearfix>\n\t\t        <span style='font-weight:normal;'>"+(DNTP.socialMap[i].name+
" "+d("dntp.oneofseveral"))+"</span>\n                ",j>0&&(a+="\n                <br/><br/>\n                <div style='float:left;'>\n\t\t\t        <img src='"+DNTP.getImageUrl(DNTP.socialMap[i].favicon)+"'\n\t\t                                      style='height:24px;width:24px;float:left;margin-right:4px;' />\n\t\t        </div>\n\t            <div style='float:left;font-size:1.6em;margin-right:5px;color:green;font-weight:normal !important;'>\n\t\t            "+j+"\n\t            </div>\n\t            <div style='float:left;display:inline;width:250px;font-weight:normal;'>\n\t\t            "+
d("firstparty.youblocked",DNTP.socialMap[i].name,j,d(DNTP.plural("dntp.othersite",j)))+"\n\t            </div>\n                <div style='clear:both;'></div>\n                "),a+="\n                </div>\n\t        ");a+="\n\n\t        ";h&&(a+="<div id='msgBorder' style='padding:4px;border:2px solid orange;position:relative'>");a+="\n\n\t        <ul id='DNTPsocialList'>\n\t\t        ";for(var n in e)n!="length"&&(g=n.replace(" ",""),i=e[n]==2?".recommended":"",j=e[n]==2?"suggested":"",b.observe(g,
"click",b.bind(b.toggleTracker,n,!0)),a+='\n                <li id="'+g+'"\n                     class="tracker clearfix ',a+=n in f?"on":"off",a+='">\n                    <div class="fl name">'+n+'</div>\n                    <div class="fr onMsg '+j+'">'+d("dntp.capblockedhere"+i)+'</div>\n                    <div class="fr offMsg '+j+'">'+d("dntp.notblockedhere"+i)+'</div>\n                    <div class="fr button" style="background-image: url('+DNTP.getImageUrl("on-off.png")+');">\n                        <img class=skip src="'+
DNTP.getImageUrl("on-off-knob.png")+'"/>\n                    </div>\n                </li>\n\t\t        ');a+="\n\t\t        ";e.length>0&&(a+="\n\t\t        <li class=nohover>\n\t\t\t        <a class=externalLink href='"+DNTP.getLinkUrl("how-social")+"'\n\t\t\t           style='float:left;padding-top:5px;' target='_blank'>\n\t\t\t            "+d("dntp.stillwork")+"\n\t\t\t        </a>\n\t\t        </li>\n\t\t        ");a+="\n\t\t    </ul>\n\n\t        ";h&&(a+="<br style='clear:both;'/><span id=abineMsg>"+
h+"</span></div>");a+="\n\n\t    </div>\n        "}a+="\n\t</div>\n</div>\n";return a};DNTP.templates.View_light_tracker_block=function(b){this.window=b};
DNTP.templates.View_light_tracker_block.prototype.render=function(b,c){var d=DNTP._,a="";if(c.toggledOff||c.abineMessage||c.firstPartySocial&&c.trackers.length==0)return a;a+="\n";var e=c.trackers,f=c.blocked,g=c.trackersBlocked,h=b.getTextColor(f,e),i=b.getTrackerImage(f,e);a+='\n<div class="block clearfix" id="trackerBlock">\n\t<div class="header clearfix '+(e.length==0?"empty":"")+'" id="trackerTop">\n\t\t<div class=title style="letter-spacing:.051em;" id="DNTPtrackerText">\n\t\t\t';e.length>0?
(a+="\n\t\t        "+d("dntp.trackingcompany",e.length,DNTP._(DNTP.plural("dntp.company",e.length)))+"\n                <span class=count style='letter-spacing:normal;color:"+h+"'>\n\t                "+g+" "+d(DNTP.plural("dntp.Fblocked",g))+"\n                </span>\n\t\t\t\t",b.observe("trackerTop","click",b.bind(b.toggleBlock,"DNTPtrackers")),a+="\n\t\t\t"):a+="\n                "+d("dntp.notrackingcompanies")+"\n            ";a+='\n        </div>\n\t\t<img src="'+DNTP.getImageUrl(i)+'" id="DNTPtrackerIcon" height="36px" width="36px" />\n\t</div>\n\t';
if(e.length>0){g="&c=";h=!1;a+='\n        <div id="DNTPtrackers" style="display:none;max-height:150px;overflow:auto;" class="cb">\n            <ul id="DNTPtrackerList">\n            ';for(var j in e)if(j!="length"){g+=j+"~";var i=e[j]==2?".recommended":"",k=e[j]==2?"suggested":"";i!=""&&(h=!0);var l=j.replace(" ","");a+='\n\n                <li id="'+l+'"\n                     class="tracker clearfix ';a+=j in f?"on":"off";a+='">\n                    <div class="fl name">'+j+'</div>\n                    <div class="fr onMsg '+
k+'">'+d("dntp.capblockedhere"+i)+'</div>\n                    <div class="fr offMsg '+k+'">'+d("dntp.notblockedhere"+i)+'</div>\n                    <div class="fr button" style="background-image: url('+DNTP.getImageUrl("on-off.png")+');">\n                        <img class=skip src="'+DNTP.getImageUrl("on-off-knob.png")+'"/>\n                    </div>\n                </li>\n                ';b.observe(l,"click",b.bind(b.toggleTracker,j,!1));a+="\n            "}a+="\n            <li class=nohover>\n              ";
a+=h?"\n                  <a class=externalLink href='"+DNTP.getLinkUrl("recommended")+"' target='_blank'>\n                    "+d("dntp.recommended")+"</a></li>\n              ":"\n                  <a class=externalLink href='"+DNTP.getLinkUrl("who-they-are")+"' target='_blank'>\n                    "+d("dntp.whoarethey")+"</a>\n              ";a+="\n            </li>\n\t        </ul>\n        </div>\n    "}a+="\n</div>";return a};
DNTP.templates.View_light_tracking_report=function(b){this.window=b};
DNTP.templates.View_light_tracking_report.prototype.render=function(b,c){var d=DNTP._,a="",e=c.badges;a+='\n\n<ul id="reportTabs" class="tabs">\n\t<li id="trackingTab" class="selected" style="margin-left: 5px;"><a id="DNTPshowTracking" href="#">'+d("dntp.whoarethey")+'</a></li>\n\t<li id="badgeTab" class=""><a id="DNTPshowBadges" href="#">'+d("dntp.badges.mybadges")+'</a></li>\n</ul>\n\n<div id="badgeTabContent" style="display:none;" class="tabContent">\n\n';for(var f=0;f<e.length;f++){var g=e[f];
a+="\n\t";f>0&&(a+='<div class="badgeSep">&nbsp;</div>');a+='\n\t<div class="badgeBlock">\n\t\t'+d(g.title)+"\n\n    ";a+=g.name=="None"?'\n\t    <div class="" style="margin:10px auto;text-align:center;height:50px;">'+d("dntp.no.badge")+"</div>\n    ":'\n        <div class="badgeText badgeIconSmall badge'+g.cssClass+" badge"+g.cssClass+'Img">\n\t        <div class=badgeCountSmall>'+DNTP.addCommas(e[f].limit)+"</div>\n\t        <div class=badgeTextSmall>"+d(g.badgeText)+"</div>\n        </div>\n    ";
a+="\n\t\t<div>\n\t";a+=g.nextBadge.name=="None"?"\n        "+d("dntp.badges.maxlevel")+"\n    ":"\n            "+d("dntp.badges.levelup",DNTP.addCommas(g.nextBadge.limit),(g.nextBadge.level?"<br/>"+g.nextBadge.level+b.getNumberSuffix(g.nextBadge.level)+" ":"")+d(g.nextBadge.name))+"\n    ";a+="\n\t\t</div>\n\n    </div>\n"}a+='\n\n    <div class="cb clearfix" style="padding:5px;font-size:10px;">\n    ';e.length>0&&e[0].name!="None"&&(g=e[0],e=(g.level?g.level+b.getNumberSuffix(g.level)+" ":"")+d(g.name),
a+="\n        <div class=fl>\n        "+d("dntp.badge.share")+':\n\n        <a class="externalLink" target="_blank" href="'+DNTP.getLinkUrl("badgeShare",{where:"fb",name:e,limit:g.limit})+'">\n            <img class=vm src="'+DNTP.getImageUrl("fb_sm.png")+'" height="16px"/>\n        </a>\n        <a class="externalLink" target="_blank" href="'+DNTP.getLinkUrl("badgeShare",{where:"tw",name:e,limit:g.limit})+'">\n            <img class=vm src="'+DNTP.getImageUrl("tw_sm.png")+'" height="16px"/>\n        </a>\n        </div>\n    ');
a+='\n        <div class="fr" style="margin-top: 3px;">\n            <a class=externalLink href="'+DNTP.getLinkUrl("read-about-medals")+'" target="_blank">\n                '+d("dntp.readbadges")+'\n            </a>\n        </div>\n    </div>\n\t<br style="clear:both;"/>\n</div>\n\n<div id="trackingTabContent" style="display:block;padding: 0 10px;" class="tabContent">\n\t<table class="cb detailTable" style="margin-top: 10px;" cellspacing=0 cellpadding=3 width=100%>\n\t\t<tr><th align=left>'+d("dntp.whostried")+
"</th><th align=right>"+d("dntp.numblocked")+"</th></tr>\n\t\t<tr>\n\t\t\t<td align=left>"+d("dntp.socialbuttons")+'</td>\n\t\t\t<td style="font-weight:normal;" align=right>'+DNTP.addCommas(c.globalSocialTotal)+"</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td align=left>"+d("dntp.trackingcompanies")+'</td>\n\t\t\t<td style="font-weight:normal;" align=right>'+DNTP.addCommas(c.globalTrackerTotal)+'</td>\n\t\t</tr>\n\t</table><br/>\n\n\t<div class=am style="font-size:100%;font-weight:normal;">\n\t\t'+d("dntp.intotalstart")+
'\n\t\t<span style="font-weight:700;">'+DNTP.addCommas(c.globalTotal)+"</span>\n\t\t"+d("dntp.intotalend",d(DNTP.plural("dntp.attempt",c.globalTotal)))+'\n        <a class="externalLink" target="_blank" href="'+DNTP.getLinkUrl("totalShare",{where:"fb",total:c.globalTotal})+'">\n            <img class=vm src="'+DNTP.getImageUrl("fb_sm.png")+'" height="16px"/>\n        </a>\n        <a class="externalLink" target="_blank" href="'+DNTP.getLinkUrl("totalShare",{where:"tw",total:c.globalTotal})+'">\n            <img class=vm src="'+
DNTP.getImageUrl("tw_sm.png")+'" height="16px"/>\n        </a>\n\n\t</div><br/>\n</div>\n';b.addOnLoad(b.bind(b.tabs,"reportTabs",c.newBadge?"badgeTab":null));return a};