var EXPORTED_SYMBOLS=["DNTP"];if(typeof Components=="undefined"||typeof Components.utils=="undefined")Components={utils:{"import":function(){}}};
var REVISION=9705,ORIGIN="ChromeStore",VERSION="2.2.8.109",GUID="donottrackplus@abine.com",ADDON_NAME="DoNotTrackMe",SILENT=!1,DNTP={DEFAULT_TRACKER_STATE:!0,OPTOUT_DISABLED:!0,DISABLE_BAD_TRACKERS:!1,DISABLE_PRIVACY_UPDATE:!1,DISABLE_DAILY_TOTALS:!1,GUID:GUID,ADDON_NAME:ADDON_NAME,revision:REVISION,origin:ORIGIN,version:VERSION,SILENT:SILENT,currentLocale:"en",theme:null,LinkBaseUrl:"http://donottrackplus.com/link.php",OptoutUpdateUrl:"http://www.abine.com/permacookie/list.php",RulesUpdateUrl:"http://www.abine.com/rules/update.php",
TagUpdateUrl:"http://www.abine.com/donottrackme/tag.php",extend:function(a){for(var b in a)DNTP[b]=a[b]},socialMap:{"facebook.com":{favicon:"facebook.png",trackerName:"Facebook Connect",name:"Facebook",blockImg:"facebook.png"},"google.com":{favicon:"google.png",trackerName:"Google +1",name:"Google",blockImg:"google.png"},"gmail.com":{favicon:"google.png",trackerName:"Google +1",name:"Google",blockImg:"facebook.png"},"twitter.com":{favicon:"twitter.png",trackerName:"Twitter Badge",name:"Twitter",blockImg:"twitter.png"},
"linkedin.com":{favicon:"linked-in.png",trackerName:"LinkedIn",name:"LinkedIn",blockImg:"linked-in.png"}},socialImages:{"Facebook Connect":"like","Google +1":"plusone","Twitter Badge":"tweet",LinkedIn:"linkedin"},socialBlocked:{"Facebook Connect":0,"Twitter Badge":0,"Google +1":0,LinkedIn:0},notificationMessages:[],abineDomainsRegex:/^(.+\.)?(donottrackplus\.com|donotrackplus\.com|abine.com)|(localhost:[0-9]+)$/i,$A:function(a){if(!a)return[];if("toArray"in a)return a.toArray();for(var b=a.length||
0,c=Array(b);b--;)c[b]=a[b];return c},plural:function(a,b){return!a?a:b!="1"&&DNTP.currentLocale=="en"?a.length>2&&a.substr(a.length-3).match(/y$/)?a.substr(0,a.length-1)+"ies":a+"s":a},addCommas:function(a){a+="";x=a.split(".");x1=x[0];x2=x.length>1?"."+x[1]:"";for(a=/(\d+)(\d{3})/;a.test(x1);)x1=x1.replace(a,"$1,$2");return x1+x2},bind:function(a,b,c,d,e){e&&(a=e.getElementById(a));a&&(a.addEventListener?a.addEventListener(b,c,d):a.attachEvent&&a.attachEvent("on"+b,c))},bindClick:function(a,b,c){c&&
(a=c.getElementById(a));a&&(a.addEventListener?a.addEventListener("click",b,!0):a.attachEvent&&a.attachEvent("onclick",b))},bindClickArr:function(a,b,c){for(var d=0;d<a.length;d++)this.bindClick(a[d],b,c)},bindInfo:function(a,b){b&&(a=b.getElementById(a));if(a)this.bind(a,"focus",function(){if(this.getAttribute("info")==this.value)this.value=""},!0),this.bind(a,"blur",function(){if(this.value=="")this.value=this.getAttribute("info")},!0),a.value=a.getAttribute("info")},getCurrentLocale:function(){DNTP.currentLocale=
DNTP.currentLocale||typeof navigator!="undefined"&&navigator.language.replace(/\-.*/,"")||"en";return DNTP.currentLocale},getLinkUrl:function(a,b){b=b||{};b.type=a;b.lang=DNTP.getCurrentLocale();var c="",d;for(d in b)c+=c==""?"?":"&",c+=encodeURIComponent(d)+"="+encodeURIComponent(b[d]);return DNTP.LinkBaseUrl+c},addNotificationIframe:function(a,b){var c=b.createElement("script");c.type="text/javascript";var d="("+abineNotificationFrameScript+")();";b.all?c.text=d:c.appendChild(b.createTextNode(d));
d=b.createElement("iframe");d.style.position="fixed";d.style.top="1px";d.style.left="1px";d.style.border="10px solid black";d.style.boxShadow="5px 5px 5px #888888";d.style.backgroundColor="white";d.style.zIndex="2147483647";d.id="abineIframe";d.src=a;d.setAttribute("onMouseDown","abineMouseDown(event);");d.setAttribute("onMouseOut","abineMouseOut(event);");d.setAttribute("onMouseMove","abineMouseMove(event);");b.body.appendChild(c);b.body.appendChild(d)},setupNotifications:function(a){if(a&&a.messages)DNTP.notificationMessages=
a.messages},sendRequest:function(a,b,c,d){var e=createXMLHTTPObject();if(e){d=typeof d=="undefined"?!0:d;e.open(c?"POST":"GET",a,d);e.setRequestHeader("Cache-Control","no-cache");e.setRequestHeader("Pragma","no-cache");e.setRequestHeader("If-Modified-Since","Sat, 1 Jan 2000 00:00:00 GMT");c&&(e.setRequestHeader("Content-type","application/x-www-form-urlencoded"),e.setRequestHeader("Content-length",c.length));a=function(){e.readyState==4&&(e.status!=200&&e.status!=304&&e.status!=0?b(null,e):b(e.responseText,
e))};if(d)e.onreadystatechange=a;DNTP.setRequestHeaders(e);e.send(c);d||a()}},setRequestHeaders:function(a){var b=DNTP.installDate?DNTP.installDate.getFullYear()+"-"+(DNTP.installDate.getMonth()+1)+"-"+DNTP.installDate.getDate():"-1";a.setRequestHeader("X-DNT-OVersion",DNTP.oversion,!1);a.setRequestHeader("X-DNT-Cohort",b,!1);a.setRequestHeader("X-DNT-Version",DNTP.version+" FF "+DNTP.origin+" "+DNTP.revision,!1)},fireEvent:function(a,b){var c=a.ownerDocument;return c.createEvent?(c=c.createEvent("HTMLEvents"),
c.initEvent(b,!0,!0),!a.dispatchEvent(c)):(c=c.createEventObject(),a.fireEvent("on"+b,c))},fromDayOfYear:function(a,b){b||(b=(new Date).getFullYear());return new Date((new Date(b,0,1)).setMonth(0,a))},toDayOfYear:function(a){var a=a||new Date,b=new Date(a.getFullYear(),0,0);return Math.floor((a-b)/864E5)},saveNewTrackers:function(a){if(!DNTP.DISABLE_PRIVACY_UPDATE){var b=DNTP.Config.get("newTrackers",""),b=!b||b==""?[]:b.split(","),b=b.concat(a);DNTP.Config.set("newTrackers",b.join(","))}},getDailyTotals:function(a){if(DNTP.DISABLE_DAILY_TOTALS)return{};
a=JSON.parse(DNTP.Config.get("dailyTotals"+a,"{}"));a.hasBadTrackers=1;return a},updateDailyTotals:function(a,b){if(!DNTP.DISABLE_DAILY_TOTALS){var c=new Date,d=DNTP.toDayOfYear(c)+"",c=c.getFullYear(),e=JSON.parse(DNTP.Config.get("dailyTotals"+c,"{}"));d in e?e[d]+=b:e[d]=a+b;DNTP.Config.set("dailyTotals"+c,JSON.stringify(e));DNTP.DISABLE_BAD_TRACKERS||DNTP.saveBadTrackerTotals()}},isNewerVersion:function(a,b){var a=a.split("."),b=b.split("."),c=!1;if(a.length>b.length)c=!0;else for(var d=0;d<a.length;d++){if(parseInt(a[d],
10)<parseInt(b[d],10))break;if(parseInt(a[d],10)>parseInt(b[d],10)){c=!0;break}}return c},getVersion:function(){return DNTP.version},getOriginalVersion:function(){return DNTP.oversion},getFullVersion:function(){return DNTP.version+" FF "+DNTP.origin+" "+DNTP.revision},setupTag:function(a){DNTP.sendRequest(DNTP.TagUpdateUrl,function(b){if(b&&b!="")DNTP.Config.set("origin",b),ORIGIN=DNTP.origin=b;a()})},setText:function(a,b){if(a)a.textContent=b},setHtml:function(a,b){if(a)a.innerHTML="",a.appendChild(DNTP.parseHTML(a.ownerDocument,
b,!0))}},XMLHttpFactories=[function(){return framework.extension.getRequest()},function(){return Components.classes["@mozilla.org/xmlextras/xmlhttprequest;1"].createInstance()},function(){return new XMLHttpRequest}];function createXMLHTTPObject(){for(var a=!1,b=0;b<XMLHttpFactories.length;b++){try{a=XMLHttpFactories[b](),XMLHttpFactories=[XMLHttpFactories[b]]}catch(c){continue}break}return a}
function abineNotificationFrameScript(){var a=!1,b=null,c=null,d=null,e=null,g=1,h=1,i=300,j=150;window.abineMoveOutsideIframe=function(f){b&&c&&(d=b,e=c);b=f.clientX;c=f.clientY;if(a&&(f=document.getElementById("abineIframe")))d>h+i/2&&e>g+j/2?(j=Math.max(0,c-e+j),i=Math.max(0,b-d+i),f.style.height=j+"px",f.style.width=i+"px",f.style.cursor="nwse-resize"):(g=Math.max(0,c-e+g),h=Math.max(0,b-d+h),f.style.top=g+"px",f.style.left=h+"px",f.style.cursor="move")};window.abineMouseDown=function(b){a=!0;
if(b.clientX>h+i+20||b.clientY<g-20||b.clientX<h-20||b.clientY>g+j+20)(b=document.getElementById("abineIframe"))&&b.parentNode.removeChild(b),window.onmousemove=null,window.onmouseup=null,window.onmousedown=null};window.abineMouseUp=function(){a=!1};window.abineMouseMove=function(a){var b=document.getElementById("abineIframe");if(b)b.style.cursor=a.clientX>h+i/2&&a.clientY>g+j/2?"nwse-resize":"move",a.clientX>h+i&&a.clientY<g+10?(b.style.opacity=0.5,b.style.cursor="crosshair"):b.style.opacity=1};
window.abineMouseOut=function(){var a=document.getElementById("abineIframe");if(a)a.style.opacity=1};window.onmousemove=window.abineMoveOutsideIframe;window.onmouseup=window.abineMouseUp;window.onmousedown=window.abineMouseDown};