/*
***********************************************************************
 (C) 2008, 2009 by Abine, Inc. All Rights Reserved.

 This software is the confidential and proprietary information
 of Abine, Inc. ("Confidential Information"), subject
 to the Non-Disclosure Agreement and/or License Agreement you entered
 into with Abine. You shall use such Confidential Information only
 in accordance with the terms of said Agreement(s). Abine makes
 no representations or warranties about the suitability of the
 software. The software is provided with ABSOLUTELY NO WARRANTY
 and Abine will NOT BE LIABLE for ANY DAMAGES resulting from
 the use of the software.

 Contact license@getabine.com with any license-related questions.

 http://www.getabine.com

*/
var EXPORTED_SYMBOLS=["View"];Components.utils["import"]("resource://dntp/ff/overlay.js");Components.utils["import"]("resource://dntp/template.js");
function View(a,b){if(typeof b=="undefined")b=a,a=b.documentElement;this.doc=this.parentDoc=b;this.docElement=a;this.events=[];this.onload=[];this.doNotFade=!1;this.viewName="";this._width=MAX_IFRAME_WIDTH;this._top=View._top;this._right=View._right;this._left=View._left;this.fadeTimer=this.docElement._secondClick?15E3:5E3;if(DNTP.debugMode)this.fadeTimer=1E7;this.docElement._secondClick=!0;if(this.parentDoc._currentView)try{this.parentDoc._currentView.close(!0)}catch(c){}this.parentDoc._currentView=
this;this.attachUnloadHandler()}
View.prototype={show:function(){this.iframe=this.createIframe();var a=this,b=function(){a.doc=a.iframe.contentDocument;if(a.doc){a.win=a.doc.defaultView;var b=a.doc.createElement("div");b.setAttribute("id","thePopup");a.viewName!="notification"?(b.style.boxShadow="0 0 3px 3px #eee",b.style.margin="3px"):b.style.background="transparent";if(a.noTemplate)b.className=a.viewName,DNTP.setHtml(b,a.render());else{a.addOnLoad(function(){a.changeInviteLink()});b.className=a.className()+" "+a.viewName;var c=
(new DNTP.Template("layout",a.win)).render(a,{body:a.render(),notifications:a.getNotifications()});DNTP.setHtml(b,c);a.setupAutoClose()}a.doc.documentElement.appendChild(b);a.postShow()}else a.close()};if(this.iframe.alreadyLoaded){this.resetFade();var c=this.doc.getElementById("thePopup");c&&c.parentNode.removeChild(c);b()}else this.iframe.addEventListener("load",b,!1),this.docElement.appendChild(this.iframe)},attachUnloadHandler:function(){var a=this;this.windowUnloadHandler=function(){a.close()};
DNTP.bind(this.parentDoc.defaultView.top,"unload",this.windowUnloadHandler,!1)},postShow:function(){this.startObservers();this.sendOnLoadEvent();this.autoSizeIframe();this.fixExternalLinks();this.noTemplate||this.markNotificationsSeen()},markNotificationsSeen:function(){DNTP.NotificationManager.markNotificationsSeen(this.docElement.abineNotifications,this.parentDoc)},changeInviteLink:function(){if(parseInt(DNTP.Config.get("howitworks.clicked",0))==0){var a=this.doc.getElementById("DNTPinviteLink");
a&&(DNTP.setText(a,DNTP._("dntp.howthisworks")),a.setAttribute("href","http://www.donottrackplus.com/link.php?type=how"),DNTP.bind(a,"click",function(){DNTP.Config.set("howitworks.clicked",1);return!0},!0))}},openUrlInNewTab:function(a){a=this.fixExternalLink(a);DNTP.openWindowInNewTab(a)},fixExternalLinks:function(){for(var a=this.doc.getElementsByClassName("externalLink"),b=DNTP.installDate?DNTP.installDate.getTime():(new Date).getTime(),b=Math.round(((new Date).getTime()-b)/6E4),c=0;c<a.length;c++)if(a[c].href&&
a[c].href.match(/^http[s]?:\//)&&(!a[c].className||a[c].className.indexOf("plainLink")==-1))a[c].href=a[c].href.replace(/&m=.+]/,"")+"&m="+b+"&v="+DNTP.version+"&o="+DNTP.origin+"&r="+DNTP.revision+"&ov="+DNTP.oversion},fixExternalLink:function(a){var b=DNTP.installDate?DNTP.installDate.getTime():(new Date).getTime(),b=Math.round(((new Date).getTime()-b)/6E4);a&&a.match(/^http[s]?:\//)&&(a=a.replace(/&m=.+]/,"")+"&m="+b+"&v="+DNTP.version+"&o="+DNTP.origin+"&r="+DNTP.revision+"&ov="+DNTP.oversion);
return a},createIframe:function(){var a=this.parentDoc.getElementById("dntpContainerFrame");if(a&&this.iframe==a)return a.alreadyLoaded=!0,a;a&&a.parentNode.removeChild(a);var b="abine://blank.html";DNTP.theme&&DNTP.theme!=""&&(b="abine://themes/"+DNTP.theme+"/blank.html");a=this.parentDoc.createElement("iframe");b={scrolling:"no",allowTransparency:"true",frameborder:"0",id:"dntpContainerFrame",src:b};b.style="position: fixed; right: "+this._right+"px; left: "+this._left+"px; top: "+this._top+"px; width: "+
this._width+"px; height: 50px; padding: 0; margin: 0; border: 0; z-index: 2147483647; overflow: hidden;";for(var c in b)a.setAttribute(c,b[c]);return a},autoSizeIframe:function(){if(this.doc){var a=this.doc.getElementById("thePopup");if(a)this.iframe.style.height=a.offsetHeight+8+"px",this.iframe.style.width=a.offsetWidth+20+"px"}},className:function(){return"bluePopup"},close:function(a){DNTP.clearTimeout(this.animateBtnTimer);this.iframe&&this.iframe.parentNode&&this.iframe.parentNode.removeChild(this.iframe);
if(this.onClosed)try{this.onClosed()}catch(b){}if(this.parentDoc)this.windowUnloadHandler&&this.parentDoc.defaultView.top.removeEventListener("unload",this.windowUnloadHandler,!1),this.windowUnloadHandler=null,this.parentDoc._currentView=null;this.iframe=this.doc=null;this.events=[];this.onload=[];this.parentDoc=this.docElement=null;a!==!0&&DNTP.closePopup()},render:function(){return""},renderPartialInElement:function(a,b,c,d){if(a=this.$(a)){if(d){var e=c,c={},f;for(f in e)c[f]=e[f];for(f in d)c[f]=
d[f]}d=this.events;f=this.onload;this.events=[];this.onload=[];b=new DNTP.Template(b,this.win);DNTP.setHtml(a,b.render(this,c));this.sendOnLoadEvent();this.startObservers();this.fixExternalLinks();this.events=d;this.onload=f}},showGlobal:function(){DNTP.show_global_trackers(this.parentDoc,this.doc);return!1},$:function(a){return this.doc?this.doc.getElementById(a):null},observe:function(a,b,c,d){if(typeof a=="object"&&a.length)for(var e=0;e<a.length;e++)this.events.push([a[e],b,c,d||!1]);else this.events.push([a,
b,c,d||!1])},observeNow:function(a,b,c,d){this.observe(a,b,c,d);this.startObservers()},addOnLoad:function(a){this.onload.push(a)},startObservers:function(){for(var a=0;a<this.events.length;a++)if(!this.events[a][3]){var b=this.$(this.events[a][0]);b&&DNTP.bind(b,this.events[a][1],this.events[a][2],!1)}this.events=[]},sendOnLoadEvent:function(){for(var a=0;a<this.onload.length;a++){try{this.onload[a]()}catch(b){}this.onload[a]=null}this.onload=[]},bind:function(a){var b=a,c=DNTP.$A(arguments),d=this;
c.shift();return function(){return b.apply(d,c.concat(DNTP.$A(arguments)))}},setupAutoClose:function(){this.resetFade();if(!this.doNotFade&&this.doc&&this.iframe){var a=this;this.parentDoc.abineMouseOver||this.setupFade();this.observe("thePopup","mouseout",function(b){for(b=b.relatedTarget?b.relatedTarget:b.toElement;b&&b.nodeName!="BODY";){if(b.id==this.id)return;b=b.parentNode}a.setupFade()});this.observe("thePopup","mouseover",function(){a.resetFade()})}},setupFade:function(){if(this.doc&&this.win){var a=
this;this.resetFade();this.win.autoClosePopup=this.win.setTimeout(function(){a.startFade()},this.fadeTimer)}},resetFade:function(){if(this.doc&&this.win){if(this.win.windowFade)this.win.clearTimeout(this.win.windowFade),this.win.windowFade=null;if(this.win.autoClosePopup)this.win.clearTimeout(this.win.autoClosePopup),this.win.autoClosePopup=null;var a=this.$("thePopup");if(a)a.style.opacity="1.0"}},startFade:function(){if(!this.doNotFade&&this.doc&&this.iframe){var a=this.$("thePopup"),b=this;this.win.windowFade=
this.win.setInterval(function(){var c=a.style.opacity;c>=0.05?a.style.opacity=c-0.05:(a.style.display="none",b.win.clearInterval(b.win.windowFade),b.win.windowFade=null,b.close())},50)}},getNotifications:function(){if(this.docElement){if(!this.docElement.abineNotifications)try{DNTP.computeNotifications(this.doc,this.docElement)}catch(a){}for(var b=this.docElement.abineNotifications||[],c=!1,d=0;d<4&&b;d++)if(b[d]){c=!0;break}if(!c)return null;notifications=[];for(d=0;d<=3;d++)if(c=b[d]){var e=c.link,
f=c.impressions;c.link&&(e="http://donottrackplus.com/link.php?type="+c.link+"&msg="+escape(c.msg)+"&c="+(f||1),c.linkType=="iframe"&&(e=this.fixExternalLink(e)));notifications.push({id:"notif"+d,label:c.msg,link:e,iframe:c.linkType=="iframe",image:c.image,alert:c.alert,badTracker:c.badTracker});if(d==0)break}return notifications}},addNotificationIframe:function(a){DNTP.addNotificationIframe(a,this.doc.defaultView.top.document);this.close();return!1},verticallyCenter:function(a){var b=this.$(a);if(a&&
b)b.style.top=Math.floor((b.parentNode.offsetHeight-b.offsetHeight)/2)-1+"px"},showElement:function(a){var b=a;typeof a=="string"&&(b=this.$(a));if(b)b.style.display=""},hideElement:function(a){var b=a;typeof a=="string"&&(b=this.$(a));if(b)b.style.display="none"},tabs:function(a,b){var c=this.$(a);if(c){var d=this,e=c.getElementsByTagName("li"),f=function(a,b){for(var c=0;c<e.length;c++)b==e[c].id?(e[c].className="selected",d.$(e[c].id+"Content").style.display="block"):(e[c].className="",d.$(e[c].id+
"Content").style.display="none"),a===!0&&DNTP.bindClick(e[c],function(a){return function(){f(!1,a.id)}}(e[c]));DNTP.setTimeout(function(){d.autoSizeIframe()},500)};f(!0,b||e[0].id)}},addCss:function(a){var b=a.replace(/[^a-z]+/gi,"");if(!this.doc.getElementById(b)){var c=this.doc.createElement("link");c.setAttribute("rel","stylesheet");c.setAttribute("type","text/css");c.setAttribute("href",a);c.setAttribute("id",b);this.doc.getElementsByTagName("head")[0].appendChild(c)}},animateButton:function(a,
b,c){a.setAttribute("animateProgress","1");this.animateButtonImpl(this.getButton(a),b,function(){a.removeAttribute("animateProgress");c()})},animateButtonImpl:function(a,b,c){if(a&&a.firstChild){for(var d=a.firstChild;!d.nodeName||d.nodeName.toUpperCase()!="IMG";)if(d.nextSibling)d=d.nextSibling;else break;var e=d.style.marginLeft,e=e==""?b<0?22:0:parseInt(e);if(b<0&&e<=0||b>0&&e>=22)d.style.marginLeft="",c();else{e+=1*b;d.style.marginLeft=e+"px";var f=this;DNTP.clearTimeout(this.animateBtnTimer);
this.animateBtnTimer=DNTP.setTimeout(function(){f.animateButtonImpl(a,b,c)},10)}}},getButton:function(a){for(var b=null,c=0;c<a.childNodes.length;c++){var d=a.childNodes[c];if(d.className&&d.className.indexOf("button")!=-1){b=d;break}}return b},getNumberSuffix:function(a){var b=["th","st","nd","rd"];return a/10%10!=1&&(a%=10,a<4)?b[a]:"th"}};View.registerDerivedClass=function(a){for(var b in View.prototype)b in a.prototype||(a.prototype[b]=View.prototype[b]);a.prototype.parentConstructor=View};
View._top=5;View._right=0;View._left="auto";View.setPosition=function(a,b){View._top=a;View._left=b;View._right="auto"};DNTP.View=View;var MAX_IFRAME_WIDTH=360;