/*
***********************************************************************
 (C) 2008, 2009 by Abine, Inc. All Rights Reserved.

 This software is the confidential and proprietary information
 of Abine, Inc. ("Confidential Information"), subject
 to the Non-Disclosure Agreement and/or License Agreement you entered
 into with Abine. You shall use such Confidential Information only
 in accordance with the terms of said Agreement(s). Abine makes
 no representations or warranties about the suitability of the
 software. The software is provided with ABSOLUTELY NO WARRANTY
 and Abine will NOT BE LIABLE for ANY DAMAGES resulting from
 the use of the software.

 Contact license@getabine.com with any license-related questions.

 http://www.getabine.com

*/
var EXPORTED_SYMBOLS=[];Components.utils["import"]("resource://dntp/ff/overlay.js");Components.utils["import"]("resource://dntp/view.js");var dataClickTimer=null,chartClickTimer=null;View.Alert=function(){this.parentConstructor.apply(this,arguments);this.viewName="alert"};
View.Alert.prototype={render:function(){if(this.docElement){var b=this;this.removeTrackerChangeHandler();var c="",a=this.docElement.toggledOff;this.setupData();this.separateSocialTrackers();var d=this.trackers.length+this.optouts.length+this.social.length,e=this.currentSocial;this.domain in DNTP.socialMap&&this.bCount[DNTP.socialMap[this.domain].trackerName]&&(e+=this.bCount[DNTP.socialMap[this.domain].trackerName]);var g=this.docElement.funWord||Math.floor(Math.random()*16)+1;this.docElement.funWord=
g;this.globalTotal=this.globalTotalBlocked+this.globalTotalOptout;d={host:this.host,hostname:this.host?this.host.replace(/(\.co)?\.[a-z]+$/i,""):null,domain:this.domain,off:this.docElement.abineDisabled,toggledOff:this.docElement.toggledOff,abineMessage:this.docElement.abineMessage,firstPartySocial:this.domain in DNTP.socialMap,social:this.social,blocked:this.blocked,optouts:this.optouts,trackers:this.trackers,totalTrackers:d,socialBlocked:this.socialBlocked,trackersBlocked:this.trackersBlocked,currentSocialCount:e,
globalTotal:this.globalTotal,globalTrackerTotal:this.globalTotalBlocked-this.globalSocialTotal,globalOptoutTotal:this.globalTotalOptout,globalSocialTotal:this.globalSocialTotal,optoutEnabled:DNTP.Config.getWriteCookies(),newBadge:DNTP.BadgeManager.getUnviewedBadge(),badges:DNTP.BadgeManager.getBadges(),funWordIndex:g,skipTotals:!1};d.newBadge&&(DNTP.BadgeManager.mark_viewed(),DNTP.update_toolbar_icon(this.parentDoc));if(this.docElement.toggledOff||this.docElement.abineMessage||this.docElement.abineDisabled)this.docElement.abineMessage=
null,this.docElement.toggledOff=null,d.skipTotals=!0;e=new DNTP.Template("privacy");c+=e.render(this,d);this.restoreTrackers();this.addOnLoad(function(){!a&&DNTP.Events&&b.addTrackerChangeHandler(b.trackers.length+b.optouts.length+b.social.length)});return c}},setupData:function(){this.host=this.domain=this.docElement.topDomain||"";this.trackers=this.docElement.abineTracking=this.docElement.abineTracking||{length:0};this.blocked=this.docElement.abineBlocked=this.docElement.abineBlocked||{length:0};
this.social={length:0};this.bCount=JSON.parse(DNTP.policy.getBlockedCount());this.globalSocialTotal=0;for(var b in DNTP.socialBlocked)this.bCount[b]||(this.bCount[b]=0),this.bCount[b]+=parseInt(DNTP.Config.get("tracking.totalblocked."+b,0)),this.globalSocialTotal+=this.bCount[b];DNTP.updateOptouts(this.docElement);b=parseInt(DNTP.Config.get("tracking.totalblocked.optout",0));this.globalTotalOptout=DNTP.totalOptout+b;this.globalTotalBlocked=DNTP.totalBlocked+parseInt(this.bCount.total)-b;this.docElement.abineDomains=
this.docElement.abineDomains||{length:0};this.optouts=this.docElement.abineOptout=this.docElement.abineOptout||{length:0};this.currentSocial=0;if(this.domain in DNTP.socialMap&&this.bCount[DNTP.socialMap[this.domain].trackerName])this.currentSocial=this.bCount[DNTP.socialMap[this.domain].trackerName];DNTP.update_toolbar_icon(this.parentDoc)},separateSocialTrackers:function(){var b={length:0};this.socialBlocked=this.trackersBlocked=0;for(var c in this.trackers)if(c!="length"){var a=c in this.blocked;
a&&this.trackersBlocked++;c in DNTP.socialImages&&(b[c]=this.trackers[c],b.length++,delete this.trackers[c],this.trackers.length--,a&&(this.socialBlocked++,this.trackersBlocked--))}this.social=this.docElement.abineSocial=b;this.numSocial=b.length},restoreTrackers:function(){for(var b in this.social)b!="length"&&(this.trackers[b]=this.social[b],this.trackers.length++);this.docElement.abineSocial=null},toggleOnOff:function(){var b=!this.docElement.abineDisabled;DNTP.toggle_tracker(this.parentDoc,this.doc,
b,"*",this.host);this.docElement.abineDisabled=b;this.docElement.toggledOff=!0;b?DNTP.showAllowedSites():(this.doNotAutoRefresh=1,this.show())},getNewVersionLink:function(){return""},getTextColor:function(b,c,a){var d=0,e;for(e in b)e!="length"&&e in c&&(!a||!(e in a))&&d++;var g=0;for(e in c)e!="length"&&(!a||!(e in a))&&g++;if(d==g)return"#01a650 !important;";else{for(e in c)if(e!="length"&&c[e]!=2&&!b[e]&&(!a||!(e in a)))return"#d6170e !important;";return"#fd8801 !important;"}},getTrackerImage:function(b,
c){var a="company-green.png",d;for(d in c)if(!(d=="length"||d in this.social))if(!(d in b)&&c[d]!=2){a="company-red.png";break}else c[d]==2&&!(d in b)&&(a="company-yellow.png");return a},updateHeaderText:function(b){var c=this.$("DNTPsocialText");if(c&&this.social.length>0){var a=this.getTextColor(this.blocked,this.social),a=DNTP._("dntp.socialtracking",this.social.length,DNTP._(DNTP.plural("dntp.count.socialbutton",this.social.length)))+"<span id=DNTPsocialTextColor class=count style='color:"+a+
"'>"+this.socialBlocked+" "+DNTP._(DNTP.plural("dntp.Mblocked",this.socialBlocked))+"</span>";DNTP.setHtml(c,a)}if((c=this.$("DNTPtrackerText"))&&this.trackers.length>0){var a=this.getTextColor(this.blocked,this.trackers,this.social),d=this.trackers.length-this.social.length,a=DNTP._("dntp.trackingcompany",d,DNTP._(DNTP.plural("dntp.company",d)))+" <span class=count style='letter-spacing:normal;color:"+a+"'>"+this.trackersBlocked+" "+DNTP._(DNTP.plural("dntp.Fblocked",this.trackersBlocked))+"</span>";
DNTP.setHtml(c,a+(b?b:""))}(c=this.$("toggleSiteOnMsg"))&&DNTP.setHtml(c,DNTP._("onoff.on.here",this.blocked.length+"",DNTP._("dntp."+(this.blocked.length!=1?"companies":"company"))))},updateHeaderIcons:function(){var b=this.$("DNTPtrackerIcon");b&&b.setAttribute("src",DNTP.getImageUrl(this.getTrackerImage(this.blocked,this.trackers)));(b=this.$("DNTPsocialIcon"))&&b.setAttribute("src",DNTP.getImageUrl(this.getSocialImage(this.blocked,this.social)))},getSocialImage:function(b,c){var a;if(this.domain in
DNTP.socialMap)a=DNTP.socialMap[this.domain].blockImg;else{a="social-green.png";for(var d in c)if(d!="length")if(!(d in b)&&c[d]!=2){a="social-red.png";break}else c[d]==2&&!(d in b)&&(a="social-yellow.png")}return a},getNotifyHtml:function(){var b=JSON.parse(DNTP.Config.get("notify","{}")),c="";b&&b.id&&!DNTP.Config.get("notify.done."+b.id,null)&&b.link.match(/^http[s]?:.*/)&&(c='<a id="spNotify" href="'+DNTP.getNotifyUrl(b.link)+'" target=_blank>'+b.text+"</a>",this.observe("spNotify","click",function(){var a=
JSON.parse(DNTP.Config.get("notify","{}"));DNTP.Config.set("notify.done."+a.id,"1")}));return c},adOverlayOptionClicked:function(){DNTP.adOverlayEnabled?(DNTP.Config.set("ad.overlay","0"),DNTP.adOverlayEnabled=!1):(DNTP.Config.set("ad.overlay","1"),DNTP.adOverlayEnabled=!0)},analyticsOptionClicked:function(){DNTP.Config.get("GA.tracking","1")=="1"?DNTP.Config.set("GA.tracking","0"):DNTP.Config.set("GA.tracking","1")},checkAllowedByDomain:function(b){return this.docElement.abineTracking[b]==2?!1:!0},
socialTrackerClicked:function(b,c){for(var c=c||event,a=c.target||c.srcElement;a.nodeName.toUpperCase()!="LI";)a=a.parentNode;a=!(b in this.blocked);this.autoSizeIframe();var d=this.$("DNTPsocialButtonText"+b.replace(" ","")),e=this.social[b]==2?".recommended":"";d&&(a?DNTP.setHtml(d,"<img src='"+DNTP.getImageUrl("accept.gif")+"' /> "+DNTP._("dntp.capblockedhere"+e)):DNTP.setHtml(d,"<img src='"+DNTP.getImageUrl("cancel.gif")+"' /> "+DNTP._("dntp.notblockedhere"+e)));DNTP.toggle_social(this.parentDoc,
this.doc,a,b,this.host,!1);DNTP.update_toolbar_icon(this.parentDoc);a?this.socialBlocked++:(this.showSocialButton(b),this.docElement.abineMessage=null,this.socialBlocked--);this.updateHeaderText();this.updateHeaderIcons();if(this.$("abineMsg"))this.$("abineMsg").style.display="none",this.$("msgBorder").style.border="0px solid";return!1},showSocialButton:function(b){DNTP.SocialButtons.commonClickHandlerFromPopup(this.parentDoc,this.host,b,b)},trackerClicked:function(b,c){for(var a=this,c=c||event,
d=c.target||c.srcElement;d.nodeName.toUpperCase()!="LI";)d=d.parentNode;d=!(b in this.blocked);DNTP.toggle_tracker(this.parentDoc,this.doc,d,b,this.host,!1);d?this.trackersBlocked++:this.trackersBlocked--;this.updateHeaderIcons();DNTP.update_toolbar_icon(this.parentDoc);d?(this.updateHeaderText(' <br/><a href="#" style="" id="DNTPblockMore">'+DNTP._("dntp.blockall")+"</a>"),DNTP.bindClick("DNTPblockMore",function(){DNTP.toggle_all_trackers_on_site(a.parentDoc,a.doc,a.host,!0);DNTP.update_toolbar_icon(a.parentDoc);
a.trackersBlocked=a.trackers.length-a.social.length;a.socialBlocked=a.social.length;a.updateHeaderIcons();a.updateHeaderText(' <br/><a href="#" id="DNTPblockMore">'+DNTP._("dntp.blockalleverywhere")+"</a>");DNTP.bindClick("DNTPblockMore",function(){DNTP.Config.set("global.blocked","1");DNTP.toggle_all_trackers_no_ui(!0);a.updateHeaderIcons();a.updateHeaderText();DNTP.update_toolbar_icon(a.parentDoc);a.show()},a.doc)},a.doc)):(this.updateHeaderText('<br/><a href="#" id="DNTPunblockMore">'+DNTP._("dntp.unblockall")+
"</a>"),DNTP.bindClick("DNTPunblockMore",function(){DNTP.toggle_all_trackers_on_site(a.parentDoc,a.doc,a.host,!1);DNTP.update_toolbar_icon(a.parentDoc);a.docElement.abineMessage=null;a.socialBlocked=0;a.trackersBlocked=0;a.updateHeaderIcons();a.updateHeaderText(' <br/><a style="font-size: smaller;" href="#" id="DNTPunblockMore">'+DNTP._("dntp.unblockalleverywhere")+"</a>");DNTP.bindClick("DNTPunblockMore",function(){DNTP.Config.set("global.blocked","0");DNTP.toggle_all_trackers_no_ui(!1);a.updateHeaderIcons();
a.updateHeaderText();DNTP.update_toolbar_icon(a.parentDoc);a.show()},a.doc)},a.doc));return!1},addTrackerChangeHandler:function(b){var c=this;this.removeTrackerChangeHandler();this.processedChangeEvent=!1;this.trackerChangesHandle=function(a){if(!c.processedChangeEvent&&c.parentDoc==a&&b!=c.trackers.length+c.optouts.length+c.social.length&&c.doNotAutoRefresh===!1)c.refreshTimer&&DNTP.clearTimeout(c.refreshTimer),c.resetFade(),c.refreshTimer=DNTP.setTimeout(function(){c.processedChangeEvent=!0;c.removeTrackerChangeHandler();
c.show()},1500)};DNTP.Events.addListener("TrackerCountChanged",this.trackerChangesHandle)},removeTrackerChangeHandler:function(){this.trackerChangesHandle&&DNTP.Events.removeListener("TrackerCountChanged",this.trackerChangesHandle);this.trackerChangesHandle=null},onClosed:function(){this.removeTrackerChangeHandler()},toggleBlock:function(b,c){c=c||event;if((c.target||c.srcElement).nodeName.toUpperCase()!="A"){var a=["DNTPsocial","DNTPoptouts","DNTPtrackers"],d=this.$(b);d.style.display=d.style.display==
""?"none":"";for(d=0;d<a.length;d++)b!=a[d]&&this.hideElement(a[d]);this.autoSizeIframe()}},showAllBlocks:function(){for(var b=["DNTPsocial","DNTPoptouts","DNTPtrackers"],c=!0,a=0;a<b.length;a++){var d=this.$(b[a]);if(d&&d.style.display=="none"){c=!1;break}}for(a=0;a<b.length;a++)c?this.hideElement(b[a]):this.showElement(b[a]);this.autoSizeIframe()},getOptoutToggleBlock:function(){var b="&nbsp;&nbsp;";b+=DNTP.Config.getWriteCookies()?" <span style='cursor:pointer;float:left;' id='toggleOptouts'>"+
DNTP._("dntp.optingout")+" <span style='float:right;margin-top:-3px;margin-right:21px;text-decoration:none;color:#000;font-weight:100;font-style:normal;'><img style='vertical-align:middle;' src='"+DNTP.getImageUrl("accept.gif")+"' /> "+DNTP._("dntp.optoutson")+"</span></span>":" <span style='cursor:pointer;float:left;' id='toggleOptouts'>"+DNTP._("dntp.notoptingout")+" <span style='float:right;margin-top:-3px;margin-right:24px;text-decoration:none;color:#000;font-weight:100;font-style:normal;'><img style='vertical-align:middle;' src='"+
DNTP.getImageUrl("cancel.gif")+"' /> "+DNTP._("dntp.optoutsoff")+"</span></span>";this.observe("toggleOptouts","click",function(b){b=b||event;for(b=b.target||b.srcElement;b.id!="toggleOptouts";)b=b.parentNode;var a=b.ownerDocument;DNTP.Config.getWriteCookies()?(DNTP.Config.setWriteCookies(0),DNTP.setHtml(b,DNTP._("dntp.notoptingout")+" <span style='float:right;margin-top:-3px;margin-right:23px;text-decoration:none;color:#000;font-weight:100;font-style:normal;'><img style='vertical-align:middle;padding-top:-3px;' src='"+
DNTP.getImageUrl("cancel.gif")+"' /> "+DNTP._("dntp.optoutsoff")+"</span>"),a.getElementById("optoutColor").style.color="red",DNTP.setText(a.getElementById("optoutText"),DNTP._("dntp.unblocked"))):(DNTP.Config.setWriteCookies(1),DNTP.setHtml(b,DNTP._("dntp.optingout")+" <span style='float:right;margin-top:-3px;margin-right:20px;text-decoration:none;color:#000;font-weight:100;font-style:normal;'><img style='vertical-align:middle;' src='"+DNTP.getImageUrl("accept.gif")+"' /> "+DNTP._("dntp.optoutson")+
"</span>"),a.getElementById("optoutColor").style.color="green",DNTP.setText(a.getElementById("optoutText"),DNTP._("dntp.Fblocked")))});return b},renderChart:function(){function b(){var a=c.$("DNTPtrackingAttempts");if(a)a.style.height="30px";(a=c.$("latestBadge"))&&(a.className+=" noGraph");if(a=c.$("chartdiv"))a.style.display="none"}var c=this;if(!this.$("chartdiv")||!this.win)b();else{for(var a="Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),d=["F1E7BF","F1EACD"],e=new Date,g=DNTP.toDayOfYear(e),
k=-1,q={},r=[],s=[],m=0,f=e,l=DNTP.getBadTrackerTotals(),u=[],e=0;e<=30;e++){var i=f.getFullYear();k!=i&&(k=i,q[i]=DNTP.getDailyTotals(k));var h=-1;g in q[k]&&(h=q[k][g]);r.push(h);s.push(f);var h=0,t=null,j="",i=!0,p;for(p in l.totals)try{var o=l.daily[p][k][g];if(o&&typeof o!="undefined"){var y="<tr><td>"+p+'</td><td align="right">'+o+"</td></tr>";o>h?(j=y+j,h=o,t=p):j+=y;i=!1}}catch(z){}i||(i=a[f.getMonth()]+" "+f.getDate()+" "+f.getFullYear(),j='<tr><th colspan=2 style="border-bottom: 1px solid;">'+
i+"</th></tr>"+j,j='<table cellpadding="2" cellspacing="0" style="margin:0;padding:0;">'+j+"</table>");u.push({name:t,count:h,tooltip:j});g--;f=new Date(f.getFullYear(),f.getMonth(),f.getDate()-1);g<=0&&(g=DNTP.toDayOfYear(f))}q=[];g=[];p=[];o=[];k=[];l=-1;for(e=r.length-1;e>=0;e--)h=r[e],f=s[e],l==-1&&h==-1&&e>7||(i=f.getMonth(),h==-1?h=l:l=h,h==-1&&(h=0),g.push(h),p.push(f));var v=Math.floor(g.length/5);v<=1&&(v=2);l=s=r=-1;e=t=0;for(j=g.length-1;e<g.length;e++,j--){h=g[e];f=p[e];i=f.getMonth();
i!=r&&(r=i,s++,s>=d.length&&(s=0));if(l==-1||l>h)l=h;m<h&&(m=h);i=a[i]+" "+f.getDate();e%v==0?(f=g[e],e>0&&(f-=g[e-1]),t<f&&(t=f),o.push([i,f,"","",i+" = "+f])):o.push([i,0,"",""," "]);u[j].name&&k.push([i,0,5,{label:u[j].name,color:"#01A650"},u[j].tooltip]);q.push([i,h,"","",i+" = "+h])}if(m==0)b();else{m+=m/4;m=Math.round((m+50)/100)*100;for(e=0;e<k.length;e++)k[e][1]=Math.floor(m-m/8);var n=this.win.$,w={series:[{renderer:n.jqplot.LineRenderer,rendererOptions:{},lineWidth:2,fillAndStroke:!0,fill:!0,
fillColor:"#f7f2e1",fillAlpha:0.9,showMarker:!0,markerOptions:{show:!0,style:"filledCircle",lineWidth:1,size:4,color:"#01A650",shadow:!0,shadowAngle:45,shadowOffset:1,shadowDepth:3,shadowAlpha:0.01}}],highlighter:{show:!0,showMarker:!0,tooltipAxes:"y",tooltipLocation:"n",yvalues:4,formatString:'<div class="jqplot-highlighter" style="background-color:#fafad2;"><span style="display:none">%s%s%s</span>%s</div>'},seriesColors:["#6B9A00","#6B9A00"],grid:{drawGridLines:!0,gridLineColor:"#eee",background:"#fff",
borderColor:"#ccc",borderWidth:0.5,shadow:!1},seriesDefaults:{},axesDefaults:{tickRenderer:n.jqplot.CanvasAxisTickRenderer,tickOptions:{fontSize:"6pt"}},axes:{xaxis:{renderer:n.jqplot.CategoryAxisRenderer,tickOptions:{angle:-30,showGridline:!1,formatter:function(){var a=-1;return function(b,c){a++;return a%v==0?c:" "}}()}},yaxis:{label:DNTP._("chart.y.axis.title"),labelRenderer:n.jqplot.CanvasAxisLabelRenderer,labelOptions:{fontSize:"7pt"},autoscale:!0,min:Math.floor(l),max:Math.floor(m),angle:90},
y2axis:{label:DNTP._("chart.y2.axis.title"),labelRenderer:n.jqplot.CanvasAxisLabelRenderer,labelOptions:{fontSize:"7pt"},autoscale:!0,angle:90,min:0,max:Math.floor(t*2.3)}}},a=[q];k.length>0&&(a.push(k),w.series.push({renderer:n.jqplot.BubbleRenderer,rendererOptions:{bubbleAlpha:0.6,highlightAlpha:0.8,showLabels:!1,autoscaleBubbles:!1},shadow:!0,shadowAlpha:0.05}));var a=new n.jqplot("chartdiv",a,w),x=this;a.series[0].highlightColorGenerator={get:function(){new n.jqplot.ColorGenerator(w.seriesColors)}};
a.series[0].labels=[];for(e=0;e<g.length;e++)a.series[0].labels.push(null);n("#chartdiv").bind("jqplotDataClick",function(a,b,c,d){DNTP.clearTimeout(dataClickTimer);DNTP.clearTimeout(chartClickTimer);dataClickTimer=DNTP.setTimeout(function(){dataClickTimer=null;d.length>3&&d[3]!=""?x.openUrlInNewTab(DNTP.getLinkUrl("badTracker."+d[3].label)):x.openUrlInNewTab(DNTP.getLinkUrl("dntReport"))},200)});if(a=this.$("stats"))a.style.display="";if(a=this.$("nextBadgeMsg"))if(a.style.display="",!this.$("latestBadge"))a.style.top=
"29px",a.style.left="55px";this.observeNow("chartdiv","mouseup",function(){chartClickTimer=DNTP.setTimeout(function(){x.openUrlInNewTab(DNTP.getLinkUrl("dntReport"))},500)})}}}};View.registerDerivedClass(View.Alert);