DEFAULT_USER=`whoami`

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="agnoster"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(bundler capistrano coffee command-not-found django gem git git-extras git-flow history-substring-search python rails3 rake rsync ruby rvm screen)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
RUBY_VERSION=`rvm-prompt v p`
export PATH=~/.rvm/gems/ruby-$RUBY_VERSION/bin:~/.rvm/gems/ruby-$RUBY_VERSION@global/bin:~/.rvm/rubies/ruby-$RUBY_VERSION/bin:~/.rvm/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

# ... => ../..
rationalise-dot() {
  if [[ $LBUFFER = *.. ]]; then
    LBUFFER+=/..
  else
     LBUFFER+=.
  fi
}
zle -N rationalise-dot
bindkey . rationalise-dot

# Set 256 Colors Term
if [ "$TERM" = "xterm" ] ; then
    if [ -z "$COLORTERM" ] ; then
        if [ -z "$XTERM_VERSION" ] ; then
            echo "Warning: Terminal wrongly calling itself 'xterm'."
        else
            case "$XTERM_VERSION" in
                "XTerm(256)") TERM="xterm-256color" ;;
                "XTerm(88)") TERM="xterm-88color" ;;
                "XTerm") ;;
                *) echo "Warning: Unrecognized XTERM_VERSION: $XTERM_VERSION" ;;
            esac
        fi
    else
        case "$COLORTERM" in
            gnome-terminal) TERM="gnome-256color" ;;
            Terminal) TERM="xterm-256color";;
            *) echo "Warning: Unrecognized COLORTERM: $COLORTERM" ;;
        esac
    fi
fi

export EDITOR='vi'
